/** FleetEncounterContext.adjustPlayerReputation: a separate, once-per-encounter dialog operation. */
import {encounterCheck as check,encounterCall as call,encounterBool as bool,encounterFloat as num,originalEncounterSide} from './OriginalEncounterState.mjs';
import {originalBattleSideFor,originalBattleIsPlayerSide,originalBattleIsInvolved,originalBattlePlayerSide,originalBattlePrimary,originalBattleSnapshotFor,originalBattleFleetKnowsPlayer} from './OriginalCampaignBattle.mjs';
import {originalEncounterPlayerContribution} from './OriginalEncounterLoot.mjs';
import {originalFleetPointCost} from './OriginalFleetData.mjs';
import {setOriginalConstructedFleetDestination} from './OriginalCampaignFleetMotion.mjs';
import {originalEntityMemoryWithoutUpdate,originalCampaignMemoryBoolean,setOriginalCampaignMemory,addOriginalCampaignMemoryRequired,originalCampaignMemoryContains} from './OriginalCampaignMemory.mjs';
import {createOriginalReputationEnvelope} from './OriginalCoreReputation.mjs';
const f=Math.fround,player=s=>call(s,'readBattlePlayerFleet'),faction=fleet=>{check(fleet?.campaign?.faction&&typeof fleet.campaign.faction.factionId==='string','Actual fleet Faction identity required');return fleet.campaign.faction;};
function otherSide(b,s){const own=originalBattlePlayerSide(b,s);return own===b.sideOne?b.sideTwo:own===b.sideTwo?b.sideOne:null;}
function snapshot(b,side){const value=originalBattleSnapshotFor(b,side);check(Array.isArray(value),'Actual Battle snapshot required');return value;}
function memberSnapshot(fleet){check(Array.isArray(fleet.snapshot),'Actual pre-battle FleetData snapshot required');return fleet.snapshot;}
function impactFlag(state,key,s){const b=state.battle;if(b===null||otherSide(b,s)===null||originalBattlePrimary(b,otherSide(b,s),s)===null)return false;return originalCampaignMemoryBoolean(originalEntityMemoryWithoutUpdate(originalBattlePrimary(b,otherSide(b,s),s).campaign.entity),key,s.memoryServices);}
export const originalEncounterLowRepImpact=(state,services={})=>impactFlag(state,'$lowRepImpact',services);
export const originalEncounterNoRepImpact=(state,services={})=>impactFlag(state,'$noRepImpact',services);
export function didOriginalPlayerWinEncounterOutright(state,services={}){if(originalEncounterSide(state,player(services)).disengaged)return false;const winner=state.sideData.find(d=>!d.disengaged)??null,loser=state.sideData.find(d=>d.disengaged)??null;if((state.lastOutcome===null||winner!==null&&loser!==null)&&originalBattleIsPlayerSide(state.battle,originalBattleSideFor(state.battle,winner?.fleet??null),services))return true;return ['BATTLE_PLAYER_WIN_TOTAL','ESCAPE_ENEMY_LOSS_TOTAL','ESCAPE_ENEMY_SUCCESS','ESCAPE_PLAYER_WIN','ESCAPE_PLAYER_WIN_TOTAL'].includes(state.lastOutcome);}
export function didOriginalPlayerWinLatestEncounterBattle(state,services={}){if(originalEncounterSide(state,player(services)).disengaged)return false;return didOriginalPlayerWinEncounterOutright(state,services)||state.lastOutcome==='BATTLE_PLAYER_WIN';}
export function markOriginalEncounterLowRepImpact(fleet,services={}){const memory=originalEntityMemoryWithoutUpdate(fleet.campaign.entity),key='$lowRepImpact',required=key+'_battleOnLowImpactSide';setOriginalCampaignMemory(memory,key,true);setOriginalCampaignMemory(memory,required,true,-1);addOriginalCampaignMemoryRequired(memory,key,required);return originalCampaignMemoryContains(memory,key,services.memoryServices);}
function friendlyDamage(state,which){const rows=state.playerFPHullDamageToAlliesByFaction.filter(row=>row.faction===which);check(rows.length<=1,'Actual unique faction-keyed friendly-fire map required');return rows.length?num(rows[0].damage):null;}
const threshold=action=>action==='COMBAT_HELP_MAJOR'?5:action==='COMBAT_HELP_CRITICAL'?10:2;
export function adjustOriginalEncounterPlayerReputation(state,dialog,ffText=null,okToAdjustAlly=true,okToAdjustEnemy=true,services={}){
 bool(okToAdjustAlly);bool(okToAdjustEnemy);check(ffText===null||typeof ffText==='string','Actual optional friendly-fire text required');if(state.alreadyAdjustedRep)return false;const b=state.battle;if(b===null||!originalBattleIsInvolved(b,player(services))||!state.engagedInHostilities)return false;
 state.alreadyAdjustedRep=true;let printed=false;const playerWon=didOriginalPlayerWinLatestEncounterBattle(state,services),playerSide=originalBattlePlayerSide(b,services),enemySide=otherSide(b,services),pf=player(services);setOriginalConstructedFleetDestination(pf,...pf.campaign.entity.position);
 const aggressive=bool(state.playerDidSeriousDamage)||!bool(state.playerOnlyRetreated);let action=null,knows=false;for(const fleet of enemySide)if(originalBattleFleetKnowsPlayer(fleet,services)){knows=true;break;}if(!knows)for(const fleet of snapshot(b,enemySide))if(originalBattleFleetKnowsPlayer(fleet,services)){knows=true;break;}
 const lowImpact=originalEncounterLowRepImpact(state,services);if(lowImpact)for(const fleet of snapshot(b,enemySide))markOriginalEncounterLowRepImpact(fleet,services);
 if(state.playerPursued&&playerWon)action=knows&&!lowImpact?'COMBAT_AGGRESSIVE':'COMBAT_AGGRESSIVE_TOFF';else if(aggressive)action=knows&&!lowImpact?'COMBAT_NORMAL':'COMBAT_NORMAL_TOFF';if(originalEncounterNoRepImpact(state,services)||!okToAdjustEnemy)action=null;
 const adjust=(action,param,id)=>{const panel=call(dialog,'getTextPanel');call(services,'adjustEncounterFactionReputation',createOriginalReputationEnvelope(action,param,panel),id);printed=true;},seen=new Set();
 if(action!==null)for(const fleet of snapshot(b,enemySide)){const id=faction(fleet).factionId;if(seen.has(id))continue;seen.add(id);adjust(action,null,id);}
 let playerFP=0,allyFP=0,enemyFP=0;for(const fleet of snapshot(b,playerSide))for(const member of memberSnapshot(fleet)){if(bool(fleet.isPlayerFleet))playerFP=f(playerFP+originalFleetPointCost(member));else allyFP=f(allyFP+originalFleetPointCost(member));}for(const fleet of snapshot(b,enemySide))for(const member of memberSnapshot(fleet))enemyFP=f(enemyFP+originalFleetPointCost(member));void playerFP;
 action=allyFP>enemyFP||!playerWon?'COMBAT_HELP_MINOR':allyFP<f(enemyFP*f(.5))?'COMBAT_HELP_CRITICAL':'COMBAT_HELP_MAJOR';const contribution=originalEncounterPlayerContribution(state,services);if(contribution<=0)action=null;else if(contribution<f(.1))action='COMBAT_HELP_MINOR';
 if(action!==null){const total=f(num(state.allyFPHullDamageToEnemies)+num(state.playerFPHullDamageToEnemies));if(total<10)action='COMBAT_HELP_MINOR';else if(total<20&&action==='COMBAT_HELP_CRITICAL')action='COMBAT_HELP_MAJOR';}if(bool(b.playerInvolvedAtStart)&&action!==null)action=null;if(!okToAdjustAlly)action=null;
 seen.clear();for(const ally of snapshot(b,playerSide)){if(bool(ally.isPlayerFleet))continue;const fact=faction(ally),id=fact.factionId;if(seen.has(id))continue;seen.add(id);const damage=friendlyDamage(state,fact);if(damage!==null&&damage>threshold(action)||action===null||!playerSide.includes(ally))continue;adjust(action,null,id);}
 if(okToAdjustAlly){let first=true;seen.clear();for(const ally of snapshot(b,playerSide)){if(bool(ally.isPlayerFleet))continue;const fact=faction(ally),id=fact.factionId;if(id==='player'||seen.has(id))continue;seen.add(id);const damage=friendlyDamage(state,fact);if(damage!==null&&damage>threshold(action)){if(first&&ffText!==null){first=false;call(call(dialog,'getTextPanel'),'addParagraph',ffText);}adjust('COMBAT_FRIENDLY_FIRE',f(damage-threshold(action)),id);continue;}if(action!==null)playerSide.includes(ally);}}
 return printed;
}
