/** HullModItemManager: native required-item bookkeeping, without a fake refit UI or global player switch. */
import R from '../data/reference-battle-autoresolver.json' with {type:'json'};
import ITEMS from '../data/reference-required-items.json' with {type:'json'};
import {createOriginalSpecialCargoStack} from './OriginalSpecialItems.mjs';
import {requireThat} from '../core/Values.mjs';
import {originalCampaignMemoryGet,setOriginalCampaignMemory} from './OriginalCampaignMemory.mjs';
import {originalAutofitSpecs} from './OriginalAutofitSpecRegistry.mjs';
import {sameOriginalNativeCargoItem,originalNativeCargoItemQuantity,addOriginalNativeCargoItems,removeOriginalNativeCargoItems,sortOriginalNativeCargo} from './OriginalNativeCargo.mjs';
const f=Math.fround,check=(ok,message)=>requireThat(ok,'UNSUPPORTED_NATIVE_HULLMOD_ITEMS',message);
const call=(s,key,...args)=>{check(typeof s[key]==='function','Actual hullmod item service required: '+key);const result=s[key](...args);check(!result||typeof result.then!=='function','Hullmod item services must be synchronous');return result;};
const round=value=>Math.max(-2147483648,Math.min(2147483647,Math.floor(f(value)+.5)));
export function originalHullmodRequiredItem(id,services={}){if(services.readHullmodRequiredItem)return call(services,'readHullmodRequiredItem',id);const spec=R.hullmods[id];check(spec,'Actual registered hullmod required: '+id);if(spec.requiredItem==='default-null')return null;const item=ITEMS.requiredItems[id];check(item?.type==='SPECIAL'&&spec.requiredItem==='custom','Actual custom required-item implementation required: '+id);return createOriginalSpecialCargoStack(null,item.itemId,item.itemData);}
export function validateOriginalHullmodItemManager(state){check(state?.scope==='native-hullmod-item-manager'&&Array.isArray(state.map),'Actual HullModItemManager history required');const ids=new Set();for(const row of state.map){check(typeof row.memberId==='string'&&!ids.has(row.memberId)&&Array.isArray(row.installed),'Actual unique member installation lists required');ids.add(row.memberId);for(const item of row.installed)check(typeof item.modId==='string'&&item.item&&typeof item.item.type==='string','Actual retained installation item required');}return state;}
export function originalHullmodItemManagerInstance(memory,services){let manager=originalCampaignMemoryGet(memory,'$hullModItemManager',services.memoryServices);if(manager!==null)return validateOriginalHullmodItemManager(manager);const listeners=call(services,'readRefitScreenListeners');check(Array.isArray(listeners?.saved)&&Array.isArray(listeners.transient),'Actual RefitScreenListener repositories required');const objectRef=call(services,'createHullmodItemManagerRef');check(typeof objectRef==='string'&&objectRef.length>0,'Actual manager identity required');manager={scope:'native-hullmod-item-manager',objectRef,kind:'hullmod-item-manager',map:[]};listeners.saved.push(manager);setOriginalCampaignMemory(memory,'$hullModItemManager',manager);return manager;}
export function bindOriginalHullmodItemManager(state,services={}){
 validateOriginalHullmodItemManager(state);const req=id=>originalHullmodRequiredItem(id,services);
 function list(member){check(typeof member?.id==='string','Actual FleetMember ID required');let row=state.map.find(row=>row.memberId===member.id);if(!row){row={memberId:member.id,installed:[]};state.map.push(row);}return row.installed;}
 const cleanup=()=>{for(let i=state.map.length-1;i>=0;i--)if(state.map[i].installed.length===0)state.map.splice(i,1);};
 const player=()=>{const cargo=call(services,'readHullmodPlayerCargo');check(cargo===null||cargo&&Array.isArray(cargo.slots),'Actual nullable player cargo required');return cargo;};
 const storage=market=>{const cargo=call(services,'readHullmodStorageCargo',market);check(cargo===null||cargo&&Array.isArray(cargo.slots),'Actual nullable storage cargo required');return cargo;};
 const builtIn=(member,id)=>services.isHullmodBuiltIntoMember?call(services,'isHullmodBuiltIntoMember',member,id):originalAutofitSpecs.readHull(member.variant).builtInMods.includes(id);
 function diff(member,variant){const installed=list(member).map(data=>data.modId),result={needItems:[],noLongerNeedItems:[]};check(Array.isArray(variant?.effects?.hullMods),'Actual ordered current hullmods required');for(const id of variant.effects.hullMods){if(builtIn(member,id)||req(id)===null)continue;const at=installed.indexOf(id);if(at<0)result.needItems.push(id);else installed.splice(at,1);}result.noLongerNeedItems.push(...installed);return result;}
 function unconfirmed(item,member,variant){if(member===null||variant===null)return 0;const delta=diff(member,variant);let count=0;const hasData=item.type==='RESOURCES'?item.commodityId!=null:item.itemId!=null;for(const [ids,sign]of [[delta.needItems,1],[delta.noLongerNeedItems,-1]])for(const id of ids){const other=req(id);if(other!==null&&hasData&&sameOriginalNativeCargoItem(item,other))count=(count+sign)|0;}return count;}
 function available(item,market){const cargo=player();if(cargo===null)return 0;let quantity=f(round(originalNativeCargoItemQuantity(cargo,item)));if(market!==null){const store=storage(market);if(store!==null)quantity=f(quantity+round(originalNativeCargoItemQuantity(store,item)));}return round(quantity);}
 function possible(id,member,variant,market){const mode=call(services,'readHullmodGameState');check(typeof mode==='string','Actual GameState required');if(mode==='TITLE')return true;if(member===null||variant===null)return true;const item=req(id);if(item===null)return true;if(player()===null)return true;if(list(member).some(data=>data.modId===id))return true;const used=unconfirmed(item,member,variant);return ((available(item,market)-used)|0)>=1;}
 function take(id,member,market){const item=req(id);if(item===null)return;const installed=list(member);if(installed.some(data=>data.modId===id))return;let cargo=player();if(cargo===null)return;let removed=false;if(originalNativeCargoItemQuantity(cargo,item)>=1){removeOriginalNativeCargoItems(cargo,item,1,services.cargoServices);removed=true;}if(!removed&&market!==null){cargo=storage(market);if(cargo!==null&&originalNativeCargoItemQuantity(cargo,item)>=1){removeOriginalNativeCargoItems(cargo,item,1,services.cargoServices);removed=true;}}if(removed)installed.push({modId:id,item});}
 function giveBack(id,member,cargo){if(req(id)===null)return;if(cargo===null)cargo=player();if(cargo===null)return;const installed=list(member),index=installed.findIndex(data=>data.modId===id);if(index>=0){const data=installed.splice(index,1)[0];if(!installed.length){const at=state.map.findIndex(row=>row.memberId===member.id);state.map.splice(at,1);}addOriginalNativeCargoItems(cargo,data.item,1,services.cargoServices);}}
 return {
  isRequiredItemAvailable:possible,getHullmodDiff:diff,getNumUnconfirmed:unconfirmed,getNumAvailable:available,
  getNumAvailableMinusUnconfirmed:(item,member,variant,market)=>{const used=unconfirmed(item,member,variant);return (available(item,market)-used)|0;},
  takeRequiredItems:take,giveBackRequiredItems:giveBack,
  giveBackAllItems:(member,cargo=null)=>{for(const id of list(member).map(data=>data.modId))giveBack(id,member,cargo);cleanup();},
  reportFleetMemberVariantSaved:(member,market)=>{const delta=diff(member,member.variant);for(const id of delta.needItems)take(id,member,market);for(const id of delta.noLongerNeedItems)giveBack(id,member,null);cleanup();},
  getItemsInUseBy:member=>{const cargo=call(services,'createHullmodItemsCargo');for(const data of list(member))addOriginalNativeCargoItems(cargo,data.item,1,services.cargoServices);sortOriginalNativeCargo(cargo,services.cargoServices);return cargo;},
 };
}
