/** BaseEventPlugin's actual lifecycle only; never used as a substitute for its task subclasses. */
import {requireThat} from '../core/Values.mjs';
import {validateOriginalCampaignEventTarget} from './OriginalCampaignEventKeys.mjs';
const check=(ok,message)=>requireThat(ok,'UNSUPPORTED_NATIVE_BASE_EVENT',message);
const call=(services,name,...args)=>{check(typeof services[name]==='function','Actual base-event service required: '+name);const value=services[name](...args);check(!value||typeof value.then!=='function','Base-event services must be synchronous');return value;};
export function createOriginalBaseCampaignEvent(objectRef,id){check(typeof objectRef==='string'&&objectRef.length>0&&typeof id==='string'&&id.length>0,'Actual BaseEventPlugin UID required');return {scope:'native-base-campaign-event',kind:'base-campaign-event',objectRef,id,eventType:null,eventTarget:null,market:null,entity:null,faction:null,statModId:null,started:false,memory:null,startProbability:0};}
export function validateOriginalBaseCampaignEvent(event){check(event?.scope==='native-base-campaign-event'&&event.kind==='base-campaign-event'&&typeof event.objectRef==='string'&&typeof event.id==='string'&&typeof event.started==='boolean'&&typeof event.startProbability==='number'&&Number.isFinite(event.startProbability)&&Math.fround(event.startProbability)===event.startProbability,'Actual BaseEventPlugin state required; subclass behavior must be supplied');if(event.eventTarget!==null)validateOriginalCampaignEventTarget(event.eventTarget);check(event.eventType===null||typeof event.eventType==='string','Actual event type required');return event;}
export function setOriginalBaseCampaignEventTarget(event,target,services){validateOriginalCampaignEventTarget(target);event.eventTarget=target;if(target.entity!==null){event.market=call(services,'readBaseEventEntityMarket',target.entity);event.faction=call(services,'readBaseEventEntityFaction',target.entity);event.entity=target.entity;}}
export function initializeOriginalBaseCampaignEvent(event,type,target,services,addListener=true){check(typeof type==='string'&&typeof addListener==='boolean','Actual base event initialization required');event.eventType=type;event.eventTarget=target;setOriginalBaseCampaignEventTarget(event,target,services);const id=call(services,'nextBaseEventUID');check(typeof id==='string'&&id.length>0,'Actual stat modifier UID required');event.statModId=type+'_'+(event.market===null?'':call(services,'readBaseEventMarketId',event.market)+'_')+id;if(addListener)call(services,'addBaseEventListener',event);}
export function startOriginalBaseCampaignEvent(event,services,addListener=false){check(typeof addListener==='boolean','Actual listener registration flag required');event.started=true;if(addListener)call(services,'addBaseEventListener',event);}
export function cleanupOriginalBaseCampaignEvent(event,services){call(services,'removeBaseEventListener',event);}
