/** PersistentUIData.AbilitySlots, separate from gameplay plugin state. */
import {requireThat} from '../core/Values.mjs';
import {originalFleetAbilityEntries,originalFleetAbility,isOriginalCampaignAbility,validateOriginalCampaignAbility,originalAbilityUsable,originalAbilityCooldownFraction} from './OriginalCampaignAbilities.mjs';
const check=(v,m)=>requireThat(v,'INVALID_NATIVE_ABILITY_BAR',m);
export function createOriginalAbilitySlots(){return {scope:'native-campaign-ability-slots',currBarIndex:0,locked:false,slots:Array.from({length:5},()=>Array.from({length:10},(_,slotId)=>({slotId,abilityId:null,inHyperAbilityId:null})))};}
export function validateOriginalAbilitySlots(state){check(state?.scope==='native-campaign-ability-slots'&&Object.keys(state).every(k=>['scope','currBarIndex','locked','slots'].includes(k))&&typeof state.locked==='boolean'&&Number.isInteger(state.currBarIndex)&&state.currBarIndex>=0&&state.currBarIndex<5,'Actual ability bar state required');check(Array.isArray(state.slots)&&state.slots.length===5,'Five native bars required');const identities=new Set();for(const page of state.slots){check(Array.isArray(page)&&page.length===10,'Ten native slots required');for(const [i,slot]of page.entries()){check(slot&&Object.keys(slot).every(k=>['slotId','abilityId','inHyperAbilityId'].includes(k))&&!identities.has(slot)&&slot.slotId===i,'Distinct ordered native ability slots required');identities.add(slot);for(const key of ['abilityId','inHyperAbilityId'])check(slot[key]===null||typeof slot[key]==='string'&&slot[key].length>0&&slot[key].length<=128,'Actual nullable ability id required');}}return state;}
/** New UI profile only. Does not recover missing historical arrangements. */
export function populateOriginalNewAbilitySlots(state,fleet){validateOriginalAbilitySlots(state);for(const {id}of originalFleetAbilityEntries(fleet)){if(state.slots.some(page=>page.some(s=>s.abilityId===id)))continue;const empty=state.slots.flat().find(s=>s.abilityId===null);if(empty)empty.abilityId=id;}return state;}
export function changeOriginalAbilityBar(state,action){validateOriginalAbilitySlots(state);check(action&&typeof action==='object','Actual ability bar gesture required');if(action.kind==='page'){check(Object.keys(action).every(k=>['kind','direction'].includes(k))&&[-1,1].includes(action.direction),'Actual page direction required');state.currBarIndex=(state.currBarIndex+action.direction+5)%5;}else if(action.kind==='lock'){check(Object.keys(action).every(k=>['kind','locked'].includes(k))&&typeof action.locked==='boolean','Actual lock state required');state.locked=action.locked;}else check(false,'Unsupported ability bar gesture');return state;}
export function originalAbilityForSlot(state,fleet,slotIndex){validateOriginalAbilitySlots(state);check(Number.isInteger(slotIndex)&&slotIndex>=0&&slotIndex<10,'Actual current bar slot required');const slot=state.slots[state.currBarIndex][slotIndex],hyper=fleet.campaign.entity.containingLocation?.hyperspaceMode;return (hyper&&slot.inHyperAbilityId!==null?originalFleetAbility(fleet,slot.inHyperAbilityId):null)??(slot.abilityId===null?null:originalFleetAbility(fleet,slot.abilityId));}
export function projectOriginalAbilityBar(state,fleet,{commandBlockReason=null}={}){
 validateOriginalAbilitySlots(state);const color=fleet.campaign.faction.specBaseUIColor??fleet.campaign.faction.specColor;check(Array.isArray(color)&&color.length===4&&color.every(c=>Number.isFinite(c)&&c>=0&&c<=255),'Actual faction UI color required');
 return {scope:'native-campaign-ability-bar',page:state.currBarIndex,locked:state.locked,color:[...color],commandBlockReason,slots:state.slots[state.currBarIndex].map((slot,i)=>{const a=originalAbilityForSlot(state,fleet,i);let ability=null;if(isOriginalCampaignAbility(a)){validateOriginalCampaignAbility(a,fleet);ability={id:a.id,name:a.spec.name,icon:a.spec.icon,active:a.turnedOn,usable:originalAbilityUsable(a),progress:a.level,showProgress:a.id!=='go_dark'&&a.level>0&&(!a.turnedOn||a.level<1),showActive:a.turnedOn,cooldownFraction:originalAbilityCooldownFraction(a)};}return {index:i,shortcut:String((i+1)%10),assigned:slot.abilityId!==null||slot.inHyperAbilityId!==null,unsupported:a!==null&&!isOriginalCampaignAbility(a),ability};})};
}
