import {isOriginalCampaignPlanet} from './OriginalCampaignPlanet.mjs';
import {validateOriginalCampaignBackgroundSource} from './OriginalCampaignBackground.mjs';
import {isOriginalCargoPods} from './OriginalCargoPods.mjs';
/** BaseLocation entity phases on shared objects. Generic entities, background warps and encounters still require their actual services. */
import {validateOriginalCampaignBattle} from './OriginalCampaignBattle.mjs';
import {advanceOriginalLocationEncounters} from './OriginalLocationEncounters.mjs';
import {requireThat} from '../core/Values.mjs';
import {createOriginalFader,fadeOriginalFader,advanceOriginalFader,originalFaderIsOut,validateOriginalFader} from './OriginalFader.mjs';
import {advanceOriginalViewShifter,validateOriginalViewShifter} from './OriginalFleetViewShifters.mjs';
import {originalEntityMemoryWithoutUpdate,originalCampaignMemoryGet,advanceOriginalCampaignMemory,validateOriginalCampaignMemory} from './OriginalCampaignMemory.mjs';
import {originalWorldLocationObjects,removeOriginalFleetFromLocation,removeOriginalCustomEntityFromLocation,removeOriginalPlanetFromLocation} from './OriginalFleetWorld.mjs';
import {originalLocationEntityState,advanceOriginalLocationOrbit,validateOriginalLocationOrbit} from './OriginalLocationOrbits.mjs';
const f=Math.fround,check=(v,m)=>requireThat(v,'UNSUPPORTED_NATIVE_LOCATION_FRAME',m),ENTITY='com.fs.starfarer.campaign.CampaignEntity',TOKEN='com.fs.starfarer.campaign.BaseLocation$LocationToken';
const call=(s,k,...args)=>{check(typeof s[k]==='function','Actual location frame service required: '+k);const value=s[k](...args);check(!value||typeof value.then!=='function','Location services must be synchronous: '+k);return value;};
const scalar=n=>{check(Number.isFinite(n)&&Number.isFinite(f(n)),'Finite location float required');return f(n);};
const bool=v=>{check(typeof v==='boolean','Actual location Boolean required');return v;};
const rgba=c=>{check(Array.isArray(c)&&c.length===4&&c.every(v=>Number.isInteger(v)&&v>=0&&v<=255),'Actual location light color required');return c;};
const fleet=o=>o?.campaign?.scope==='native-constructed-campaign-fleet';
const objects=(state,type,services)=>{const list=services.readLocationObjects?call(services,'readLocationObjects',state.location,type):originalWorldLocationObjects(state.location,type);check(Array.isArray(list),'Actual ordered location object list required');return list;};
/** New-location advance state only. Background/center are explicit actual inputs, not inferred captures. */
export function createOriginalLocationFrame(world,location,{kind,center,background}){const lightHeight=createOriginalFader(1,10,10,true,true);fadeOriginalFader(lightHeight,'OUT');const state={scope:'native-location-natural-frame',world,location,kind,center,background,lightColor:[255,255,255,255],lightHeight,memory:null,scripts:[],hitParticles:{scope:'native-location-hit-particles',limit:2000,particles:[]},spawnPoints:[],idMapDirty:true,lastPlayerVisitTimestamp:'0'};return validateOriginalLocationFrame(state,world);}
export function validateOriginalLocationFrame(state,world){
 check(state?.scope==='native-location-natural-frame'&&state.world===world&&world.locations.includes(state.location),'Lost actual location-frame/world identity');check(['base','star-system'].includes(state.kind)&&(state.kind==='star-system'?state.center&&typeof state.center==='object':state.center===null),'Actual location subclass/center required');rgba(state.lightColor);validateOriginalFader(state.lightHeight);if(state.memory!==null)validateOriginalCampaignMemory(state.memory);
 check(state.background===null||state.background&&typeof state.background==='object','Actual background or known null required');if(state.background?.scope==='native-location-background-advance'){const bg=state.background;if(Object.hasOwn(bg,'visual')){validateOriginalCampaignBackgroundSource(bg);check(!state.location.hyperspaceMode,'Normal-space background cannot be attached to hyperspace');}check(bg.warpingRenderer===null||bg.warpingRenderer&&typeof bg.warpingRenderer==='object','Actual background warper or known null required');for(const k of ['colorShifter','particleColorShifter'])if(bg[k]!==null)validateOriginalViewShifter(bg[k]);}check(Array.isArray(state.scripts)&&Array.isArray(state.spawnPoints),'Actual location script/spawn lists required');check(state.hitParticles?.scope==='native-location-hit-particles'&&Number.isInteger(state.hitParticles.limit)&&state.hitParticles.limit>=0&&Array.isArray(state.hitParticles.particles)&&state.hitParticles.particles.every(p=>p&&typeof p==='object'),'Actual hit particle state required');check(typeof state.idMapDirty==='boolean'&&typeof state.lastPlayerVisitTimestamp==='string'&&/^-?[0-9]+$/.test(state.lastPlayerVisitTimestamp),'Actual location visit/cache state required');const timestamp=BigInt(state.lastPlayerVisitTimestamp);check(String(timestamp)===state.lastPlayerVisitTimestamp&&BigInt.asIntN(64,timestamp)===timestamp,'Location visit timestamp outside native long range');return state;
}
export function advanceOriginalLocationIndicator(indicator,seconds,services={}){check(indicator,'Actual native indicator required');if(indicator.pendingTypeOrdinal!==null&&originalFaderIsOut(indicator.fader)){if(indicator.renderList!==null)call(services,'invalidateIndicatorList',indicator.renderList);indicator.typeOrdinal=indicator.pendingTypeOrdinal;indicator.color=indicator.pendingColor;indicator.pendingTypeOrdinal=null;fadeOriginalFader(indicator.fader,'IN');}else if(indicator.pendingTypeOrdinal!==null)fadeOriginalFader(indicator.fader,'OUT');advanceOriginalFader(indicator.fader,seconds);advanceOriginalFader(indicator.pulse,seconds);}
function focus(object,services){const orbit=originalLocationEntityState(object,services).orbit;if(orbit===null)return null;check(orbit!==undefined,'Actual nullable entity orbit required');return orbit.scope==='native-current-location-orbit'?orbit.focus:call(services,'readLocationOrbitFocus',object,orbit);}
function planet(object,services){if(isOriginalCampaignPlanet(object))return true;if(object===null||fleet(object)||isOriginalCargoPods(object))return false;return bool(call(services,'isLocationPlanet',object));}
function lighting(state,object,services){
 const entity=originalLocationEntityState(object,services);entity.containingLocation=state.location;if(fleet(object))object.logisticsEnvironment.inHyperspace=state.location.hyperspaceMode;
 const memory=originalEntityMemoryWithoutUpdate(entity),override=originalCampaignMemoryGet(memory,'$lightSourceOverride',services.memoryServices),colorOverride=originalCampaignMemoryGet(memory,'$lightColorOverride',services.memoryServices);let source=null,color=state.lightColor;
 if(override!==null&&colorOverride!==null){check(typeof override==='object','Actual override light source required');source=override;color=rgba(colorOverride);}
 else if(state.kind==='star-system'){source=state.center;const direct=focus(object,services);if(planet(direct,services)){if(isOriginalCampaignPlanet(direct)?direct.graphics.spec.isStar:bool(call(services,'isLocationStar',direct)))source=direct;else{const parent=focus(direct,services);if(planet(parent,services)&&(isOriginalCampaignPlanet(parent)?parent.graphics.spec.isStar:bool(call(services,'isLocationStar',parent))))source=parent;}}if(planet(source,services)){const lightOverride=isOriginalCampaignPlanet(source)?source.lightColorOverrideIfStar:call(services,'readStarLightColorOverride',source);if(lightOverride!==null)color=rgba(lightOverride);}}
 if(fleet(object)){entity.lightSource=source;entity.lightColor=color;object.campaign.view.lightSource=source;object.campaign.view.lightColor=color;}else if(isOriginalCargoPods(object)||isOriginalCampaignPlanet(object)){entity.lightSource=source;entity.lightColor=color;}else call(services,'setLocationEntityLight',object,source,color);
}
function scriptDone(script,services){if(script.scope==='native-current-campaign-battle'){validateOriginalCampaignBattle(script);return script.done;}return bool(call(services,'isLocationScriptDone',script));}
function scriptWhilePaused(script,services){return script.scope==='native-current-campaign-battle'?false:bool(call(services,'locationScriptRunsWhilePaused',script));}
function scripts(state,seconds,context,services){for(const script of [...state.scripts]){if(script===null)continue;const remove=()=>{const index=state.scripts.indexOf(script);if(index>=0)state.scripts.splice(index,1);};if(scriptDone(script,services)){remove();continue;}if(!scriptWhilePaused(script,services)&&bool(context.paused))continue;call(services,'advanceLocationScript',script,seconds,context);if(scriptDone(script,services))remove();}}
/** executeAdds/executeRemoves are verified EMPTY in 0.98a-RC8: no artificial queues. */
export function advanceOriginalLocationEvenIfPaused(state,seconds,context,services={}){seconds=scalar(seconds);const entities=[...objects(state,ENTITY,services)];for(const object of entities){if(object===null)continue;const indicator=originalLocationEntityState(object,services).indicator;if(fleet(object)||isOriginalCargoPods(object)||isOriginalCampaignPlanet(object))advanceOriginalLocationIndicator(indicator,seconds,services);else call(services,'advanceLocationEntityIndicator',object,seconds);}
 for(const object of entities){if(object===null)continue;lighting(state,object,services);call(services,fleet(object)?'advanceLocationFleetEvenIfPaused':'advanceLocationEntityEvenIfPaused',object,seconds,context);}scripts(state,seconds,context,services);return {scope:'native-location-even-if-paused',entities:entities.length,readyForAuthority:false};}
function background(state,seconds,services){const bg=state.background;if(bg===null)return;if(bg.scope!=='native-location-background-advance')return call(services,'advanceLocationBackground',bg,seconds);if(bg.warpingRenderer!==null)call(services,'advanceLocationBackgroundWarp',bg.warpingRenderer,seconds);for(const k of ['colorShifter','particleColorShifter'])if(bg[k]!==null){validateOriginalViewShifter(bg[k]);advanceOriginalViewShifter(bg[k],seconds);}}
function particles(state,seconds,services){const list=state.hitParticles.particles,expired=[];for(const particle of list){call(services,'advanceLocationParticle',particle,seconds);if(bool(call(services,'isLocationParticleExpired',particle)))expired.push(particle);}for(let i=list.length-1;i>=0;i--)if(expired.includes(list[i]))list.splice(i,1);}
function integrate(object,seconds,days,services){const entity=originalLocationEntityState(object,services);check(Object.hasOwn(entity,'orbit'),'Actual nullable orbit required');if(entity.orbit!==null){if(entity.orbit.scope==='native-current-location-orbit'){validateOriginalLocationOrbit(entity.orbit);check(entity.orbit.entity===object,'Lost orbit/entity identity');}advanceOriginalLocationOrbit(entity.orbit,seconds,days,services);}const velocity=entity.velocity??call(services,'readLocationEntityVelocity',object);check(Array.isArray(velocity)&&velocity.length===2,'Actual velocity vector required');for(let i=0;i<2;i++)entity.position[i]=scalar(f(entity.position[i]+f(scalar(velocity[i])*seconds)));}
export function advanceOriginalLocationFrame(state,seconds,context,services={}){
 seconds=scalar(seconds);let advanced=0,removed=0,tokens=0,encounters=null;const effects=[];if(!bool(context.paused)){
  const days=scalar(call(services,'convertLocationSecondsToDays',seconds));if(state.memory!==null)advanceOriginalCampaignMemory(state.memory,days,{paused:context.paused},services.memoryServices);state.idMapDirty=true;advanceOriginalFader(state.lightHeight,days);if(state.background!==null&&state.location===context.currentLocation)background(state,seconds,services);particles(state,seconds,services);
  for(const object of [...objects(state,ENTITY,services)]){const entity=originalLocationEntityState(object,services);if(bool(entity.expired)){if(fleet(object))removeOriginalFleetFromLocation(state.world,state.location,object,services);else if(isOriginalCargoPods(object))removeOriginalCustomEntityFromLocation(state.world,state.location,object,services);else if(isOriginalCampaignPlanet(object))removeOriginalPlanetFromLocation(state.world,state.location,object,services);else call(services,'removeLocationEntity',state.location,object);removed++;continue;}entity.containingLocation=state.location;lighting(state,object,services);const result=call(services,fleet(object)?'advanceLocationFleet':'advanceLocationEntity',object,seconds,context);if(result?.effects!==undefined){check(Array.isArray(result.effects),'Ordered entity frame effects required');for(const effect of result.effects)effects.push({entity:object,effect});}integrate(object,seconds,days,services);if(entity.indicator!==null){if(fleet(object)||isOriginalCargoPods(object)||isOriginalCampaignPlanet(object))advanceOriginalLocationIndicator(entity.indicator,seconds,services);else call(services,'advanceLocationEntityIndicator',object,seconds);}advanced++;}
  for(const token of [...objects(state,TOKEN,services)]){integrate(token,seconds,days,services);tokens++;}
  if(seconds<=0)return {scope:'native-location-natural-frame-result',advanced,removed,tokens,encounters,effects,zeroTimeReturn:true,readyForAuthority:false};
  encounters=services.advanceLocationEncounters?call(services,'advanceLocationEncounters',state,context):advanceOriginalLocationEncounters(state,context,services);for(const point of state.spawnPoints)call(services,'advanceLocationSpawnPoint',point,state.location);
 }
 if(state.location===context.currentLocation){const timestamp=call(services,'readLocationClockTimestamp');check((typeof timestamp==='string'&&/^-?[0-9]+$/.test(timestamp))||Number.isSafeInteger(timestamp),'Actual native visit timestamp required');state.lastPlayerVisitTimestamp=String(timestamp);}
 return {scope:'native-location-natural-frame-result',advanced,removed,tokens,encounters,effects,zeroTimeReturn:false,readyForAuthority:false};
}
