import type {OriginalNativeMemberStatus,OriginalNativeRepairTracker} from './OriginalNativeRepair.mjs';
import type {OriginalNativeFleetCounts} from './OriginalNativeFleetCounts.mjs';
import type {OriginalNativeInflater,OriginalNativeBattleStrength,OriginalNativeStrengthServices} from './OriginalNativeStrength.mjs';
import type {OriginalFleetStats} from './OriginalNativeFleetStats.mjs';
import type {OriginalMemberBuffManager} from './OriginalMemberBuffs.mjs';
import type { DeepReadonly } from '../Types.js';
import type { EconomyBonus,EconomyMutable } from './OriginalMarketEconomy.mjs';
import type { OriginalStoredMember } from './OriginalStorage.mjs';
import type { OriginalPlayerEconomyState,OriginalPlayerCargo,OriginalPayrollPerson } from './OriginalPlayerEconomy.mjs';
export interface OriginalFleetMemberStats {nativeMemberStatsVersion?:1;fleetMemberRef?:string;variantRef?:string;dynamicStats?:Record<string,EconomyMutable>;lifecycle:'base-only'|'rebuilding'|'current';suppliesToRecover:EconomyMutable;suppliesPerMonth:EconomyMutable;maxBurn:EconomyMutable;fighterBays:EconomyMutable;cargoMod:EconomyBonus;fuelMod:EconomyBonus;minCrewMod:EconomyBonus;maxCrewMod:EconomyBonus;fuelUseMod:EconomyBonus;dynamic:Record<string,EconomyBonus>}
export interface OriginalNativeFleetMember extends OriginalStoredMember {shipName?:string|null;isFlagship?:boolean;isAlly?:boolean;id?:string|null;buffManager?:OriginalMemberBuffManager|null;fleetDataRef:string|null;captainRef?:string|null;fleetCommanderForStatsRef?:string|null;stats:OriginalFleetMemberStats|null;statUpdateNeeded?:boolean;cachedStrength?:number;forceNoMoreStatsUpdates?:boolean;status?:(Omit<OriginalNativeMemberStatus,'modules'>&Partial<Pick<OriginalNativeMemberStatus,'modules'>>)|null;repairTracker:(Pick<OriginalNativeRepairTracker,'objectRef'|'mothballed'|'cr'>&Partial<Omit<OriginalNativeRepairTracker,'objectRef'|'mothballed'|'cr'>>)|null;crewComposition:{objectRef:string;crew:number;marines?:number}|null;buffManagerRef:string|null}
export interface OriginalNativeFleetFields {defaultCommanderRef?:string|null;nullMember?:OriginalNativeFleetMember;factionId?:string;counts?:OriginalNativeFleetCounts;despawning?:boolean;forceNoSensorProfileUpdate?:boolean|null;sensorProfile?:number|null;sensorStrength?:number|null;inflater?:OriginalNativeInflater|null;inflated?:boolean;battle?:OriginalNativeBattleStrength|import('./OriginalCampaignBattle.mjs').OriginalCampaignBattle|null;isPlayerFleet?:boolean;logisticsEnvironment?:{velocity:[number,number];secondsPerDay:number;inHyperspace:boolean}|null;stats?:OriginalFleetStats|null;transponderOn?:boolean;statPeople?:OriginalPayrollPerson[];playerPersonRef?:string;nativeSyncScope:'native-fleet-data-sync-inputs';syncUnresolved:string[];attachedToCampaignFleet:boolean;aiMode:boolean|null;members:OriginalNativeFleetMember[];commanderRef:string|null;fleetStatsRef:string|null;logisticsRef:string|null;membersWithoutNull:OriginalNativeFleetMember[]|null;sortedMembersWithoutNull:OriginalNativeFleetMember[]|null;sortedMembersWithoutNullWithFighters:OriginalNativeFleetMember[]|null;cacheClearedOnSync:Record<string,unknown>;crewSerial:number;fleetwideMaxBurnMod:EconomyBonus|null;commanderTravelSpeedBonus:EconomyBonus|null;minCrew:number|null;fuelPerLightYear:number|null;travelSpeed:number|null;fleetPointsUsed:number|null;effectiveStrength:number|null}
export type OriginalNativeFleet=NonNullable<OriginalPlayerEconomyState['fleet']>&OriginalNativeFleetFields;
export interface OriginalFleetLifecycleServices extends OriginalNativeStrengthServices {readTowCableState?():import('./OriginalTowCable.mjs').OriginalTowCablePersistentEntry|null;towCableState?:import('./OriginalTowCable.mjs').OriginalTowCablePersistentEntry|null;memberHullmodPlugins?:import('./OriginalFleetEffects.mjs').OriginalMemberCampaignHullmodPlugins;memberBuffPlugins?:import('./OriginalMemberBuffs.mjs').OriginalMemberBuffPlugins;fleetStatsAvailable?(fleet:OriginalNativeFleet):boolean;setCommanderStatsFleet?(commanderRef:string,fleet:OriginalNativeFleet):void;updateMemberStats?(member:OriginalNativeFleetMember,fleet:OriginalNativeFleet):void;applyCommanderFleetwideStats?(member:OriginalNativeFleetMember,fleet:OriginalNativeFleet):void;isPlayerCommanderForStats?(member:OriginalNativeFleetMember):boolean;playerCargoWithoutSync?():OriginalPlayerCargo;reportAllHullmodFleetSync?(fleet:OriginalNativeFleet):void;readMemberStrength?(member:OriginalNativeFleetMember,withHull:true,withQuality:true,withCaptain:true):number;advanceFleetLogistics?(fleet:OriginalNativeFleet,amount:0):void;advanceMemberBuffs?(member:OriginalNativeFleetMember,amount:number):void;advanceMemberHullmods?(member:OriginalNativeFleetMember,amount:number):void;updateMemberCrewAndCRStats?(member:OriginalNativeFleetMember):void;applyMemberBuffs?(member:OriginalNativeFleetMember):void;updateMemberRepairRates?(member:OriginalNativeFleetMember):void;updateFleetCounts?(fleet:OriginalNativeFleet):void;updateFleetSizeCount?(fleet:OriginalNativeFleet):void;readFleetwideTotalMod?(fleet:OriginalNativeFleet,key:'fleet_burn_bonus',base:0):number}
export const ORIGINAL_FLEET_SYNC:DeepReadonly<{schemaVersion:1;originalReference:string;scope:string;sources:Record<string,{sha256:string}>;settings:Record<string,number>;hullmodScripts:Record<string,string|null>;hullmodSpecs:Record<string,{tags:string[];costs:Record<string,number>}>;weaponOP:Record<string,{opCost:number;type:string;size:string;beam:boolean;pd:boolean}>;hullmodLifecycle:Record<string,{script:string|null;memberAdvance:string|null;withOnFleetSync:boolean;affectsOPCosts:boolean}>;fleetSyncHooks:{id:string;script:string}[];skills:Record<string,{index:number;type:string;script:string|null;governingSkill:string;requiredLevel:number}[]>;effectConstants:Record<string,{constants:Record<string,number>;hullSizeMap:Record<string,number>;combatHullSizeMap:Record<string,number>}>;memberStatDefaults:Record<string,{kind:'bonus'}|{kind:'mutable';base:number}>;memberStatAliases:Record<string,string>;hulls:Record<string,{hullSize:string;hints:string[];ordnancePoints:number;fleetPoints:number;fighterBays:number;cargo:number;fuel:number;fuelUse:number;minCrew:number;maxCrew:number;maxBurn:number;suppliesToRecover:number;suppliesPerMonth:number;crToDeploy:number;memberStats:Record<string,number>}>;wings:Record<string,{baseValue:number;variantId:string;numFighters:number;fleetPoints:number;opCost:number;role:string|null}>;weaponSpace:Record<string,number>;specialSpace:Record<string,number>;unsupportedHulls:{id:string;reason:string}[]}>;
export function newOriginalFleetMemberStats(member:OriginalStoredMember):OriginalFleetMemberStats;
export function applyOriginalMemberMothballStats(member:OriginalNativeFleetMember):void;
export function originalFleetPointCost(member:OriginalStoredMember):number;
export function originalMemberDeploymentPoints(member:OriginalNativeFleetMember):number;
export function originalMemberLogistics(member:OriginalNativeFleetMember):{cargo:number;fuel:number;minCrew:number;maxCrew:number;fuelUse:number;maxBurn:number};
export function originalCargoStackSpace(stack:OriginalPlayerCargo['slots'][number]):number;
export function updateOriginalFleetCargoSpace(cargo:OriginalPlayerCargo):number;
export function syncOriginalMemberLists(fleet:OriginalNativeFleet):void;
export function recrewOriginalFleet(fleet:OriginalNativeFleet,services?:OriginalFleetLifecycleServices):void;
export function updateOriginalFleetCapacities(fleet:OriginalNativeFleet):void;
export function originalFleetMinBurnLevel(fleet:OriginalNativeFleet):number;
export function originalFleetBurnLevel(fleet:OriginalNativeFleet):number;
export function updateOriginalFleetTravelSpeed(fleet:OriginalNativeFleet):number;
export function synchronizeOriginalFleet(fleet:OriginalNativeFleet,services?:OriginalFleetLifecycleServices):ReturnType<typeof synchronizeOriginalPlayerFleet>;
export function synchronizeOriginalPlayerFleet(player:OriginalPlayerEconomyState,services:OriginalFleetLifecycleServices):{phase:'fleet-stats-unavailable'|'not-needed'|'load-order-wait'|'member-lists-only'|'synchronized'};
export function originalPlayerDeploymentPoints(player:OriginalPlayerEconomyState,dependencies?:{nativeFleetServices?:OriginalFleetLifecycleServices}):number[];

export function validateOriginalNativeFleet(fleet:OriginalNativeFleet):void;
export function restoreOriginalNativeFleet(fleet:OriginalNativeFleet):OriginalNativeFleet;
