/** Java HashSet<String> bucket order for the non-treeified native collections used by campaign knowledge. */
import {requireThat} from '../core/Values.mjs';
const check=(ok,message)=>requireThat(ok,'UNSUPPORTED_NATIVE_STRING_SET',message);
const hash=s=>{let h=0;for(let i=0;i<s.length;i++)h=(Math.imul(h,31)+s.charCodeAt(i))|0;return (h^(h>>>16))>>>0;};
const id=s=>check(typeof s==='string'&&s.length>0&&s.length<=1024,'Actual non-null string-set ID required');
const order=s=>s.entries.sort((a,b)=>(hash(a)&(s.capacity-1))-(hash(b)&(s.capacity-1)));
export function validateOriginalJavaStringSet(s){check(s?.scope==='native-java-string-set'&&Number.isInteger(s.capacity)&&s.capacity>=16&&s.capacity<=1048576&&(s.capacity&(s.capacity-1))===0&&Array.isArray(s.entries),'Actual string HashSet state/capacity required');check(s.entries.length<=65536&&new Set(s.entries).size===s.entries.length,'Unique bounded string-set entries required');let previous=-1;for(const value of s.entries){id(value);const bucket=hash(value)&(s.capacity-1);check(bucket>=previous,'Actual Java HashSet bucket order required');previous=bucket;}return s;}
export function addOriginalJavaStringSet(s,value){validateOriginalJavaStringSet(s);id(value);if(s.entries.includes(value))return false;check(s.entries.length<65536,'String-set work bound');const bucket=hash(value)&(s.capacity-1),count=s.entries.filter(v=>(hash(v)&(s.capacity-1))===bucket).length;check(count<8||s.capacity<64,'Treeified String HashSet requires native tree-order service');s.entries.push(value);if(count>=8)s.capacity*=2;if(s.entries.length>s.capacity*.75)s.capacity*=2;order(s);return true;}
export function removeOriginalJavaStringSet(s,value){validateOriginalJavaStringSet(s);id(value);const index=s.entries.indexOf(value);if(index<0)return false;s.entries.splice(index,1);return true;}
export function createOriginalJavaStringSet(entries=[],collection=false){check(Array.isArray(entries)&&typeof collection==='boolean','Actual HashSet constructor inputs required');let capacity=16;if(collection){const requested=Math.max(Math.trunc(Math.fround(entries.length/Math.fround(.75)))+1,16);while(capacity<requested)capacity*=2;}const s={scope:'native-java-string-set',capacity,entries:[]};for(const value of entries)addOriginalJavaStringSet(s,value);return s;}
