/** Actual BaseIntelPlugin fields/lifecycle and posting visibility; not subclass missions or UI. */
import {requireThat} from '../core/Values.mjs';
import {originalIntelDistance,originalIntelSettings} from './OriginalIntelCommunications.mjs';
const f=Math.fround,check=(ok,message)=>requireThat(ok,'UNSUPPORTED_NATIVE_BASE_INTEL',message);
const scalar=value=>{check(typeof value==='number'&&Number.isFinite(value)&&Number.isFinite(f(value)),'Native finite intel float required');return f(value);};
const call=(services,name,...args)=>{check(typeof services[name]==='function','Actual base-intel service required: '+name);const value=services[name](...args);check(!value||typeof value.then!=='function','Base-intel services must be synchronous');return value;};
export function createOriginalBaseIntel(objectRef){check(typeof objectRef==='string'&&objectRef.length>0,'Actual new intel identity required');return {scope:'native-base-intel-plugin',objectRef,classId:'base',important:null,timestamp:null,neverClicked:true,listInfoParam:null,ended:null,ending:null,endingTimeRemaining:null,postingLocation:null,postingRangeLY:null,tagsForSort:null,hidden:null,forceAdd:null};}
export function createOriginalNewMessagesIntel(objectRef,num){check(Number.isInteger(num)&&num>0&&num<=2147483647,'Actual new-message count required');return {...createOriginalBaseIntel(objectRef),classId:'new-messages',num};}
/** Field validation is shared by explicitly ported subclasses, never a subclass dispatcher. */
export function validateOriginalBaseIntelFields(item){check(item?.scope==='native-base-intel-plugin'&&typeof item.objectRef==='string'&&item.objectRef.length>0,'Actual BaseIntelPlugin fields required');for(const k of ['important','neverClicked','ended','ending','hidden','forceAdd'])check(item[k]===null||typeof item[k]==='boolean','Actual nullable intel flag required');if(item.timestamp!==null){check(typeof item.timestamp==='string'&&/^-?(0|[1-9][0-9]*)$/.test(item.timestamp)&&String(BigInt.asIntN(64,BigInt(item.timestamp)))===item.timestamp,'Actual signed-long intel timestamp required');}for(const k of ['endingTimeRemaining','postingRangeLY'])if(item[k]!==null)check(scalar(item[k])===item[k],'Native float intel timer/range required');check(item.postingLocation===null||typeof item.postingLocation==='object','Actual intel posting entity required');check(item.tagsForSort===null||Array.isArray(item.tagsForSort)&&item.tagsForSort.every(t=>typeof t==='string'),'Actual intel sort tags required');return item;}
export function validateOriginalBaseIntel(item){check(item?.scope==='native-base-intel-plugin'&&typeof item.objectRef==='string'&&['base','new-messages'].includes(item.classId),'Actual BaseIntelPlugin or NewMessagesIntel required; subclass methods must be provided');validateOriginalBaseIntelFields(item);if(item.classId==='new-messages')check(Number.isInteger(item.num)&&item.num>0&&item.num<=2147483647,'Actual new-message count required');return item;}
export const originalIntelEnded=item=>item.ended===true,originalIntelEnding=item=>item.ending===true;
export const originalIntelShouldRemove=item=>item.timestamp===null&&originalIntelEnding(item)||originalIntelEnded(item);
export function originalIntelHidden(item,tutorial){check(typeof tutorial==='boolean','Actual tutorial state required');return tutorial||item.hidden!==null;}
export function setOriginalIntelForceAdd(item,value){check(typeof value==='boolean','Actual force-add flag required');item.forceAdd=value?true:null;}
export function endOriginalBaseIntel(item,days=3,services={}){item.endingTimeRemaining=scalar(days);const was=originalIntelEnding(item);item.ending=true;if(!was&&services.notifyIntelEnding)call(services,'notifyIntelEnding',item);if(item.endingTimeRemaining<=0){item.ended=true;if(services.notifyIntelEnded)call(services,'notifyIntelEnded',item);}}
export function advanceOriginalBaseIntel(item,seconds,services){if(originalIntelEnded(item))return;const days=scalar(call(services,'convertIntelSecondsToDays',scalar(seconds)));if(originalIntelEnding(item)){check(item.endingTimeRemaining!==null,'Actual ending timer required');item.endingTimeRemaining=f(item.endingTimeRemaining-days);if(item.endingTimeRemaining<=0){item.ended=true;if(services.notifyIntelEnded)call(services,'notifyIntelEnded',item);}return;}if(services.advanceIntelImpl)call(services,'advanceIntelImpl',item,seconds);}
export function originalBaseIntelCanMakeVisible(item,inRelay,context,services){
 check(typeof inRelay==='boolean'&&typeof context.commSniffer==='boolean','Actual intel reception context required');if(originalIntelEnding(item))return false;
 const posting=item.postingLocation;if(posting===null)return inRelay;const settings=originalIntelSettings(services);let range=item.postingRangeLY??settings.maxRelayRangeInHyperspace,commRange=0;
 const inHyper=call(services,'isIntelEntityInHyperspace',posting);check(typeof inHyper==='boolean','Actual posting hyperspace state required');if(inHyper){commRange=settings.maxRelayRangeInHyperspace;range=Math.max(range,commRange);}
 const location=call(services,'readIntelEntityLocation',posting),same=location!==null&&location===context.location;if(range<=0&&!same)return false;
 if(inRelay)return f(originalIntelDistance(call(services,'readIntelEntityHyperPosition',posting),context.hyperPosition)/settings.unitsPerLightYear)<=range;
 if(inHyper)return f(originalIntelDistance(call(services,'readIntelEntityHyperPosition',posting),context.hyperPosition)/settings.unitsPerLightYear)<commRange&&(!context.commSniffer||inRelay);
 return same&&(!context.commSniffer||inRelay);
}
