/** ActionIndicator and PingScript. Sound intents are returned, never played inside world transactions. */
import R from '../data/reference-campaign-pings.json' with {type:'json'};
import {requireThat} from '../core/Values.mjs';
import {createOriginalFader,fadeOriginalFader,advanceOriginalFader,originalFaderIsIn,validateOriginalFader} from './OriginalFader.mjs';
import {originalLocationEntityState} from './OriginalLocationOrbits.mjs';
const f=Math.fround,check=(v,m)=>requireThat(v,'UNSUPPORTED_NATIVE_CAMPAIGN_PING',m);
const scalar=v=>{check(typeof v==='number'&&Number.isFinite(v)&&Number.isFinite(f(v)),'Actual finite ping float required');return f(v);};
const color=v=>{check(v===null||Array.isArray(v)&&v.length===4&&v.every(n=>Number.isInteger(n)&&n>=0&&n<=255),'Actual nullable ping color required');return v;};
const call=(s,k,...args)=>{check(typeof s[k]==='function','Actual ping service required: '+k);const result=s[k](...args);check(!result||typeof result.then!=='function','Synchronous ping service required');return result;};
export function validateOriginalPingSpec(s){check(s&&(s.id===null||typeof s.id==='string')&&Array.isArray(s.sounds)&&s.sounds.every(v=>v===null||typeof v==='string'),'Actual CampaignPingSpec required');for(const k of ['minRange','range','duration','delay','width','alphaMult','inFraction'])check(scalar(s[k])===s[k],'Native ping spec float required');check(Number.isInteger(s.num)&&s.num>=-2147483648&&s.num<=2147483647&&typeof s.invert==='boolean'&&typeof s.useFactionColor==='boolean','Actual ping spec flags required');color(s.color);return s;}
export function originalCampaignPingSpec(id){check(Object.hasOwn(R.specs,id),'Missing actual CampaignPingSpec: '+id);return validateOriginalPingSpec(R.specs[id]);}
function fields(entity,options,services){check(entity&&typeof entity==='object'&&options,'Actual ping source/options required');check(options.pingType===null||typeof options.pingType==='string','Actual nullable ping type required');check(options.custom===null||options.custom&&typeof options.custom==='object','Actual nullable custom ping spec required');const spec=options.pingType===null?options.custom:services.readPingSpec?call(services,'readPingSpec',options.pingType):originalCampaignPingSpec(options.pingType);validateOriginalPingSpec(spec);color(options.colorOverride);return {entity,pingType:options.pingType,custom:options.custom,spec,colorOverride:options.colorOverride};}
function validateFields(s){check(s?.entity&&typeof s.entity==='object'&&(s.pingType===null||typeof s.pingType==='string'),'Actual ping source identity required');validateOriginalPingSpec(s.spec);check(s.custom===null||validateOriginalPingSpec(s.custom),'Actual nullable custom spec required');if(s.pingType===null)check(s.custom===s.spec,'Lost shared custom ping spec');color(s.colorOverride);}
export function createOriginalActionIndicator(entity,options,services={}){const state={scope:'native-campaign-action-indicator',...fields(entity,options,services),fader:null};state.fader=createOriginalFader(0,state.spec.duration,0);fadeOriginalFader(state.fader,'IN');return state;}
export function validateOriginalActionIndicator(s){check(s?.scope==='native-campaign-action-indicator','Actual ActionIndicator required');validateFields(s);validateOriginalFader(s.fader);return s;}
export function advanceOriginalActionIndicator(s,seconds){validateOriginalActionIndicator(s);advanceOriginalFader(s.fader,scalar(seconds));}
export function originalActionIndicatorCanCleanUp(s){validateOriginalActionIndicator(s);return originalFaderIsIn(s.fader);}
export function validateOriginalPingScript(s){check(s?.scope==='native-campaign-ping-script','Actual PingScript required');validateFields(s);check(Number.isInteger(s.numLeft)&&s.numLeft>=-2147483648&&s.numLeft<=2147483647&&scalar(s.timeLeft)===s.timeLeft,'Actual ping script counter/float required');return s;}
function fire(s,context,services){
 check(context&&Object.hasOwn(context,'currentLocation'),'Actual nullable ping current location required');const entity=originalLocationEntityState(s.entity,services),effects=[];
 if(entity.containingLocation===context.currentLocation){const index=(s.spec.num-s.numLeft)|0;if(s.spec.sounds.length>index){check(index>=0,'Native ping sound index out of bounds');const id=s.spec.sounds[index];if(id!==null&&id!==''){check(Array.isArray(entity.velocity)&&entity.velocity.length===2,'Actual ping source velocity required');effects.push({kind:'campaign-sound',id,position:entity.position.map(scalar),velocity:entity.velocity.map(scalar),pitch:1,volume:1});}}}
 call(services,'addPingIndicator',createOriginalActionIndicator(s.entity,{pingType:s.custom!==null?null:s.pingType,custom:s.custom,colorOverride:s.custom!==null?null:s.colorOverride},services));s.numLeft=(s.numLeft-1)|0;s.timeLeft=s.spec.delay;return effects;
}
export function createOriginalPingScript(entity,options,context,services={}){const script={scope:'native-campaign-ping-script',...fields(entity,options,services),numLeft:0,timeLeft:0};script.numLeft=script.spec.num;return {script,effects:fire(script,context,services)};}
export function originalPingScriptIsDone(s){validateOriginalPingScript(s);return s.numLeft<=0;}
export function advanceOriginalPingScript(s,seconds,context,services={}){validateOriginalPingScript(s);const dt=scalar(seconds);check(dt>=0,'Negative ping dt');if(originalPingScriptIsDone(s))return [];s.timeLeft=f(s.timeLeft-dt);if(s.timeLeft<=0){const remainder=f(-s.timeLeft),effects=fire(s,context,services);s.timeLeft=f(s.timeLeft-remainder);return effects;}return [];}
