import type { JsonValue } from '../Types.js';
import type { OriginalResourceCargo } from './OriginalResourceCargo.mjs';
import type { OriginalFleetPayroll,OriginalAdministratorPayroll } from './OriginalMonthlyReport.mjs';
export interface OriginalPersonnelMemoryEntry {key:string;present:boolean;value:{type:string;text:string;source?:JsonValue}|null;expires:number[]}
export interface OriginalPayrollPerson {advanced?:boolean;fleetRef?:string|null;personalityId?:string|null;portraitSprite?:string|null;factionId?:string|null;marketRef?:string|null;aiCoreId?:string|null;nativeConstruction?:'default-administrator'|'default-fleet-captain'|'random-faction-person';importance?:import('./OriginalFactionPersons.mjs').OriginalPersonImportance;nativeMemoryAllocated?:boolean;rankId?:string;postId?:string;isAICore?:boolean;objectRef:string;id:string;name:{objectRef:string;first:string|null;last:string|null;gender?:string|null};stats:{objectRef:string;level:number;skills?:{skillId:string;level:number}[];fleetRef?:string|null;source?:JsonValue}&Partial<import('./OriginalNativeCharacterStats.mjs').OriginalNativeCharacterStats>;memory:{nativeState?:import('./OriginalCampaignMemory.mjs').OriginalCampaignMemory|null;objectRef:string;entries:Record<string,OriginalPersonnelMemoryEntry>;source?:JsonValue};source?:JsonValue}
export interface OriginalPayrollMarket {objectRef:string;marketId:string;name:string}
export interface OriginalPlayerCargo extends OriginalResourceCargo {objectRef:string;creditsRef:string;carryingFleetRef:string|null;spaceUsed:number|null;extraCargoUsed:number;extraCrewUsed:number;extraMarinesUsed:number;extraFuelUsed:number;extraSuppliesUsed:number;unresolved:string[]}
export interface OriginalPlayerEconomyState {scope:'native-current-player-economy';schemaVersion:1;characterRef:string;hullMods?:import('./OriginalJavaStringSet.mjs').OriginalJavaStringSet;characterMemory?:import('./OriginalCampaignMemory.mjs').OriginalCampaignMemory|null;nativeUID?:import('./OriginalMarketPersonnel.mjs').OriginalNativeUID|null;marketPersonnel?:import('./OriginalMarketPersonnel.mjs').OriginalMarketPersonnelRegistry;characterRefresh?:import('./OriginalNativeCharacterStats.mjs').OriginalCharacterWorldCapture;player:OriginalPayrollPerson;tutorial:OriginalPersonnelMemoryEntry;administrators:{objectRef:string;person:OriginalPayrollPerson;market:OriginalPayrollMarket|null;source?:JsonValue}[];fleet:{objectRef:string;dataRef:string;cargo:OriginalPlayerCargo;credits:{objectRef:string;value:number};officers:{objectRef:string;madePicks?:boolean;skillPicks?:string[];person:OriginalPayrollPerson;source?:JsonValue}[];synchronization:{lifecycle:'native-read-resolve-pending'|'native-constructed-pending'|'synchronizing'|'member-lists-only'|'current';needsSync:boolean;forceNoSync:boolean;onlySyncMemberLists:boolean};memberRefs:string[];source?:JsonValue}&Partial<import('./OriginalFleetData.mjs').OriginalNativeFleetFields>|null}
export interface OriginalPlayerEconomyCapture {scope:'native-saved-player-economy';state:OriginalPlayerEconomyState|null;unresolved:string[]}
export interface OriginalPlayerEconomyDependencies {nativeFleetServices?:import('./OriginalFleetData.mjs').OriginalFleetLifecycleServices;synchronizePlayerFleet?(state:OriginalPlayerEconomyState):void;readPersonnelMemoryFloat?(entry:OriginalPersonnelMemoryEntry):number}
export function originalPersonnelFullName(person:OriginalPayrollPerson):string;
export function originalPlayerLevel(state:OriginalPlayerEconomyState):number;
export function originalTutorialInProgress(state:OriginalPlayerEconomyState):boolean;
export function originalOfficerPayroll(state:OriginalPlayerEconomyState):OriginalFleetPayroll['officers'];
export function originalAdministratorPayroll(state:OriginalPlayerEconomyState,dependencies?:OriginalPlayerEconomyDependencies):OriginalAdministratorPayroll[];
export function originalPlayerFleetPayroll(state:OriginalPlayerEconomyState,dependencies?:OriginalPlayerEconomyDependencies):OriginalFleetPayroll;
export function originalPlayerCargoStat(state:OriginalPlayerEconomyState,kind:'crew'|'marines'|'supplies'|'fuel'|'cargo',dependencies?:OriginalPlayerEconomyDependencies):number;
export function validateOriginalPlayerEconomy(state:OriginalPlayerEconomyState):OriginalPlayerEconomyState;
/** Structural identity validation after a bounded shared-graph decoder; not an input sanitizer. */
export function validateOriginalPlayerEconomyReferences(state:OriginalPlayerEconomyState):OriginalPlayerEconomyState;
export function restoreOriginalPlayerEconomy(state:OriginalPlayerEconomyState):OriginalPlayerEconomyState;

export function originalPlayerCharacterMemoryWithoutUpdate(state:OriginalPlayerEconomyState):import('./OriginalCampaignMemory.mjs').OriginalCampaignMemory;
