/** BaseIndustry frames/effects for ordinary no-item population, ports and ground defenses. Lamps stay unsupported. */
import {requireThat} from '../core/Values.mjs';
import {blank,functional} from './OriginalIndustryState.mjs';
import {newOriginalCivicIndustry} from './OriginalCivicIndustries.mjs';
import {ORIGINAL_MILITARY_BASES as catalog} from './OriginalMilitaryBases.mjs';
import {hasOriginalCivicFrame,hasOriginalCivicEffects,unapplyOriginalCivicIndustry,unapplyOriginalCivicItem} from './OriginalCivicIndustryEffects.mjs';
import {isSupportedOriginalPortItem} from './OriginalPortItems.mjs';
import {isSupportedOriginalGroundDefenseItem} from './OriginalGroundDefenses.mjs';
import {originalIndustryDisruptionKey} from './OriginalIndustryRuntime.mjs';
import {validateOriginalCampaignMemory,originalCampaignMemoryContains,originalCampaignMemoryBoolean,setOriginalCampaignMemory,unsetOriginalCampaignMemory} from './OriginalCampaignMemory.mjs';
import {advanceOriginalBaseIndustryFrame} from './OriginalBaseIndustryFrame.mjs';
const f=Math.fround,check=(v,m)=>requireThat(v,'UNSUPPORTED_CIVIC_LIFECYCLE',m),float=v=>Number.isFinite(v)&&f(v)===v;
const validItem=(id,special)=>special===null||id!=='population'&&special&&typeof special.objectRef==='string'&&(isSupportedOriginalPortItem(id,special.id)||isSupportedOriginalGroundDefenseItem(id,special.id));
const spec=id=>{check(hasOriginalCivicFrame(id),'Actual civic plugin required');return catalog.industrySpecs[id];};
function current(m,id){const row=m.civicLifecycle?.industries.find(row=>row.active&&row.entry.state.industryId===id);check(row,'Actual active civic instance required');return row;}
export function restoreOriginalCivicLifecycle(saved,m,share=value=>value){
 const selected=saved.industries.filter(i=>hasOriginalCivicFrame(i.industryId));if(selected.some(i=>!Object.hasOwn(i,'buildCostOverride')||!Object.hasOwn(i,'specialItem')||!i.runtimeInput))return null;
 // Ordinary population support must not admit an installed lamp and only fail
 // after sharing its object or entering a later construction/frame callback.
 for(const i of selected)if(i.industryId==='population')check(i.specialItem===null,'Population special items/lamp are not implemented; cannot restore this civic lifecycle');
 const disruptions=[];for(const i of selected){const d=i.runtimeInput.disruption,old=disruptions.find(row=>row.key===d.key);check(!old||JSON.stringify(old)===JSON.stringify(d),'Conflicting civic disruption capture');if(!old)disruptions.push(structuredClone(d));}
 return {scope:'native-civic-industry-lifecycle',nextObjectId:0,memory:null,disruptions,messages:[],industries:selected.map(i=>({objectRef:i.objectRef,active:true,entry:m.industries.find(e=>e.state.industryId===i.industryId),finances:m.finances.find(e=>e.industryId===i.industryId),buildProgress:i.buildProgress,buildTime:Math.max(1,i.buildTime??0),buildCostOverride:i.buildCostOverride,wasDisrupted:i.wasDisrupted,special:i.specialItem?share(structuredClone(i.specialItem)):null}))};
}
export function validateOriginalCivicLifecycle(m){
 const s=m.civicLifecycle;check(s?.scope==='native-civic-industry-lifecycle'&&Number.isSafeInteger(s.nextObjectId)&&s.nextObjectId>=0&&Array.isArray(s.industries)&&Array.isArray(s.messages),'Actual civic lifecycle capture required');
 check(new Set(s.industries.map(row=>row.objectRef)).size===s.industries.length&&new Set(s.industries.map(row=>row.entry)).size===s.industries.length&&new Set(s.industries.map(row=>row.finances)).size===s.industries.length,'Split civic instance identities');
 if(s.memory!==null){validateOriginalCampaignMemory(s.memory);check(s.disruptions===null,'Bound civic lifecycle cannot duplicate Memory');}else{const keys=new Set(s.industries.map(row=>originalIndustryDisruptionKey(row.entry.state.industryId)));check(Array.isArray(s.disruptions)&&s.disruptions.length===keys.size&&new Set(s.disruptions.map(d=>d.key)).size===keys.size&&s.disruptions.every(d=>keys.has(d.key)&&typeof d.present==='boolean'&&Array.isArray(d.expires)&&d.expires.every(float)&&(d.present?['boolean','string','number'].includes(typeof d.value):d.value===null)),'Actual civic disruption history required');}
 for(const row of s.industries){const id=row.entry?.state.industryId;spec(id);check(typeof row.objectRef==='string'&&typeof row.active==='boolean'&&typeof row.wasDisrupted==='boolean'&&float(row.buildProgress)&&float(row.buildTime)&&(row.buildTime>=1||(id==='population'&&row.buildTime===0))&&(row.buildCostOverride===null||float(row.buildCostOverride)),'Actual civic BaseIndustry fields required');functional(row.entry.operating);check(m.industries.includes(row.entry)===row.active&&m.finances.includes(row.finances)===row.active&&row.finances.industryId===id,'Lost active/retired civic identities');check((row.special?.id??null)===row.entry.modifiers.specialItemId&&validItem(id,row.special),'Lost civic SpecialItemData');}
 check(m.industries.filter(e=>hasOriginalCivicFrame(e.state.industryId)).every(e=>s.industries.some(row=>row.active&&row.entry===e)),'Missing current civic instance');return s;
}
function memory(m){const value=validateOriginalCivicLifecycle(m).memory;check(value,'Civic frames require complete bound market Memory');return value;}
export function bindOriginalCivicMemory(m,mem){const s=validateOriginalCivicLifecycle(m);validateOriginalCampaignMemory(mem);if(s.memory!==null){check(s.memory===mem,'Cannot replace bound civic Memory');return;}
 for(const d of s.disruptions){const data=mem.data.find(row=>row.key===d.key),expires=mem.expire.filter(row=>row.key===d.key);check(Boolean(data)===d.present&&(!d.present||Object.is(data.value,d.value))&&expires.length===d.expires.length&&expires.every((row,i)=>Object.is(row.timeLeft,d.expires[i])),'Civic Memory disagrees with captured disruption');}s.memory=mem;s.disruptions=null;
}
function isDisrupted(m,row,services){const mem=memory(m),key=originalIndustryDisruptionKey(row.entry.state.industryId);return row.entry.operating.disrupted=originalCampaignMemoryContains(mem,key,services)&&originalCampaignMemoryBoolean(mem,key,services);}
export function syncOriginalCivicDisruption(m,services={}){for(const row of validateOriginalCivicLifecycle(m).industries)isDisrupted(m,row,services);}
export function setOriginalCivicDisrupted(m,id,days,useMax=false,services={}){const row=current(m,id),mem=memory(m),key=originalIndustryDisruptionKey(id);check(float(days)&&typeof useMax==='boolean','Actual civic disruption duration required');isDisrupted(m,row,services);const duration=useMax?Math.max(days,mem.expire.find(e=>e.key===key)?.timeLeft??-1):days;if(duration<=0)unsetOriginalCampaignMemory(mem,key,services);else setOriginalCampaignMemory(mem,key,true,duration);syncOriginalCivicDisruption(m,services);return row.entry.operating.disrupted;}
export function instantiateOriginalCivicIndustry(m,id){validateOriginalCivicLifecycle(m);spec(id);return {objectRef:'created-civic-industry:'+m.objectRef+':'+m.civicLifecycle.nextObjectId++,active:false,entry:{state:structuredClone(newOriginalCivicIndustry(id)),operating:{building:false,upgradeId:null,disrupted:false},modifiers:{aiCoreId:null,improved:false,specialItemId:null,adminSupplyBonus:0,adminDemandReduction:0,supplyBonusFromOther:blank(),demandReductionFromOther:blank()}},finances:{industryId:id,income:blank(),upkeep:blank()},buildProgress:0,buildTime:1,buildCostOverride:null,wasDisrupted:false,special:null};}
export function addOriginalCivicIndustry(m,id,runtime){const old=m.civicLifecycle.industries.find(row=>row.active&&row.entry.state.industryId===id);if(old)return old;const row=instantiateOriginalCivicIndustry(m,id);memory(m);check(hasOriginalCivicEffects(id),'Actual civic constructor apply required');row.active=true;m.civicLifecycle.industries.push(row);m.industries.push(row.entry);m.finances.push(row.finances);isDisrupted(m,row,runtime.memoryServices);runtime.apply(row);return row;}
// BaseIndustry.startBuilding uses the literal spec time: population is ZERO, not
// readResolve's >=1 clamp. The next undisrupted Base.advance may finish at day 0.
export function startBuildingOriginalCivicIndustry(m,row){check(hasOriginalCivicEffects(row.entry.state.industryId)&&validItem(row.entry.state.industryId,row.special),'Actual supported civic unapply required; population items/lamp remain unsupported');
 if(row.entry.state.industryId==='population')check(row.special===null&&row.entry.modifiers.specialItemId===null,'Population special items/lamp must be rejected before changing construction state');row.entry.operating.building=true;row.entry.operating.upgradeId=null;row.buildProgress=0;row.buildTime=spec(row.entry.state.industryId).buildTime;unapplyOriginalCivicIndustry(m,row);}
export function startOriginalCivicUpgrade(m,id){const row=current(m,id),target=spec(id).upgradeId;check(target!==null&&hasOriginalCivicEffects(target),'Actual civic upgrade required');row.entry.operating.building=true;row.entry.operating.upgradeId=target;row.buildProgress=0;row.buildTime=spec(target).buildTime;}
// BaseIndustry.cancelUpgrade resets flags/progress, NOT buildTime. A population
// startBuilding -> cancelUpgrade sequence therefore legitimately keeps time=0.
export function cancelOriginalCivicUpgrade(m,id){const row=current(m,id);row.entry.operating.building=false;row.entry.operating.upgradeId=null;row.buildProgress=0;}
export function setOriginalCivicSpecialItem(m,row,special){if(row.entry.state.industryId==='population')check(special===null&&row.special===null&&row.entry.modifiers.specialItemId===null,'Population special items/lamp cannot be installed or silently unapplied');check(validItem(row.entry.state.industryId,special),'Actual compatible SpecialItemData required');unapplyOriginalCivicItem(m,row);row.special=special;row.entry.modifiers.specialItemId=special?.id??null;}
function message(m,row,runtime){if(m.playerOwned)m.civicLifecycle.messages.push({marketId:m.marketId,industryId:row.entry.state.industryId,industryRef:row.objectRef,kind:'finished',timestamp:runtime.timestamp(),clickAction:'COLONY_INFO'});}
function reapply(m,row,runtime){unapplyOriginalCivicIndustry(m,row);runtime.apply(row);}
function finish(m,row,runtime){check(hasOriginalCivicEffects(row.entry.state.industryId),'Actual civic finish/apply required');const e=row.entry;e.operating.building=false;row.buildProgress=0;row.buildTime=1;
 if(e.operating.upgradeId!==null){const target=e.operating.upgradeId;check(hasOriginalCivicEffects(target),'Actual civic upgrade plugin required');unapplyOriginalCivicIndustry(m,row);m.industries.splice(m.industries.indexOf(e),1);m.finances.splice(m.finances.indexOf(row.finances),1);row.active=false;const next=addOriginalCivicIndustry(m,target,runtime);next.entry.modifiers.aiCoreId=e.modifiers.aiCoreId;next.entry.modifiers.improved=e.modifiers.improved;message(m,next,runtime);setOriginalCivicSpecialItem(m,next,row.special);reapply(m,next,runtime);return next.objectRef;}
 message(m,row,runtime);runtime.buildNextInQueue();reapply(m,row,runtime);return row.objectRef;
}
export function advanceOriginalCivicIndustryFrame(m,row,days,runtime,{colonyDebug=false}={}){check(validateOriginalCivicLifecycle(m).industries.includes(row),'Actual current or retained civic instance required');memory(m);const finishedRef=advanceOriginalBaseIndustryFrame(row,days,{colonyDebug},{isDisrupted:()=>isDisrupted(m,row,runtime.memoryServices),disruptionFinished:()=>{},finishBuildingOrUpgrading:()=>finish(m,row,runtime)});return {scope:'native-civic-industry-frame',industryRef:row.objectRef,finishedRef};}
