import type {DeepReadonly} from '../Types.js';import type {EconomyMutable} from './OriginalMarketEconomy.mjs';
export interface OriginalPatrolTracker {objectRef:string;minInterval:number;maxInterval:number;currInterval:number;elapsed:number;intervalElapsed:boolean;randomRef:string|null}
export interface OriginalRouteSegment {objectRef:string;id:number|null;elapsed:number;daysMax:number;fromRef:string|null;toRef:string|null;customRef:string|null}
export interface OriginalPatrolRoute {objectRef:string;source:string|null;marketId:string|null;marketRef:string|null;seed:string|null;timestamp:string;delay:number;elapsed:number;daysSinceSeenByPlayer:number;activeFleetRef:string|null;spawnerRef:string|null;spawnerKind:string|null;custom:{objectRef:string;kind:'military-patrol';type:'FAST'|'COMBAT'|'HEAVY';spawnFP:number}|{objectRef:string;kind:'other';className:string}|null;extra:{objectRef:string;strength:number|null;quality:number|null;fp:number|null;factionId:string|null;fleetType:string|null;damage:number|null}|null;segments:OriginalRouteSegment[];current:OriginalRouteSegment|null}
export interface OriginalPatrolState {simMode?:boolean;scope:'native-patrol-route-state';schemaVersion:1;objectRef:string;nextObjectId:number;unresolved:string[];markets:{marketId:string;marketRef:string;primaryEntityRef:string|null;spawnRate:EconomyMutable}[];industries:{objectRef:string;marketId:string;marketRef:string;industryId:string;tracker:OriginalPatrolTracker|null;returningPatrolValue:number}[];routes:OriginalPatrolRoute[]}
export interface OriginalPatrolRuntime {randomDouble():number;newRouteSeed():string;timestamp():string;maxPatrols(marketId:string,type:'FAST'|'COMBAT'|'HEAVY'):number;factionId(marketId:string):string;shipQuality(marketId:string,factionId:string|null):number;fleetSize(marketId:string):number;officerQuality(marketId:string):number;primaryEntityRef(marketId:string):string|null}
export function restoreCapturedOriginalPatrolState(capture:OriginalPatrolState):OriginalPatrolState;
export function validateOriginalPatrolState(state:OriginalPatrolState,options?:{allowUnresolved?:boolean}):OriginalPatrolState;
export function originalPatrolCombatFP(type:'FAST'|'COMBAT'|'HEAVY',seed:string):number;
export function originalPatrolRouteCounts(state:OriginalPatrolState,marketId:string):{FAST:number;COMBAT:number;HEAVY:number};
export function advanceOriginalMilitaryPatrolAfterBase(state:OriginalPatrolState,industryRef:string,input:{days:number;simMode:boolean;functional:boolean;inNewGameAdvance:boolean;fastPatrolSpawn:boolean;spawnRate:number},runtime:OriginalPatrolRuntime):DeepReadonly<{scope:'military-patrol-after-base-only';createdRouteRef:string|null;advanced:boolean}>;
export function advanceOriginalRouteTime(state:OriginalPatrolState,days:number,runtime:{timestamp():string;shouldCancelAfterDelay(route:OriginalPatrolRoute):boolean;shouldRepeat(route:OriginalPatrolRoute):boolean}):DeepReadonly<{scope:'route-time-phase-without-spawn-despawn';removed:string[]}>;
export function reportOriginalPatrolReturned(state:OriginalPatrolState,industryRef:string,input:{functional:boolean;reason:string;fleetRef:string;fleetPoints:number}):number;
