import type {OriginalJavaRandomState} from './OriginalJavaRandom.mjs';
import type {OriginalConstructedCampaignFleet,OriginalFleetConstructionFaction} from './OriginalCampaignFleet.mjs';
import type {OriginalFleetRosterBinding} from './OriginalFleetRoster.mjs';
import type {OriginalPayrollPerson} from './OriginalPlayerEconomy.mjs';
export type OriginalFleetAIModuleKind='navigation'|'assignment'|'strategic'|'tactical';
export interface OriginalFleetAIModule {objectRef:string;scope?:string;[key:string]:unknown}
export interface OriginalModularFleetAI {scope:'native-modular-fleet-ai';objectRef:string;fleet:OriginalConstructedCampaignFleet;navModule:OriginalFleetAIModule;assignmentModule:OriginalFleetAIModule;strategicModule:OriginalFleetAIModule;tacticalModule:OriginalFleetAIModule;abilityAI:[string,object][];noAIAbilities:string[];actionTextProvider:object|null;actionTextOverride:string|null;[key:string]:unknown}
export interface OriginalModularFleetAIConstructionServices {globalRandom?:OriginalJavaRandomState;pickFleetAIModule(kind:OriginalFleetAIModuleKind,fleet:OriginalConstructedCampaignFleet,ai:OriginalModularFleetAI):OriginalFleetAIModule|null}
export interface OriginalModularFleetAIFrameServices {convertAIDays?(seconds:number):number;advanceFleetAIModule?(kind:OriginalFleetAIModuleKind,module:OriginalFleetAIModule,days:number,ai:OriginalModularFleetAI):void;readFleetAIAbilities?(fleet:OriginalConstructedCampaignFleet):{id:string;[key:string]:unknown}[];pickFleetAbilityAI?(ability:{id:string},ai:OriginalModularFleetAI):object|null;fleetHasAIAbility?(fleet:OriginalConstructedCampaignFleet,id:string):boolean;advanceFleetAbilityAI?(plugin:object,days:number,ability:{id:string},ai:OriginalModularFleetAI):void}
export interface OriginalNamedFleetFactoryServices {readFactoryFaction(id:string):OriginalFleetConstructionFaction;constructFactoryFleet(faction:OriginalFleetConstructionFaction,aiMode:boolean):OriginalFleetRosterBinding & {fleet:OriginalConstructedCampaignFleet};createFactoryFleetAI(fleet:OriginalConstructedCampaignFleet):OriginalFleetAIModule;readFactoryFleetCommander(fleet:OriginalConstructedCampaignFleet):OriginalPayrollPerson}
export function createOriginalModularFleetAI(objectRef:string,fleet:OriginalConstructedCampaignFleet,services:OriginalModularFleetAIConstructionServices):OriginalModularFleetAI;
export function validateOriginalModularFleetAI(ai:OriginalModularFleetAI,fleet?:OriginalConstructedCampaignFleet):OriginalModularFleetAI;
export function advanceOriginalModularFleetAI(ai:OriginalModularFleetAI,seconds:number,services:OriginalModularFleetAIFrameServices):void;
export function createOriginalNamedEmptyFleet(factionId:string,name:string|null,aiMode:boolean,services:OriginalNamedFleetFactoryServices):OriginalFleetRosterBinding & {fleet:OriginalConstructedCampaignFleet};
