/** Native FactionManager.Relation, Relationship and RepLevel; not a guessed initial diplomacy matrix. */
import R from '../data/reference-battle-autoresolver.json' with {type:'json'};
import {requireThat} from '../core/Values.mjs';
const f=Math.fround,check=(v,m)=>requireThat(v,'UNSUPPORTED_NATIVE_RELATIONSHIP',m);
const num=n=>{check(typeof n==='number'&&Number.isFinite(n)&&Number.isFinite(f(n)),'Actual finite reputation float required');return f(n);};
const levels=R.reputation.levels,level=id=>{const v=levels.find(l=>l.id===id);check(v,'Actual RepLevel required: '+id);return v;};
const ordinal=id=>{level(id);return levels.findIndex(l=>l.id===id);},positive=id=>ordinal(id)>4,negative=id=>ordinal(id)<4;
export function originalReputationInt(value){return Math.max(-2147483648,Math.min(2147483647,Math.floor(f(num(value)*100)+.5)));}
export function originalReputationLevel(value){value=num(value);const n=originalReputationInt(value>=0?value:-value);const at=n<=originalReputationInt(level('NEUTRAL').max)?0:n<=originalReputationInt(level('FAVORABLE').max)?1:n<=originalReputationInt(level('WELCOMING').max)?2:n<=originalReputationInt(level('FRIENDLY').max)?3:4;return levels[4+(value>=0?at:-at)].id;}
export const originalRepAtBest=(current,best)=>ordinal(current)<=ordinal(best),originalRepAtWorst=(current,worst)=>ordinal(current)>=ordinal(worst);
const clamp=n=>Math.max(-1,Math.min(1,num(n)));
const setLevelValue=id=>id==='NEUTRAL'?0:positive(id)?f(level(id).min+f(.01)):f(-level(id).min-f(.01));
function adjusted(before,delta,limit){delta=num(delta);if(delta===0)return null;let next=f(before+delta);if(delta>0){limit??='COOPERATIVE';const bound=negative(limit)?f(-level(limit).min-f(.01)):level(limit).max;next=Math.min(next,bound);return next>before?next:null;}limit??='VENGEFUL';const bound=positive(limit)?f(level(limit).min+f(.01)):-level(limit).max;next=Math.max(next,bound);return next<before?next:null;}
export function createOriginalFactionRelations(objectRef,factions,playerFaction){return validateOriginalFactionRelations({scope:'native-current-faction-relations',objectRef,serial:0,factions:[...factions],playerFaction,relations:[]});}
export function validateOriginalFactionRelations(manager){
 check(manager?.scope==='native-current-faction-relations'&&typeof manager.objectRef==='string'&&manager.objectRef.length>0,'Actual complete FactionManager state required');check(Number.isSafeInteger(manager.serial)&&manager.serial>=0&&Array.isArray(manager.factions)&&Array.isArray(manager.relations),'Actual faction and relationship maps required');const ids=new Set(),refs=new Set();for(const faction of manager.factions){check(typeof faction?.objectRef==='string'&&typeof faction.factionId==='string'&&faction.factionId.length>0&&!ids.has(faction.factionId)&&!refs.has(faction.objectRef),'Unique actual faction identities required');ids.add(faction.factionId);refs.add(faction.objectRef);}check(manager.playerFaction===null||manager.factions.includes(manager.playerFaction),'Lost player faction identity');const keys=new Set(),relations=new Map();for(const row of manager.relations){check(typeof row.key==='string'&&!keys.has(row.key),'Unique native relation map key required');keys.add(row.key);const r=row.relation;check(typeof r?.objectRef==='string'&&typeof r.factionIdOne==='string'&&typeof r.factionIdTwo==='string'&&r.value===clamp(r.value),'Actual native Relation fields required');check(!relations.has(r.objectRef)||relations.get(r.objectRef)===r,'Split shared Relation identity');relations.set(r.objectRef,r);check(row.key===r.factionIdOne+'_'+r.factionIdTwo||row.key===r.factionIdTwo+'_'+r.factionIdOne,'Native relation key/value mismatch');}return manager;
}
export function originalFactionById(manager,id){check(manager?.scope==='native-current-faction-relations','Actual FactionManager required');return manager.factions.find(faction=>faction.factionId===id)??null;}
/** Native string-key behavior (including underscore collisions), not a normalized pair map. */
export function originalFactionRelation(manager,one,two){check(manager?.scope==='native-current-faction-relations','Actual FactionManager required');if(one===null||two===null)return null;check(typeof one==='string'&&typeof two==='string','Native nullable faction IDs required');const key=one+'_'+two,existing=manager.relations.find(r=>r.key===key);if(existing)return existing.relation;check(Number.isSafeInteger(manager.serial)&&manager.serial<Number.MAX_SAFE_INTEGER,'Actual relation identity allocator required');const relation={objectRef:'created:'+manager.objectRef+':relation:'+(++manager.serial),factionIdOne:one,factionIdTwo:two,value:one===two?1:0};for(const key of [one+'_'+two,two+'_'+one]){const row=manager.relations.find(r=>r.key===key);if(row)row.relation=relation;else manager.relations.push({key,relation});}return relation;}
export function setOriginalFactionRelation(manager,one,two,value){const relation=originalFactionRelation(manager,one,two);check(relation,'Non-null faction IDs required for setRelationship');relation.value=clamp(value);}
export function bindOriginalFactionRelationship(manager,ownerId,targetFaction){
 check(originalFactionById(manager,ownerId)!==null&&targetFaction,'Actual relationship owner and target faction required');let target={type:'FACTION',faction:targetFaction,person:null};
 const relation=()=>originalFactionRelation(manager,ownerId,targetFaction.factionId),getRel=()=>relation().value,setRel=value=>{relation().value=clamp(value);},getLevel=()=>originalReputationLevel(getRel());
 return {getTarget:()=>target,setTarget:value=>{target=value;},getRel,setRel,getLevel,getRepInt:()=>originalReputationInt(getRel()),isAtBest:id=>originalRepAtBest(getLevel(),id),isAtWorst:id=>originalRepAtWorst(getLevel(),id),isHostile:()=>originalRepAtBest(getLevel(),'HOSTILE'),setLevel:id=>setRel(setLevelValue(id)),
  adjustRelationship:(delta,limit=null)=>{if(num(delta)===0)return false;const next=adjusted(getRel(),delta,limit);if(next===null)return false;setRel(next);return true;},
  ensureAtBest:id=>{if(originalRepAtBest(getLevel(),id))return false;setRel(negative(id)?f(-level(id).min-f(.01)):level(id).max);return true;},
  ensureAtWorst:id=>{if(originalRepAtWorst(getLevel(),id))return false;setRel(negative(id)?-level(id).max:f(level(id).min+f(.01)));return true;}
 };
}
export function createOriginalRelationship(target){return {scope:'native-relationship',rel:0,target};}
export function bindOriginalRelationship(state){check(state?.scope==='native-relationship'&&state.rel===clamp(state.rel)&&Object.hasOwn(state,'target'),'Actual Relationship state required');const getRel=()=>state.rel,setRel=value=>{state.rel=clamp(value);},getLevel=()=>originalReputationLevel(getRel()),setLevel=id=>setRel(setLevelValue(id));return {
 getTarget:()=>state.target,setTarget:value=>{state.target=value;},getRel,setRel,getLevel,setLevel,getRepInt:()=>originalReputationInt(getRel()),isAtBest:id=>originalRepAtBest(getLevel(),id),isAtWorst:id=>originalRepAtWorst(getLevel(),id),isHostile:()=>originalRepAtBest(getLevel(),'HOSTILE'),
 adjustRelationship:(delta,limit=null)=>{const next=adjusted(getRel(),delta,limit);if(next===null)return false;setRel(next);return true;},ensureAtBest:id=>{if(originalRepAtBest(getLevel(),id))return false;setLevel(id);return true;},ensureAtWorst:id=>{if(originalRepAtWorst(getLevel(),id))return false;setLevel(id);return true;}
 };}
