import type {DeepReadonly} from '../Types.js';import type {EconomyBonus,EconomyMutable} from './OriginalMarketEconomy.mjs';import type {OriginalIndustryCommodityEntry} from './OriginalIndustryCommodityPass.mjs';import type {OriginalIndustryFinanceResult} from './OriginalMarketFinance.mjs';import type {OriginalMemoryFlags} from './OriginalMemoryFlags.mjs';
export const ORIGINAL_MILITARY_BASES:DeepReadonly<{schemaVersion:1;originalReference:string;scope:string;sources:Record<string,{sha256:string}>;constants:Record<string,number>;routeManager:Record<string,number>;settings:{doctrineFleetQualityPerPoint:number;averagePatrolSpawnInterval:number};industrySpecs:Record<string,{tags:string[];upgradeId:string|null;buildTime:number}>;industries:Record<string,{tags:string[]}>;item:{id:string;industryIds:string[];conditionBonuses:Record<string,number>;requirementName:string}}>;
export interface OriginalMilitaryMarketState {scope:'native-military-market-inputs';memory:OriginalMemoryFlags;officerProbability:EconomyBonus}
export interface OriginalMilitaryMarket {conditions:{id:string}[];size:number;stability:EconomyMutable;groundDefenses:EconomyBonus;economyBonuses:Record<string,EconomyBonus>|null;military:OriginalMilitaryMarketState|null}
export interface OriginalMilitaryResult {scope:'military-industry-apply-effects-not-fleet-spawning';industryId:string;operating:boolean;patrols:{light:number;medium:number;heavy:number};stabilityDeficit:{commodityId:string|null;deficit:number};defenseDeficit:{commodityId:string|null;deficit:number};descriptionDeficit:{commodityId:string|null;deficit:number}|null;deficitMult:number;defenseMultiplier:number;officerProbability:number;finance:OriginalIndustryFinanceResult}
export function isSupportedOriginalMilitaryItem(industryId:string,itemId:string|null|undefined):boolean;
/** Installed-item runtime requirements, not a surveyed UI installation quote. */
export function originalMilitaryItemRequirements(industryId:string,itemId:string,conditionIds:string[]):DeepReadonly<string[]>;
export function originalMilitaryPatrolCounts(industryId:string,marketSize:number):{light:number;medium:number;heavy:number};
export function unapplyOriginalMilitaryBase(market:OriginalMilitaryMarket,industry:OriginalIndustryCommodityEntry):void;
export function applyOriginalMilitaryBase(market:OriginalMilitaryMarket,industry:OriginalIndustryCommodityEntry,runtime:{applyFinances():DeepReadonly<OriginalIndustryFinanceResult>;readCommodityAvailable(commodityId:string):number}):DeepReadonly<OriginalMilitaryResult>;
