/** CampaignEventManager/EventProbability orchestration; active event plugins remain explicit implementations. */
import R from '../data/reference-campaign-events.json' with {type:'json'};
import {requireThat} from '../core/Values.mjs';
import {createOriginalJavaRandom,validateOriginalJavaRandom,originalJavaNextDouble,originalJavaNextLong,originalJavaNextInt} from './OriginalJavaRandom.mjs';
import {createOriginalCampaignInterval,validateOriginalCampaignInterval,setOriginalCampaignInterval,advanceOriginalCampaignInterval} from './OriginalCampaignInterval.mjs';
import {validateOriginalCampaignEventTarget,originalCampaignEventTargetEquals,originalCampaignEventMapEntry,putOriginalCampaignEventMap,removeOriginalCampaignEventMap,originalCampaignEventMapKeys,validateOriginalCampaignEventMap} from './OriginalCampaignEventKeys.mjs';
export const ORIGINAL_CAMPAIGN_EVENTS=Object.freeze(R);
const f=Math.fround,check=(ok,message)=>requireThat(ok,'UNSUPPORTED_NATIVE_CAMPAIGN_EVENTS',message);
const number=value=>{check(typeof value==='number'&&Number.isFinite(value)&&Number.isFinite(f(value)),'Actual finite event float required');return f(value);};
const bool=value=>{check(typeof value==='boolean','Actual event Boolean required');return value;};
const call=(services,name,...args)=>{check(typeof services[name]==='function','Actual event service required: '+name);const value=services[name](...args);check(!value||typeof value.then!=='function','Event services must be synchronous');return value;};
const plugin=value=>{check(value&&typeof value.objectRef==='string'&&value.objectRef.length>0,'Actual CampaignEventPlugin identity required');return value;};
function spec(eventType,services){const value=services.readCampaignEventSpec?call(services,'readCampaignEventSpec',eventType):R.specs.find(s=>s.id===eventType);check(value?.id===eventType&&Number.isInteger(value.maxOngoing)&&value.maxOngoing===(value.maxOngoing|0),'Actual enabled event specification required: '+eventType);number(value.probabilityMult);return value;}
const math=state=>originalJavaNextDouble(state.random.mathRandom);
/** NEW manager only. The references are the explicit shared Web RNG branch, not guessed JVM random history. */
export function createOriginalCampaignEventManager(objectRef,mathRandom,newRandomSeeds){
 check(typeof objectRef==='string'&&objectRef.length>0,'Actual new event-manager identity required');validateOriginalJavaRandom(mathRandom);validateOriginalJavaRandom(newRandomSeeds);check(mathRandom!==newRandomSeeds,'Distinct Math/new-Random streams required');
 const state={scope:'native-campaign-event-manager',objectRef,probabilities:{capacity:0,entries:[]},ongoingEvents:[],tracker:null,keyList:[],currIndex:0,keyListForWarnings:[],currIndexForWarning:0,checkWarning:true,nextProbabilitySerial:'1',random:{scope:'web-campaign-event-random-branch',binding:'explicit',mathRandom,newRandomSeeds,shuffleRandom:null}};
 state.tracker=createOriginalCampaignInterval(1,1,()=>math(state));return validateOriginalCampaignEventManager(state);
}
export function validateOriginalCampaignEventManager(state,related=[]){
 check(state?.scope==='native-campaign-event-manager'&&typeof state.objectRef==='string'&&state.objectRef.length>0,'Actual campaign event-manager state required');validateOriginalCampaignInterval(state.tracker);validateOriginalCampaignEventMap(state.probabilities);
 check(state.random?.scope==='web-campaign-event-random-branch'&&['explicit','runtime-shared'].includes(state.random.binding),'Actual persistent event random branch required');validateOriginalJavaRandom(state.random.mathRandom);validateOriginalJavaRandom(state.random.newRandomSeeds);check(state.random.mathRandom!==state.random.newRandomSeeds,'Distinct event random sources required');if(state.random.shuffleRandom!==null){validateOriginalJavaRandom(state.random.shuffleRandom);check(state.random.shuffleRandom!==state.random.mathRandom&&state.random.shuffleRandom!==state.random.newRandomSeeds,'Independent Collections.shuffle random required');}
 check(typeof state.checkWarning==='boolean'&&typeof state.nextProbabilitySerial==='string'&&/^[1-9][0-9]*$/.test(state.nextProbabilitySerial),'Actual event cursor state required');for(const key of ['currIndex','currIndexForWarning'])check(Number.isInteger(state[key])&&state[key]===(state[key]|0),'Actual Java int event cursor required');
 for(const key of ['keyList','keyListForWarnings']){check(Array.isArray(state[key]),'Actual saved event key snapshot required');for(const entry of state[key]){check(typeof entry.eventType==='string','Actual snapshot Pair required');validateOriginalCampaignEventTarget(entry.target);}}
 check(Array.isArray(state.ongoingEvents),'Actual ongoing event list required');const identities=new Map();const identity=item=>{plugin(item);check(!identities.has(item.objectRef)||identities.get(item.objectRef)===item,'Lost shared event plugin/probability identity');identities.set(item.objectRef,item);};
 for(const row of state.probabilities.entries){const p=row.probability;check(p?.scope==='native-event-probability'&&p.eventType===row.key.eventType&&p.eventTarget===row.key.target&&number(p.probability)===p.probability&&typeof p.primed==='boolean','Actual shared EventProbability state required');identity(p);identity(p.plugin);}
 state.ongoingEvents.forEach(identity);related.forEach(identity);return state;
}
export function originalCampaignEventProbabilityValue(probability,services={}){return f(number(probability.probability)*number(spec(probability.eventType,services).probabilityMult));}
export function setOriginalCampaignEventProbability(probability,value){probability.probability=number(value);}
export function changeOriginalCampaignEventProbability(probability,amount){probability.probability=f(probability.probability+number(amount));}
export function setOriginalCampaignEventProbabilityAfterMult(probability,value,services={}){value=number(value);if(number(spec(probability.eventType,services).probabilityMult)<=0)return;probability.probability=f(value/number(spec(probability.eventType,services).probabilityMult));}
export function checkOriginalCampaignEventProbability(state,probability,services={}){const success=math(state)<originalCampaignEventProbabilityValue(probability,services);if(success)probability.probability=0;else{probability.probability=f(probability.probability*.5);if(originalCampaignEventProbabilityValue(probability,services)<f(.01))probability.probability=0;}return success;}
export function getOriginalCampaignEventProbability(state,eventType,eventTarget,services={}){
 check(typeof eventType==='string'&&eventType.length>0,'Actual event type required');validateOriginalCampaignEventTarget(eventTarget);const key={eventType,target:eventTarget},existing=originalCampaignEventMapEntry(state.probabilities,key,services);if(existing)return existing.probability;
 const currentSpec=spec(eventType,services),instance=plugin(call(services,'createCampaignEventPlugin',currentSpec,eventTarget)),p={scope:'native-event-probability',objectRef:state.objectRef+':probability:'+state.nextProbabilitySerial,eventType,eventTarget,probability:0,primed:false,plugin:instance};state.nextProbabilitySerial=String(BigInt(state.nextProbabilitySerial)+1n);putOriginalCampaignEventMap(state.probabilities,key,p,services);return p;
}
export function getOriginalOngoingCampaignEvent(state,target,eventType,services){for(const event of state.ongoingEvents){if(target!==null&&!originalCampaignEventTargetEquals(target,call(services,'readCampaignEventTarget',event),services))continue;if(eventType===call(services,'readCampaignEventType',event))return event;}return null;}
export function countOriginalOngoingCampaignEvents(state,eventType,services){let count=0;for(const event of state.ongoingEvents)if(eventType===call(services,'readCampaignEventType',event))count++;return count;}
function targetOrToken(target,services){return target===null?validateOriginalCampaignEventTarget(call(services,'createCampaignEventTargetToken')):validateOriginalCampaignEventTarget(target);}
export function primeOriginalCampaignEvent(state,target,eventType,param=null,services={}){target=targetOrToken(target,services);const p=getOriginalCampaignEventProbability(state,eventType,target,services);if(!bool(call(services,'allowMultipleCampaignEventsForTarget',p.plugin))&&getOriginalOngoingCampaignEvent(state,p.eventTarget,p.eventType,services)!==null)return null;if(param!==null)call(services,'setCampaignEventParam',p.plugin,param);p.primed=true;return p.plugin;}
export function startOriginalCampaignEventPlugin(state,event,services){plugin(event);state.ongoingEvents.push(event);const key={eventType:call(services,'readCampaignEventType',event),target:call(services,'readCampaignEventTarget',event)};removeOriginalCampaignEventMap(state.probabilities,key,services);call(services,'setCampaignEventStartProbability',event,1);call(services,'startCampaignEventPlugin',event);}
export function startOriginalCampaignEvent(state,target,eventType,param=null,services={}){target=targetOrToken(target,services);const p=getOriginalCampaignEventProbability(state,eventType,target,services);if(!bool(call(services,'allowMultipleCampaignEventsForTarget',p.plugin))&&getOriginalOngoingCampaignEvent(state,p.eventTarget,p.eventType,services)!==null)return null;if(param!==null)call(services,'setCampaignEventParam',p.plugin,param);state.ongoingEvents.push(p.plugin);removeOriginalCampaignEventMap(state.probabilities,{eventType,target},services);call(services,'setCampaignEventStartProbability',p.plugin,1);call(services,'startCampaignEventPlugin',p.plugin);return p.plugin;}
const removeOngoing=(state,event)=>{const at=state.ongoingEvents.indexOf(event);if(at>=0)state.ongoingEvents.splice(at,1);};
export function endOriginalCampaignEvent(state,event,services){if(state.ongoingEvents.includes(event)){call(services,'cleanupCampaignEventPlugin',event);removeOngoing(state,event);}else{const key={eventType:call(services,'readCampaignEventType',event),target:call(services,'readCampaignEventTarget',event)};call(services,'cleanupCampaignEventPlugin',event);removeOriginalCampaignEventMap(state.probabilities,key,services);}}
function nextKey(state,warning){const index=warning?'currIndexForWarning':'currIndex',list=warning?'keyListForWarnings':'keyList';state[index]=(state[index]+1)|0;if(state[index]>=state[list].length){state[list]=originalCampaignEventMapKeys(state.probabilities);state.random.shuffleRandom??=createOriginalJavaRandom(originalJavaNextLong(state.random.newRandomSeeds));for(let size=state[list].length;size>1;size--){const at=originalJavaNextInt(state.random.shuffleRandom,size),last=size-1;[state[list][at],state[list][last]]=[state[list][last],state[list][at]];}state[index]=0;}if(!state[list].length)return null;check(state[index]>=0,'Native event key index overflow');return state[list][state[index]];}
function processEvent(state,services){const key=nextKey(state,false),p=key===null?null:originalCampaignEventMapEntry(state.probabilities,key,services)?.probability;if(!p||p.primed)return;const before=originalCampaignEventProbabilityValue(p,services),success=checkOriginalCampaignEventProbability(state,p,services),max=spec(p.eventType,services).maxOngoing,count=countOriginalOngoingCampaignEvents(state,p.eventType,services);if(success&&getOriginalOngoingCampaignEvent(state,p.eventTarget,p.eventType,services)===null&&(max<0||max>count)){state.ongoingEvents.push(p.plugin);call(services,'setCampaignEventStartProbability',p.plugin,before);call(services,'startCampaignEventPlugin',p.plugin);removeOriginalCampaignEventMap(state.probabilities,state.keyList[state.currIndex],services);}else if(originalCampaignEventProbabilityValue(p,services)<=0){call(services,'cleanupCampaignEventPlugin',p.plugin);removeOriginalCampaignEventMap(state.probabilities,state.keyList[state.currIndex],services);}}
function processWarning(state,services){const key=nextKey(state,true),p=key===null?null:originalCampaignEventMapEntry(state.probabilities,key,services)?.probability;if(!p||getOriginalOngoingCampaignEvent(state,p.eventTarget,p.eventType,services)!==null)return;const probability=originalCampaignEventProbabilityValue(p,services),kind=probability>=1?'likely':probability>f(.25)?'possible':null;if(kind!==null){const stage=call(services,'readCampaignEventWarningStage',p.plugin,kind),priority=call(services,'readCampaignEventWarningPriority',p.plugin,kind);call(services,'reportCampaignEventStage',p.plugin,stage,priority);}}
export function advanceOriginalCampaignEventManager(state,seconds,context,services){
 if(bool(context.paused))return;seconds=number(seconds);advanceOriginalCampaignInterval(state.tracker,number(call(services,'convertCampaignEventSecondsToDays',seconds)),()=>math(state));
 if(state.tracker.intervalElapsed){state.checkWarning=!state.checkWarning;if(state.checkWarning)processWarning(state,services);else processEvent(state,services);const period=number(services.readCampaignEventCheckPeriod?call(services,'readCampaignEventCheckPeriod'):R.eventCheckInterval),interval=f(period/Math.max(1,f(state.probabilities.entries.length*2)));setOriginalCampaignInterval(state.tracker,f(interval*.5),f(interval*1.5),()=>math(state));}
 const done=[];for(const event of [...state.ongoingEvents]){call(services,'advanceCampaignEventPlugin',event,seconds);if(bool(call(services,'isCampaignEventPluginDone',event)))done.push(event);}for(const event of done){call(services,'cleanupCampaignEventPlugin',event);removeOngoing(state,event);}
}
