/** Original encounter XP and post-battle sequencing. Reputation remains its separate dialog entry. */
import {encounterCheck as check,encounterCall as call,encounterBool as bool,encounterFloat as num} from './OriginalEncounterState.mjs';
import {originalBattleFleetMembers,originalBattleIsInvolved,originalBattleIsPlayerSide,originalBattleSideFor,originalBattlePlayerSide,originalBattlePrimary} from './OriginalCampaignBattle.mjs';
import {originalEncounterPlayerContribution,originalEncounterSnapshotFor} from './OriginalEncounterLoot.mjs';
import {originalFleetPointCost} from './OriginalFleetData.mjs';
import {originalEncounterSalvageRandom} from './OriginalEncounterEquipment.mjs';
import {originalJavaNextFloat,originalJavaNextDouble} from './OriginalJavaRandom.mjs';
import {originalExperienceSetting,originalExperienceFloatToLong,addOriginalCharacterXP,levelUpOriginalCharacterIfNeeded,spendOriginalCharacterStoryPoints,addOriginalOfficerXP} from './OriginalCharacterExperience.mjs';
import {originalEntityMemoryWithoutUpdate,originalCampaignMemoryBoolean,unsetOriginalCampaignMemory} from './OriginalCampaignMemory.mjs';
import {originalPersonMemoryWithoutUpdate} from './OriginalPersonAdvance.mjs';
import {resolveOriginalEconomyMutable} from './OriginalMarketEconomy.mjs';
import {setOriginalConstructedFleetVelocity} from './OriginalCampaignFleet.mjs';
import {setOriginalFleetNoEngaging} from './OriginalCampaignFleetAdvance.mjs';
const f=Math.fround,playerFleet=s=>call(s,'readBattlePlayerFleet'),commander=(fleet,s)=>call(s,'readBattleFleetCommander',fleet),isPlayer=fleet=>bool(fleet.isPlayerFleet);
function adjustedFP(member,s){const captain=call(s,'readEncounterCaptain',member);check(Number.isInteger(captain?.stats?.level),'Actual casualty captain level required');return f(originalFleetPointCost(member)*f(1+f(f(captain.stats.level)/5)));}
export function originalEncounterScuttlingBonus(member,services={}){const records=call(services,'readEncounterSModRecords');check(Array.isArray(records),'Actual playthrough S-mod log required');let points=0,xp=0;for(const record of records){if(member!==record.member||record.member===null)continue;check(Number.isInteger(record.spSpent),'Actual S-mod story points required');points=f(points+f(record.spSpent));xp=f(xp+f(num(record.bonusXPFractionGained)*f(record.spSpent)));}return points>0?[points,f(1-f(xp/points))]:[0,0];}
export function gainOriginalEncounterOfficerXP(state,side,xp,services={}){
 const max=Math.max(1,num(side.maxTimeDeployed)),count=Math.max(1,side.officerData.length);for(const row of side.officerData){check(row.person&&row.sourceFleet!==undefined,'Actual officer engagement record required');const fleet=row.sourceFleet;if(fleet===null||!isPlayer(fleet))continue;check(Array.isArray(fleet.officers),'Actual source officer roster required');const officer=fleet.officers.find(o=>o.person===row.person);if(!officer)continue;const fraction=Math.max(0,Math.min(1,f(num(row.timeDeployed)/max))),amount=originalExperienceFloatToLong(f(f(fraction*num(xp))/f(count))).toString();addOriginalOfficerXP(officer,amount,state.textPanelForXPGain,services);}
}
function gainForSides(state,side,enemy,s){
 let points=0,bonus=0;for(const loss of side.ownCasualties){if(!['DISABLED','DESTROYED'].includes(loss.status))continue;const [spent,mult]=originalEncounterScuttlingBonus(loss.member,s);points=f(points+spent);bonus=f(bonus+f(mult*spent));}
 if(bonus>0&&points>0){const stats=call(s,'readExperiencePlayerStats');stats.onlyAddBonusXPDoNotSpendStoryPoints=true;stats.bonusXPGainReason='，来自内置插件的舰船损失';spendOriginalCharacterStoryPoints(stats,1,bonus,state.textPanelForXPGain,s);stats.onlyAddBonusXPDoNotSpendStoryPoints=false;stats.bonusXPGainReason=null;}
 const fleet=playerFleet(s);let fp=0;for(const loss of enemy.ownCasualties)fp=f(fp+adjustedFP(loss.member,s));let xp=f(f(fp*250)*2);xp=f(xp*Math.max(1,num(state.difficulty)));xp=f(xp*originalEncounterPlayerContribution(state,s));xp=f(xp*originalExperienceSetting('xpGainMult',s));if(xp<=0)return;
 gainOriginalEncounterOfficerXP(state,side,xp,s);addOriginalCharacterXP(commander(fleet,s).stats,originalExperienceFloatToLong(xp).toString(),state.textPanelForXPGain,s);levelUpOriginalCharacterIfNeeded(commander(fleet,s).stats,state.textPanelForXPGain,s);state.xpGained=xp;
}
export function gainOriginalEncounterXP(state,services={}){if(state.sideData.length!==2)return;const b=state.battle;check(b,'Actual encounter Battle required');if(!originalBattleIsInvolved(b,playerFleet(services)))return;const [one,two]=state.sideData;if(originalBattleIsPlayerSide(b,originalBattleSideFor(b,one.fleet),services))gainForSides(state,one,two,services);else if(originalBattleIsPlayerSide(b,originalBattleSideFor(b,two.fleet),services))gainForSides(state,two,one,services);}
export function addOriginalEncounterPotentialOfficer(state,services={}){
 if(!state.engagedInHostilities||state.xpGained<=0||state.sideData.length!==2||!originalBattleIsInvolved(state.battle,playerFleet(services)))return;
 let [player,enemy]=state.sideData;if(originalBattleIsPlayerSide(state.battle,originalBattleSideFor(state.battle,enemy.fleet),services))[player,enemy]=[enemy,player];let destroyed=0;for(const loss of enemy.ownCasualties)destroyed=f(destroyed+adjustedFP(loss.member,services));destroyed=f(destroyed*originalEncounterPlayerContribution(state,services));for(const loss of player.ownCasualties){if(bool(loss.member.isAlly))continue;destroyed=f(destroyed+adjustedFP(loss.member,services));}
 let inFleet=0;for(const member of originalBattleFleetMembers(playerFleet(services),services))inFleet=f(inFleet+adjustedFP(member,services));const maxProb=originalExperienceSetting('maxOfficerPromoteProb',services),mult=originalExperienceSetting('officerPromoteProbMult',services),fleet=playerFleet(services),stats=commander(fleet,services).stats;check(stats.officerNumber,'Actual officer capacity stat required');const max=Math.trunc(resolveOriginalEconomyMutable(stats.officerNumber));check(Array.isArray(fleet.officers),'Actual officer roster required');let current=0;for(const officer of [...fleet.officers])if(!originalCampaignMemoryBoolean(originalPersonMemoryWithoutUpdate(officer.person),'$isMercenary',services.memoryServices))current++;
 let prob=f(f(destroyed/Math.max(1,inFleet))*mult);if(current>=max)prob=f(prob*f(.5));if(prob>maxProb)prob=maxProb;const random=originalEncounterSalvageRandom(state,services);if(bool(call(services,'readEncounterTutorialInProgress')))prob=0;
 if(originalJavaNextFloat(random)<prob){const intel=call(services,'createEncounterPromoteOfficerIntel',state.textPanelForXPGain);check(intel&&typeof intel==='object','Actual PromoteOfficerIntel required');call(services,'addEncounterPromoteOfficerIntel',intel,false,state.textPanelForXPGain);}
}
function resetAmmo(fleet,services){for(const member of originalBattleFleetMembers(fleet,services)){check(Array.isArray(member.status?.modules),'Actual member module status required');for(const module of member.status.modules){check(Object.hasOwn(module,'ammoState'),'Actual ammo state required');module.ammoState=null;}}}
export function forgetOriginalEncounterTransponder(fleet,services={}){const memory=originalEntityMemoryWithoutUpdate(fleet.campaign.entity);if(originalCampaignMemoryBoolean(memory,'$cfai_makeHostileWhileTOff',services.memoryServices)){const required=[...(memory.require.find(r=>r.key==='$cfai_makeHostileWhileTOff')?.req??[])];for(const key of required)unsetOriginalCampaignMemory(memory,key,services.memoryServices);}unsetOriginalCampaignMemory(memory,'$sawPlayerTransponderOff',services.memoryServices);unsetOriginalCampaignMemory(memory,'$sawPlayerTransponderOn',services.memoryServices);}
export function applyOriginalEncounterAfterBattleEffects(state,services={}){
 const winner=state.sideData.find(d=>!d.disengaged),loser=state.sideData.find(d=>d.disengaged),b=state.battle;
 if(!winner||!loser||!state.engagedInHostilities){resetAmmo(playerFleet(services),services);if(state.noHarryBecauseOfStation&&b!==null){const own=originalBattlePlayerSide(b,services),other=own===b.sideOne?b.sideTwo:own===b.sideTwo?b.sideOne:null,fleet=originalBattlePrimary(b,other,services);check(fleet,'Actual non-player primary required');const ai=fleet.campaign.ai;if(ai!==null&&!bool(call(services,'isBattleAICurrentAssignment',ai,'STANDING_DOWN',fleet)))call(services,'addBattleAIAssignmentAtStart',ai,'STANDING_DOWN',fleet,f(f(.5)+f(f(.5)*f(originalJavaNextDouble(services.globalRandom)))),null,fleet);}setOriginalFleetNoEngaging(playerFleet(services),3);return;}
 gainOriginalEncounterXP(state,services);addOriginalEncounterPotentialOfficer(state,services);const winners=originalEncounterSnapshotFor(state,winner.fleet),losers=originalEncounterSnapshotFor(state,loser.fleet);if(winners===null||losers===null)return;
 for(const fleets of [losers,winners])for(const fleet of fleets){resetAmmo(fleet,services);setOriginalConstructedFleetVelocity(fleet,0,0);/* javap confirms isPlayer || !isPlayer: native does not set noEngaging here. */if(isPlayer(fleet)||!isPlayer(fleet))continue;setOriginalFleetNoEngaging(fleet,3);}
 if(originalBattleIsPlayerSide(b,winners,services))for(const fleet of originalBattlePlayerSide(b,services)){if(!isPlayer(fleet))forgetOriginalEncounterTransponder(fleet,services);}
 b.playerInvolvementFraction=originalEncounterPlayerContribution(state,services);if(!state.isAutoresolve&&state.engagedInActualBattle){call(services,'reportBattleOccurred',originalBattlePrimary(b,winners,services),b);call(services,'reportBattleFinished',originalBattlePrimary(b,winners,services),b);}
 originalBattlePrimary(b,winners,services); // Preserve the original unused largestWinner getter visit.
 for(const fleets of [losers,winners])for(const fleet of fleets)if(originalBattleFleetMembers(fleet,services).length===0)call(services,'despawnEncounterFleet',fleet,'DESTROYED_BY_BATTLE',b);
 for(const fleet of [...b.sideOne,...b.sideTwo]){const ai=fleet.campaign.ai;if(ai!==null&&bool(call(services,'isEncounterModularAI',ai)))call(services,'forceEncounterTargetReEval',ai);}
}
