/** CampaignEngine's timed legacy listeners share the world's existing event roster. */
import {requireThat} from '../core/Values.mjs';
import {createOriginalTimeoutTracker,validateOriginalTimeoutTracker,originalTimeoutContains,originalTimeoutItems,setOriginalTimeout,removeOriginalTimeout,advanceOriginalTimeoutTracker} from './OriginalTimeoutTracker.mjs';
const check=(ok,message)=>requireThat(ok,'UNSUPPORTED_NATIVE_LISTENER_TIMEOUTS',message);
const listener=item=>check(item&&typeof item.objectRef==='string','Actual listener identity required');
export function createOriginalCampaignListenerTimeouts(listeners){check(Array.isArray(listeners?.timed)&&listeners.timed.length===0,'New empty timed listener roster required; historical timeouts cannot be inferred');return validateOriginalCampaignListenerTimeouts({scope:'native-campaign-listener-timeouts',listeners,tracker:createOriginalTimeoutTracker()},listeners);}
export function validateOriginalCampaignListenerTimeouts(state,listeners=state?.listeners){check(state?.scope==='native-campaign-listener-timeouts'&&listeners&&state.listeners===listeners&&['saved','transient','timed'].every(k=>Array.isArray(listeners[k])),'Actual shared campaign listener timeout state required');validateOriginalTimeoutTracker(state.tracker);const items=originalTimeoutItems(state.tracker);check(items.length===listeners.timed.length&&items.every((item,i)=>item===listeners.timed[i]),'Timed listener projection lost tracker order or identity');for(const item of [...listeners.saved,...listeners.transient,...items])listener(item);return state;}
const sync=state=>{state.listeners.timed.splice(0,state.listeners.timed.length,...originalTimeoutItems(state.tracker));};
export function addOriginalCampaignListenerWithTimeout(state,item,days){validateOriginalCampaignListenerTimeouts(state);listener(item);if(!originalTimeoutContains(state.tracker,item))setOriginalTimeout(state.tracker,item,days);sync(state);}
export function removeOriginalCampaignListener(state,item){validateOriginalCampaignListenerTimeouts(state);for(const list of [state.listeners.saved,state.listeners.transient]){const index=list.indexOf(item);if(index>=0)list.splice(index,1);}removeOriginalTimeout(state.tracker,item);sync(state);}
export function advanceOriginalCampaignListenerTimeouts(state,days){validateOriginalCampaignListenerTimeouts(state);advanceOriginalTimeoutTracker(state.tracker,days);sync(state);}
