import type {OriginalJavaRandomState} from './OriginalJavaRandom.mjs';
import type {OriginalCampaignInterval} from './OriginalCampaignInterval.mjs';
import type {OriginalCampaignEventTarget,OriginalCampaignEventKey,OriginalCampaignEventKeyServices,OriginalCampaignEventMap} from './OriginalCampaignEventKeys.mjs';
export interface OriginalCampaignEventPlugin {objectRef:string}
export interface OriginalCampaignEventSpec {id:string;pluginClass:string;image:string|null;probabilityMult:number;maxOngoing:number}
export const ORIGINAL_CAMPAIGN_EVENTS:Readonly<{eventCheckInterval:number;specs:OriginalCampaignEventSpec[]}>;
export interface OriginalCampaignEventProbability {scope:'native-event-probability';objectRef:string;eventType:string;eventTarget:OriginalCampaignEventTarget;probability:number;primed:boolean;plugin:OriginalCampaignEventPlugin}
export interface OriginalCampaignEventManager {scope:'native-campaign-event-manager';objectRef:string;probabilities:OriginalCampaignEventMap<OriginalCampaignEventProbability>;ongoingEvents:OriginalCampaignEventPlugin[];tracker:OriginalCampaignInterval;keyList:OriginalCampaignEventKey[];currIndex:number;keyListForWarnings:OriginalCampaignEventKey[];currIndexForWarning:number;checkWarning:boolean;nextProbabilitySerial:string;random:{scope:'web-campaign-event-random-branch';binding:'explicit'|'runtime-shared';mathRandom:OriginalJavaRandomState;newRandomSeeds:OriginalJavaRandomState;shuffleRandom:OriginalJavaRandomState|null}}
export interface OriginalCampaignEventServices extends OriginalCampaignEventKeyServices {
 readCampaignEventSpec?(eventType:string):OriginalCampaignEventSpec;readCampaignEventCheckPeriod?():number;
 createCampaignEventPlugin?(spec:OriginalCampaignEventSpec,target:OriginalCampaignEventTarget):OriginalCampaignEventPlugin;createCampaignEventTargetToken?():OriginalCampaignEventTarget;
 readCampaignEventType?(plugin:OriginalCampaignEventPlugin):string;readCampaignEventTarget?(plugin:OriginalCampaignEventPlugin):OriginalCampaignEventTarget;
 setCampaignEventParam?(plugin:OriginalCampaignEventPlugin,param:unknown):void;setCampaignEventStartProbability?(plugin:OriginalCampaignEventPlugin,probability:number):void;allowMultipleCampaignEventsForTarget?(plugin:OriginalCampaignEventPlugin):boolean;
 startCampaignEventPlugin?(plugin:OriginalCampaignEventPlugin):void;advanceCampaignEventPlugin?(plugin:OriginalCampaignEventPlugin,seconds:number):void;isCampaignEventPluginDone?(plugin:OriginalCampaignEventPlugin):boolean;cleanupCampaignEventPlugin?(plugin:OriginalCampaignEventPlugin):void;
 readCampaignEventWarningStage?(plugin:OriginalCampaignEventPlugin,kind:'likely'|'possible'):string|null;readCampaignEventWarningPriority?(plugin:OriginalCampaignEventPlugin,kind:'likely'|'possible'):string|null;reportCampaignEventStage?(plugin:OriginalCampaignEventPlugin,stage:string|null,priority:string|null):void;
 convertCampaignEventSecondsToDays?(seconds:number):number;
}
export function createOriginalCampaignEventManager(objectRef:string,mathRandom:OriginalJavaRandomState,newRandomSeeds:OriginalJavaRandomState):OriginalCampaignEventManager;
export function validateOriginalCampaignEventManager(state:OriginalCampaignEventManager,related?:OriginalCampaignEventPlugin[]):OriginalCampaignEventManager;
export function originalCampaignEventProbabilityValue(probability:OriginalCampaignEventProbability,services?:OriginalCampaignEventServices):number;
export function setOriginalCampaignEventProbability(probability:OriginalCampaignEventProbability,value:number):void;
export function changeOriginalCampaignEventProbability(probability:OriginalCampaignEventProbability,amount:number):void;
export function setOriginalCampaignEventProbabilityAfterMult(probability:OriginalCampaignEventProbability,value:number,services?:OriginalCampaignEventServices):void;
export function checkOriginalCampaignEventProbability(state:OriginalCampaignEventManager,probability:OriginalCampaignEventProbability,services?:OriginalCampaignEventServices):boolean;
export function getOriginalCampaignEventProbability(state:OriginalCampaignEventManager,eventType:string,target:OriginalCampaignEventTarget,services?:OriginalCampaignEventServices):OriginalCampaignEventProbability;
export function getOriginalOngoingCampaignEvent(state:OriginalCampaignEventManager,target:OriginalCampaignEventTarget|null,eventType:string,services:OriginalCampaignEventServices):OriginalCampaignEventPlugin|null;
export function countOriginalOngoingCampaignEvents(state:OriginalCampaignEventManager,eventType:string,services:OriginalCampaignEventServices):number;
export function primeOriginalCampaignEvent(state:OriginalCampaignEventManager,target:OriginalCampaignEventTarget|null,eventType:string,param:unknown,services:OriginalCampaignEventServices):OriginalCampaignEventPlugin|null;
export function startOriginalCampaignEventPlugin(state:OriginalCampaignEventManager,event:OriginalCampaignEventPlugin,services:OriginalCampaignEventServices):void;
export function startOriginalCampaignEvent(state:OriginalCampaignEventManager,target:OriginalCampaignEventTarget|null,eventType:string,param:unknown,services:OriginalCampaignEventServices):OriginalCampaignEventPlugin|null;
export function endOriginalCampaignEvent(state:OriginalCampaignEventManager,event:OriginalCampaignEventPlugin,services:OriginalCampaignEventServices):void;
export function advanceOriginalCampaignEventManager(state:OriginalCampaignEventManager,seconds:number,context:{paused:boolean},services:OriginalCampaignEventServices):void;
