import type {OriginalEncounterState} from './OriginalEncounterState.mjs';
import type {OriginalFleetEncounterServices,OriginalEncounterFleetResult,OriginalEncounterEngagementResult} from './OriginalFleetEncounterContext.mjs';
import type {OriginalNativeFleetMember} from './OriginalFleetData.mjs';
import type {OriginalConstructedCampaignFleet} from './OriginalCampaignFleet.mjs';
import type {OriginalPlayerCargo} from './OriginalPlayerEconomy.mjs';
type State=OriginalEncounterState;type Services=OriginalFleetEncounterServices;type Member=OriginalNativeFleetMember;type Fleet=OriginalConstructedCampaignFleet;type Result=OriginalEncounterFleetResult;
export function originalEncounterCargo(fleet:Fleet,services?:Services):OriginalPlayerCargo;
export function originalEncounterDeployCost(state:State,member:Member,services?:Services):number;
export function removeOriginalEncounterShip(state:State,fleet:Fleet,member:Member,services?:Services):void;
export function applyOriginalEncounterCR(state:State,result:Result,services?:Services):void;
export function originalEncounterCrewLossFraction(state:State,member:Member|null,result:Result|null,hullFraction:number,hullDamage:number,services?:Services):number;
export function applyOriginalEncounterCrewLosses(state:State,result:Result,playerInvolved:boolean,services?:Services):void;
export function applyOriginalEncounterResultsToFleets(state:State,result:OriginalEncounterEngagementResult,services?:Services):void;
export function recoverOriginalEncounterCrew(state:State,fleet:Fleet,services?:Services):void;
export function recoverOriginalEncounterVictoryCR(state:State,winner:Result,loser:Result,services?:Services):number;
export function fixOriginalEncounterFighters(state:State,result:Result,services?:Services):void;
