import { originalCargoGesturesProvider } from './rules/OriginalCargoGestures.mjs';
import type { cooperativeCargoProvider } from './rules/CooperativeCargo.mjs';
import type { OriginalOrbitMethods } from './rules/OriginalOrbits.mjs';
import type { originalMarketProvider } from './rules/OriginalMarket.mjs';
import type { OriginalCalendarMethods } from './rules/OriginalCalendar.mjs';
import type { TravelMethods } from './rules/OriginalTravel.mjs';
import type { resolveOriginalFleetStats } from './rules/OriginalFleetStats.mjs';
import type { advanceOriginalFleet } from './rules/OriginalLogisticsStep.mjs';
import type { CompiledRuleset } from './Types.js';
import type { quoteOriginalLogistics } from './rules/OriginalLogistics.mjs';
export function createReferenceRuleset(): CompiledRuleset & { services: { cargoGestures: typeof originalCargoGesturesProvider.methods; cargo: typeof cooperativeCargoProvider.methods; spaceMotion: OriginalOrbitMethods; market: typeof originalMarketProvider.methods; calendar: OriginalCalendarMethods; travel: TravelMethods; fleetStats: { resolve: typeof resolveOriginalFleetStats }; logistics: { quote: typeof quoteOriginalLogistics; advance: typeof advanceOriginalFleet } } };
