import type {OriginalFactionEquipment,OriginalFactionEquipmentKind,OriginalTimedFactionEquipmentKind,OriginalFactionEquipmentServices} from '../../../src/campaign/rules/OriginalFactionEquipment.mjs';
import type {OriginalMarketFrameState,OriginalMarketFrameServices} from '../../../src/campaign/rules/OriginalMarketFrame.mjs';
import type {OriginalProductionLifecycleState,OriginalProductionLifecycleRow} from '../../../src/campaign/rules/OriginalProductionLifecycle.mjs';
export interface NativeProductionFrameServices {colonyDebug?:boolean;memoryServices?:OriginalCampaignMemoryServices;militaryServices?:NonNullable<Parameters<NativeLiveEconomyDraft['advanceMilitaryIndustry']>[3]>}
export type NativeCivicFrameServices=NativeProductionFrameServices & {readMaxOutposts?():number};
export type NativeResourceFrameServices=NativeProductionFrameServices & import('../../../src/campaign/rules/OriginalResourceLifecycle.mjs').OriginalResourceVisualServices;
export type NativeMarketFrameServices=OriginalMarketFrameServices & {resourceServices?:NativeResourceFrameServices;civicServices?:NativeCivicFrameServices;productionServices?:NativeProductionFrameServices;readMaxOutposts?():number;marketMemoryServices?:OriginalCampaignMemoryServices;personMemoryServices?:OriginalCampaignMemoryServices;militaryServices?:NonNullable<Parameters<NativeLiveEconomyDraft['advanceMilitaryIndustry']>[3]>};
import type {OriginalCampaignUIDataFrame,OriginalCampaignUIDataServices} from '../../../src/campaign/rules/OriginalCampaignUIData.mjs';
import type {OriginalCampaignPlanet,OriginalCampaignPlanetInput,OriginalCampaignPlanetConstructionServices} from '../../../src/campaign/rules/OriginalCampaignPlanet.mjs';
import type {OriginalCampaignPlanetFrameContext,OriginalCampaignPlanetFrameServices,advanceOriginalCampaignPlanetFrame} from '../../../src/campaign/rules/OriginalCampaignPlanetFrame.mjs';
export type NativePlanetServices=import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorldServices & Pick<OriginalCampaignPlanetConstructionServices,'readPlanetSpec'>;
import type {OriginalNormalSpaceBackground} from '../../../src/campaign/rules/OriginalCampaignBackground.mjs';
import type {OriginalCampaignEventManager,OriginalCampaignEventPlugin,OriginalCampaignEventProbability,OriginalCampaignEventServices} from '../../../src/campaign/rules/OriginalCampaignEvents.mjs';
import type {OriginalCampaignEventTarget} from '../../../src/campaign/rules/OriginalCampaignEventKeys.mjs';
import type {OriginalBaseCampaignEvent,OriginalBaseCampaignEventServices} from '../../../src/campaign/rules/OriginalBaseCampaignEvent.mjs';
export type NativeCampaignEventServices=OriginalCampaignEventServices & OriginalBaseCampaignEventServices;
import type {OriginalIntelManager,OriginalIntelPlugin,OriginalIntelManagerServices} from '../../../src/campaign/rules/OriginalIntelManager.mjs';
import type {OriginalBaseIntelServices} from '../../../src/campaign/rules/OriginalBaseIntel.mjs';
import type {OriginalIntelSpatialServices} from '../../../src/campaign/rules/OriginalIntelCommunications.mjs';
export type NativeIntelServices=OriginalIntelManagerServices & OriginalIntelSpatialServices & OriginalBaseIntelServices & {readIntelPlayerFleet?():object|null};
import type {OriginalImportantPeople,OriginalImportantPeopleServices} from '../../../src/campaign/rules/OriginalImportantPeople.mjs';
import type {OriginalCampaignListenerTimeouts} from '../../../src/campaign/rules/OriginalCampaignListenerTimeouts.mjs';
import type {OriginalCampaignMemory,OriginalCampaignMemoryServices} from '../../../src/campaign/rules/OriginalCampaignMemory.mjs';
import type {OriginalFleetWorldListener} from '../../../src/campaign/rules/OriginalFleetWorld.mjs';
import type {OriginalFactionFrame,OriginalFactionFrameServices} from '../../../src/campaign/rules/OriginalFactionFrame.mjs';
import type {OriginalFactionProduction,OriginalProductionItemType,OriginalProductionItemServices} from '../../../src/campaign/rules/OriginalFactionProduction.mjs';
import type {OriginalNavigationServices,OriginalFollowTargetResult} from '../../../src/campaign/rules/OriginalCampaignNavigation.mjs';
import type {OriginalCargoPodsObserverPresentation,OriginalCargoPodsObserverContext,OriginalCargoPodsRenderContext,OriginalCargoPodsPresentationServices,OriginalObserverCargoPodsLayers,advanceOriginalCargoPodsObserver} from '../../../src/campaign/rules/OriginalCargoPodsPresentation.mjs';
import type {OriginalCargoPodsFrameServices,OriginalCargoPodsFrameContext,advanceOriginalCargoPodsFrame} from '../../../src/campaign/rules/OriginalCargoPodsFrame.mjs';
import type {OriginalCargoPods} from '../../../src/campaign/rules/OriginalCargoPods.mjs';
export type NativeCargoPodsServices=import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorldServices & import('../../../src/campaign/rules/OriginalNativeCargo.mjs').OriginalNativeCargoServices & {readCustomEntityLightSource?(location:import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetLocationRegistry):object|null};
import type {OriginalLootCargoTransaction,OriginalLootCargoAction,NativeLootCargoView} from '../../../src/campaign/rules/OriginalLootCargoTransaction.mjs';
import type {OriginalFleetInteractionAftermath,OriginalFleetInteractionProgress,OriginalFleetAftermathConfig,OriginalFleetInteractionDialog,OriginalFleetInteractionServices} from '../../../src/campaign/rules/OriginalFleetInteractionAftermath.mjs';
import type {OriginalFactionRelations,OriginalFactionRelation} from '../../../src/campaign/rules/OriginalRelationships.mjs';
import type {OriginalReputationServices,OriginalReputationResult} from '../../../src/campaign/rules/OriginalCoreReputation.mjs';
import type {OriginalFleetEncounterServices,OriginalFleetEncounterContext} from '../../../src/campaign/rules/OriginalFleetEncounterContext.mjs';
import type {OriginalEncounterState} from '../../../src/campaign/rules/OriginalEncounterState.mjs';
export interface NativeRetainedEncounter {encounterId:string;ownerFleet:import('../../../src/campaign/rules/OriginalCampaignFleet.mjs').OriginalConstructedCampaignFleet;context:OriginalEncounterState;aftermath:OriginalFleetInteractionAftermath|null;lootTransaction:OriginalLootCargoTransaction|null}
export interface NativeRetainedEncounters {scope:'web-retained-native-encounters';serial:number;entries:NativeRetainedEncounter[]}
import type {OriginalBattleAutoresolver,OriginalBattleEncounterContext,OriginalBattleEngagementResult} from '../../../src/campaign/rules/OriginalBattleAutoresolver.mjs';
import type {OriginalBattleLifecycleServices} from '../../../src/campaign/rules/OriginalCampaignBattleLifecycle.mjs';
import type {OriginalBattleFrameContext} from '../../../src/campaign/rules/OriginalCampaignBattleFrame.mjs';
import type {OriginalCampaignBattle,OriginalBattleSide,OriginalCampaignBattleServices} from '../../../src/campaign/rules/OriginalCampaignBattle.mjs';
import type {OriginalLocationEncounterContext,OriginalLocationEncounterServices,OriginalLocationEncounterResult} from '../../../src/campaign/rules/OriginalLocationEncounters.mjs';
import type {OriginalLocationFrame,OriginalLocationFrameContext,OriginalLocationFrameServices,advanceOriginalLocationFrame,advanceOriginalLocationEvenIfPaused} from '../../../src/campaign/rules/OriginalLocationFrame.mjs';
import type {OriginalFleetFrameServices} from '../../../src/campaign/rules/OriginalCampaignFleetFrame.mjs';
export type NativeLocationFrameServices=OriginalLocationFrameServices & OriginalFleetFrameServices & OriginalFleetEncounterServices & OriginalCargoPodsFrameServices & OriginalCampaignPlanetFrameServices;
import type {OriginalCampaignEngineState,OriginalCampaignEngineContext,OriginalCampaignEngineServices,advanceOriginalCampaignEngine} from '../../../src/campaign/rules/OriginalCampaignEngine.mjs';
import type {OriginalFleetObserverPresentation,OriginalObserverFrameContext,OriginalObserverRenderContext,OriginalObserverFleetLayers} from '../../../src/campaign/rules/OriginalFleetPresentation.mjs';
import type { DeepReadonly } from '../../../src/campaign/Types.js';
import type { EconomyBonus, EconomyMutable } from '../../../src/campaign/rules/OriginalMarketEconomy.mjs';
import type { OriginalIndustryCommodityEntry } from '../../../src/campaign/rules/OriginalIndustryCommodityPass.mjs';
import type { OriginalCommodityCacheEntry } from '../../../src/campaign/rules/OriginalCommodityCache.mjs';
import type { NativeSaveEconomyCapture, NativeSavedStat } from '../../../scripts/lib/campaign-native-save.mjs';
import type { OriginalIndustryFinances, OriginalIndustryFinanceResult } from '../../../src/campaign/rules/OriginalMarketFinance.mjs';
import type { OriginalPopulationStabilityResult } from '../../../src/campaign/rules/OriginalMarketStability.mjs';
import type { OriginalIndustryCommodityPassInput } from '../../../src/campaign/rules/OriginalIndustryCommodityPass.mjs';
import type { OriginalLiveIndustryEconomicMarket, OriginalLiveIndustryEffectsResult } from '../../../src/campaign/rules/OriginalLiveIndustryEffects.mjs';
import type { OriginalConditionPhaseState, OriginalConditionPhaseResult } from '../../../src/campaign/rules/OriginalConditionPhase.mjs';
import type { OriginalGovernedSkillState, OriginalGovernedSkillsResult } from '../../../src/campaign/rules/OriginalGovernedSkills.mjs';
import type { projectNativeConditionAttachments } from './ConditionRestore.mjs';
export interface NativeLiveDemand {objectRef:string;demandClass:string;state:EconomyMutable}
export interface NativeLiveCommodity {
 demand:NativeLiveDemand;stockpile:number;greed:EconomyMutable;playerDemandMod:EconomyBonus;playerSupplyMod:EconomyBonus;
 demandPrice:import('../../../src/campaign/rules/OriginalCommodityClassPricing.mjs').OriginalClassPriceCalculator|null;
 supplyPrice:import('../../../src/campaign/rules/OriginalCommodityClassPricing.mjs').OriginalClassPriceCalculator|null;
 lastPriceUpdate:{month:number;phase:import('../../../src/campaign/rules/OriginalMarketEconomy.mjs').EconomyPricePass['phase'];triggerCommodityId:string}|null;
 commodityId:string;maxSupply:number;maxDemand:number;supplyLegal:boolean;demandLegal:boolean;
 available:EconomyMutable;tradeMod:EconomyMutable;tradeModPlus:EconomyMutable;tradeModMinus:EconomyMutable;
 temporary:Record<'available'|'tradeMod'|'tradeModPlus'|'tradeModMinus',NativeSavedStat['temporary']>;
}
export interface NativeLiveMarket extends OriginalLiveIndustryEconomicMarket {
 nativeFrame?:OriginalMarketFrameState;
 resourceLifecycle:import('../../../src/campaign/rules/OriginalResourceLifecycle.mjs').OriginalResourceLifecycleState|null;
 resourcePlanetContext:{planetType:string|null;planetEntityRef:string|null}|null;
 productionLifecycle:OriginalProductionLifecycleState|null;
 civicLifecycle:import('../../../src/campaign/rules/OriginalCivicLifecycle.mjs').OriginalCivicLifecycleState|null;
 civicAdminInputs:import('../../../src/campaign/rules/OriginalCharacterIndustryStats.mjs').OriginalAdministratorIndustryInputs|null;
 civicPortItemContext:import('../../../src/campaign/rules/OriginalPortItems.mjs').OriginalPortItemContext|null;
 industryLifecycle:import('../../../src/campaign/rules/OriginalMilitaryLifecycle.mjs').OriginalMilitaryLifecycleState|null;
 personnel?:import('../../../src/campaign/rules/OriginalMarketPersonnel.mjs').OriginalMarketPersonnel;
 slipstreamDetection?:import('../../../src/campaign/rules/OriginalHyperspaceTopography.mjs').OriginalSlipstreamDetection|null;
 name:string;
 economyBonuses:Record<string,EconomyBonus>|null;
 retail:import('../../../scripts/lib/campaign-native-save.mjs').NativeOpenRetailCapture|null;
 demandClasses:Record<string,NativeLiveDemand>;supplyPriceMod:EconomyBonus;demandPriceMod:EconomyBonus;
 conditionContextByModId:Record<string,import('../../../src/campaign/rules/OriginalConditionPhase.mjs').OriginalConditionPhaseContext>;
 conditionObjectRefs:Record<string,string>;
 churchContext:import('../../../scripts/lib/campaign-native-save.mjs').NativeGrowthMarketCapture['church'];
 constructionQueue:string[];
 constructionQueueState:import('../../../src/campaign/rules/OriginalConstructionQueue.mjs').OriginalConstructionQueueState|null;
 buildAdmission:{tags:string[]|null}|null;
 population:import('../../../src/campaign/rules/OriginalPopulation.mjs').OriginalPopulationComposition|null;
 immigrationModifiers:import('../../../src/campaign/rules/OriginalColonyEnvironment.mjs').OriginalImmigrationObjectLists|null;
 incoming:import('../../../src/campaign/rules/OriginalImmigration.mjs').OriginalImmigrationResult['incoming']|null;
 incentives:{on:boolean;credits:number}|null;maxMarketSize:EconomyBonus;adminAiCoreId:string|null;
 conditionState:OriginalConditionPhaseState;governedState:OriginalGovernedSkillState|null;conditionAttachments:ReturnType<typeof projectNativeConditionAttachments>|null;
 marketId:string;objectRef:string;factionId:string;econGroup:string|null;size:number;hidden:boolean;playerOwned:boolean;freePort:boolean;
 location:{x:number;y:number};factionIllegalCommodityIds:string[];incomeMult:EconomyMutable;upkeepMult:EconomyMutable;accessibility:EconomyBonus;
 previousStability:number;adminIsPlayer:boolean|null;conditions:OriginalIndustryCommodityPassInput['conditions'];stability:EconomyMutable;stabilityTemporary:NativeSavedStat['temporary'];finances:OriginalIndustryFinances[];
 industries:OriginalIndustryCommodityEntry[];commodities:Record<string,NativeLiveCommodity>;
}
export interface NativeScheduledEconomyPass {scope:'shared-scheduled-economic-pass-only';status:import('../../../src/campaign/rules/OriginalEconomyTasks.mjs').OriginalEconomyTaskStatus;counts:{conditionPasses:number;industryPasses:number;networkRebuilds:number;priceUpdates:number;populationAdvances:number;commodityCallbacks:number;finishCallbacks:number};readyForAuthority:false}
export interface NativeLiveMarketEffects {scope:'shared-offline-market-economic-effects-only';marketId:string;conditionExecution:OriginalConditionPhaseResult['execution'];governedExecution:OriginalGovernedSkillsResult['execution'];industries:OriginalLiveIndustryEffectsResult;readyForAuthority:false}
export type NativePersonnelDependencies=import('../../../src/campaign/rules/OriginalPlayerEconomy.mjs').OriginalPlayerEconomyDependencies & Partial<Pick<import('../../../src/campaign/rules/OriginalMonthlyReport.mjs').OriginalCoreEconomyRuntime,'isTutorialInProgress'|'readFleetPayroll'|'readAdministrators'>>;
export type NativeDModServices=import('../../../src/campaign/rules/OriginalDModManager.mjs').OriginalDModServices & import('../../../src/campaign/rules/OriginalGenericPlugins.mjs').OriginalGenericPluginServices<import('../../../src/campaign/rules/OriginalDModManager.mjs').OriginalDModAdderParams>;
export type NativeFleetInflaterServices=import('../../../src/campaign/rules/OriginalFleetInflater.mjs').OriginalFleetInflaterServices & Partial<import('../../../src/campaign/rules/OriginalFleetInflater.mjs').OriginalCampaignInflationServices> & Pick<import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorldServices,'reportFleetInflatedToListener'> & import('../../../src/campaign/rules/OriginalInflaterAutofitDelegate.mjs').OriginalInflaterAutofitDelegateServices & {dmodServices?:NativeDModServices;emptyVariantServices?:import('../../../src/campaign/rules/OriginalEmptyVariants.mjs').OriginalVariantModuleServices<import('../../../src/campaign/rules/OriginalStorage.mjs').OriginalStorageVariant>;hullmodItemServices?:import('../../../src/campaign/rules/OriginalHullmodItems.mjs').OriginalHullmodItemServices;playerHullmodServices?:import('../../../src/campaign/rules/OriginalPlayerHullmods.mjs').OriginalPlayerHullmodServices;factionEquipmentServices?:import('../../../src/campaign/rules/OriginalFactionEquipment.mjs').OriginalFactionEquipmentServices;autofitServices?:import('../../../src/campaign/rules/OriginalCoreAutofit.mjs').OriginalCoreAutofitServices;memberServices?:Parameters<NativeLiveEconomyDraft['bindFleetRoster']>[1];fleetServices?:Parameters<NativeLiveEconomyDraft['bindFleetRoster']>[2]};
export type NativeModularFleetAIServices=Partial<import('../../../src/campaign/rules/OriginalModularFleetAI.mjs').OriginalModularFleetAIConstructionServices> & {pluginServices?:import('../../../src/campaign/rules/OriginalCampaignPluginPicks.mjs').OriginalCampaignPickServices<import('../../../src/campaign/rules/OriginalModularFleetAI.mjs').OriginalFleetAIModule>};
export interface NativeNamedFleetFactoryServices {personServices?:Parameters<NativeLiveEconomyDraft['createNativeEmptyFleet']>[3];aiServices?:NativeModularFleetAIServices}
export type NativeCustomProductionDependencies=Partial<import('../../../src/campaign/rules/OriginalCustomProduction.mjs').OriginalCustomProductionServices<NativeLiveMarket>> & {industryServices?:import('../../../src/campaign/rules/OriginalIndustryProductionCargo.mjs').OriginalIndustryProductionServices;fleetFactoryServices?:NativeNamedFleetFactoryServices;inflaterServices?:NativeFleetInflaterServices;intelServices?:NativeIntelServices;devMode?:boolean;weaponsHaveCost?:boolean;fleetServices?:Parameters<NativeLiveEconomyDraft['bindFleetRoster']>[2];memberServices?:Parameters<NativeLiveEconomyDraft['bindFleetRoster']>[1]};
export type NativeSettlementDependencies=NativePersonnelDependencies & import('../../../src/campaign/rules/OriginalStorage.mjs').OriginalStorageDependencies & Partial<Pick<import('../../../src/campaign/rules/OriginalMonthlyReport.mjs').OriginalCoreEconomyRuntime,'doCustomProduction'>> & {readIndustryName?(marketId:string,industryId:string):string;customProduction?:NativeCustomProductionDependencies} & Partial<Pick<import('../../../src/campaign/rules/OriginalEconomyNotifications.mjs').OriginalEconomyNotificationRuntime,'hasPlayerFleet'|'readPlayerLevel'|'readFleetCargoStat'|'readFleetDeploymentPoints'>>;
export type NativeEconomyFrameOptions=({notifications:import('../../../src/campaign/rules/OriginalMarketEconomySchedule.mjs').OriginalEconomyNotificationRuntime;settlement?:never}|{settlement:NativeSettlementDependencies;notifications?:never}) & {readMaxOutposts?:()=>number;nowSeconds?:()=>number};
/** Single transaction draft; only trusted native callback adapters may mutate market handles. Discard after any failed operation. */
export interface NativeFleetGenerationServices {fleetWorld:import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorld|null;towCableState:import('../../../src/campaign/rules/OriginalTowCable.mjs').OriginalTowCablePersistentEntry|null;personFactory:import('../../../src/campaign/rules/OriginalFactionPersons.mjs').OriginalFactionPersonFactory|null;dataFactory:import('../../../src/campaign/rules/OriginalFleetDataFactory.mjs').OriginalFleetDataFactory|null;composition:import('../../../src/campaign/rules/OriginalFleetComposition.mjs').OriginalFleetCompositionState|null;memberFactory:import('../../../src/campaign/rules/OriginalFleetMembers.mjs').OriginalFleetMemberFactory|null;rosters:import('../../../src/campaign/rules/OriginalFleetRoster.mjs').OriginalFleetRosterState|null;scope:'web-native-fleet-services';doctrineCapture:import('../../../src/campaign/rules/OriginalFactionDoctrine.mjs').OriginalFactionDoctrineCapture;doctrines:import('../../../src/campaign/rules/OriginalFactionDoctrine.mjs').OriginalFactionDoctrines|null;shipSelectionCapture:import('../../../src/campaign/rules/OriginalShipSelection.mjs').OriginalShipSelectionCapture|null;shipSelection:import('../../../src/campaign/rules/OriginalShipSelection.mjs').OriginalShipSelectionState|null;random:import('../../../src/campaign/rules/OriginalJavaRandom.mjs').OriginalPatrolBranchRandom}
export class NativeLiveEconomyDraft {
 factionDoctrine(factionId:string):import('../../../src/campaign/rules/OriginalFactionDoctrine.mjs').OriginalFactionDoctrine;
 shipSelectionState():import('../../../src/campaign/rules/OriginalShipSelection.mjs').OriginalShipSelectionState;
 pickFleetShipsForRole(factionId:string,roleId:string|null,params:import('../../../src/campaign/rules/OriginalShipSelection.mjs').OriginalShipPickParams,random?:import('../../../src/campaign/rules/OriginalJavaRandom.mjs').OriginalJavaRandomState|null,filter?:((variantId:string)=>boolean)|null):import('../../../src/campaign/rules/OriginalShipSelection.mjs').OriginalShipRolePick[];
 fleetShipRoleAvailability(factionId:string,roleId:string,mode:import('../../../src/campaign/rules/OriginalShipSelection.mjs').OriginalShipPickMode):{count:number;weight:number};
 clearFleetShipRoleCache(factionId:string):void;
 fleetMemberFactoryState():import('../../../src/campaign/rules/OriginalFleetMembers.mjs').OriginalFleetMemberFactory;
 createFleetMember(specId:string,type?:'SHIP'|'FIGHTER_WING',plugins?:import('../../../src/campaign/rules/OriginalMemberEffects.mjs').OriginalMemberEffectPlugins):import('../../../src/campaign/rules/OriginalFleetMembers.mjs').OriginalCreatedFleetMember;
 pickFleetShipName(naming:import('../../../src/campaign/rules/OriginalFleetMembers.mjs').OriginalFleetNaming,member:import('../../../src/campaign/rules/OriginalFleetMembers.mjs').OriginalCreatedFleetMember,random:import('../../../src/campaign/rules/OriginalJavaRandom.mjs').OriginalJavaRandomState|null):string;
 bindFleetMemberConstruction(naming:import('../../../src/campaign/rules/OriginalFleetMembers.mjs').OriginalFleetNaming|null,plugins?:import('../../../src/campaign/rules/OriginalMemberEffects.mjs').OriginalMemberEffectPlugins):ReturnType<typeof import('../../../src/campaign/rules/OriginalFleetMembers.mjs').originalFleetMemberConstructionServices>;
 factionPersonFactoryState():import('../../../src/campaign/rules/OriginalFactionPersons.mjs').OriginalFactionPersonFactory;
 createFactionPerson(factionId:string,options:import('../../../src/campaign/rules/OriginalFactionPersons.mjs').OriginalFactionPersonOptions):import('../../../src/campaign/rules/OriginalPlayerEconomy.mjs').OriginalPayrollPerson;
 pickFactionPersonName(factionId:string,gender:import('../../../src/campaign/rules/OriginalFactionPersons.mjs').OriginalPersonGender,random?:import('../../../src/campaign/rules/OriginalJavaRandom.mjs').OriginalJavaRandomState|null):{first:string;last:string;gender:import('../../../src/campaign/rules/OriginalFactionPersons.mjs').OriginalPersonGender};
 pickFactionVoice(factionId:string,importance:import('../../../src/campaign/rules/OriginalFactionPersons.mjs').OriginalPersonImportance,random?:import('../../../src/campaign/rules/OriginalJavaRandom.mjs').OriginalJavaRandomState|null):string|null;
 fleetDataFactoryState():import('../../../src/campaign/rules/OriginalFleetDataFactory.mjs').OriginalFleetDataFactory;
 initializeFleetDataClass():import('../../../src/campaign/rules/OriginalFleetDataFactory.mjs').OriginalFleetDataClass;
 bindFleetDataClass(nullMember:import('../../../src/campaign/rules/OriginalFleetData.mjs').OriginalNativeFleetMember,defaultCommander:import('../../../src/campaign/rules/OriginalPlayerEconomy.mjs').OriginalPayrollPerson):import('../../../src/campaign/rules/OriginalFleetDataFactory.mjs').OriginalFleetDataClass;
 createFleetData(prefix:string|null,sourceFactionId:string|null):ReturnType<typeof import('../../../src/campaign/rules/OriginalFleetDataFactory.mjs').createOriginalFleetData>;
 getNativeFleetCommander(dataRef:string):import('../../../src/campaign/rules/OriginalPlayerEconomy.mjs').OriginalPayrollPerson;
 setNativeFleetCommander(dataRef:string,personRef:string|null,dependencies?:Parameters<NativeLiveEconomyDraft['refreshNativeCharacterStats']>[1]):import('../../../src/campaign/rules/OriginalPlayerEconomy.mjs').OriginalPayrollPerson|null;
 /** Constructor subphase only, NOT a completed/registered CampaignFleet. */
 initializeFleetCommander(dataRef:string,factionId:string,context:{isInSectorGen:boolean},dependencies?:Parameters<NativeLiveEconomyDraft['refreshNativeCharacterStats']>[1]):import('../../../src/campaign/rules/OriginalPlayerEconomy.mjs').OriginalPayrollPerson;

 /** Faction-object overload only: no implicit AI, name override or location registration. */
 createNativeEmptyFleet(faction:import('../../../src/campaign/rules/OriginalCampaignFleet.mjs').OriginalFleetConstructionFaction,aiMode:boolean,context:{isInSectorGen:boolean},dependencies?:Parameters<NativeLiveEconomyDraft['refreshNativeCharacterStats']>[1]):ReturnType<typeof import('../../../src/campaign/rules/OriginalCampaignFleet.mjs').constructOriginalCampaignFleet>;
 nativeCampaignPluginRegistry():import('../../../src/campaign/rules/OriginalCampaignPluginPicks.mjs').OriginalCampaignPluginRegistry;
 addNativeCampaignPlugin(plugin:import('../../../src/campaign/rules/OriginalCampaignPluginPicks.mjs').OriginalCampaignPluginDescriptor):void;
 removeNativeCampaignPlugin(id:string|null):void;
 registerNativeCoreCampaignPlugin():import('../../../src/campaign/rules/OriginalCampaignPluginPicks.mjs').OriginalCampaignPluginDescriptor;
 createNativeModularFleetAI(dataRef:string,services?:NativeModularFleetAIServices):import('../../../src/campaign/rules/OriginalModularFleetAI.mjs').OriginalModularFleetAI;
 advanceNativeModularFleetAI(dataRef:string,seconds:number,services?:import('../../../src/campaign/rules/OriginalModularFleetAI.mjs').OriginalModularFleetAIFrameServices):void;
 createNativeNamedEmptyFleet(factionId:string,name:string|null,aiMode:boolean,context?:Parameters<NativeLiveEconomyDraft['createNativeEmptyFleet']>[2],services?:NativeNamedFleetFactoryServices):ReturnType<NativeLiveEconomyDraft['createNativeEmptyFleet']>;
 attachNativePickedFleetInflater(dataRef:string,params:Parameters<NativeLiveEconomyDraft['attachNativeFleetInflater']>[1],services?:import('../../../src/campaign/rules/OriginalCampaignPluginPicks.mjs').OriginalCampaignPickServices):object|null;
 nativeGenericPluginManager():import('../../../src/campaign/rules/OriginalGenericPlugins.mjs').OriginalGenericPluginManager;
 addNativeGenericPlugin(plugin:import('../../../src/campaign/rules/OriginalGenericPlugins.mjs').OriginalGenericPluginDescriptor,isTransient?:boolean):void;
 removeNativeGenericPlugin(plugin:import('../../../src/campaign/rules/OriginalGenericPlugins.mjs').OriginalGenericPluginDescriptor):void;
 nativeDModClassState():import('../../../src/campaign/rules/OriginalDModManager.mjs').OriginalDModClassState;
 bindNativeDModClassState(state:import('../../../src/campaign/rules/OriginalDModManager.mjs').OriginalDModClassState):import('../../../src/campaign/rules/OriginalDModManager.mjs').OriginalDModClassState;
 nativeDModCount(variant:import('../../../src/campaign/rules/OriginalStorage.mjs').OriginalStorageVariant,services?:NativeDModServices):number;
 setNativeDHull(variant:import('../../../src/campaign/rules/OriginalStorage.mjs').OriginalStorageVariant,services?:NativeDModServices):boolean;
 removeNativeDMod(variant:import('../../../src/campaign/rules/OriginalStorage.mjs').OriginalStorageVariant,id:string,services?:NativeDModServices):void;
 addNativeDMods(variant:import('../../../src/campaign/rules/OriginalStorage.mjs').OriginalStorageVariant,canAddDestroyedMods:boolean,count:number,random:import('../../../src/campaign/rules/OriginalJavaRandom.mjs').OriginalJavaRandomState|null,services?:NativeDModServices):void;
 addNativeCombatDMods(variant:import('../../../src/campaign/rules/OriginalStorage.mjs').OriginalStorageVariant,destroyed:boolean,own:boolean,recoverer:object|null,random:import('../../../src/campaign/rules/OriginalJavaRandom.mjs').OriginalJavaRandomState|null,services?:NativeDModServices):void;
 nativeCoreAutofitClassState():import('../../../src/campaign/rules/OriginalFleetInflater.mjs').OriginalCoreAutofitClassState;
 bindNativeCoreAutofitClassState(state:import('../../../src/campaign/rules/OriginalFleetInflater.mjs').OriginalCoreAutofitClassState):import('../../../src/campaign/rules/OriginalFleetInflater.mjs').OriginalCoreAutofitClassState;
 attachNativeFleetInflater(dataRef:string,params?:Partial<Omit<import('../../../src/campaign/rules/OriginalFleetInflater.mjs').OriginalFleetInflaterParams,'objectRef'>>):import('../../../src/campaign/rules/OriginalFleetInflater.mjs').OriginalFleetInflater;
 inflateNativeFleet(dataRef:string,services?:NativeFleetInflaterServices):boolean;
 fleetAccidentSeverity(dataRef:string,services?:import('../../../src/campaign/rules/OriginalFleetData.mjs').OriginalFleetLifecycleServices):'NONE'|'MAJOR';
 advanceFleetAccidents(dataRef:string,seconds:number,services?:import('../../../src/campaign/rules/OriginalFleetData.mjs').OriginalFleetLifecycleServices):ReturnType<typeof import('../../../src/campaign/rules/OriginalFleetAccidents.mjs').advanceOriginalFleetAccidents>;
 advanceNativeFleetAfterBase(dataRef:string,seconds:number,context:import('../../../src/campaign/rules/OriginalCampaignFleetMotion.mjs').OriginalFleetMotionContext,services?:import('../../../src/campaign/rules/OriginalFleetData.mjs').OriginalFleetLifecycleServices):ReturnType<typeof import('../../../src/campaign/rules/OriginalCampaignFleetAdvance.mjs').advanceOriginalFleetAfterBase>;
 advanceNativeFleetFrame(dataRef:string,seconds:number,context:Omit<import('../../../src/campaign/rules/OriginalCampaignFleetFrame.mjs').OriginalFleetFrameContext,'playerFleet'>,services?:import('../../../src/campaign/rules/OriginalCampaignFleetFrame.mjs').OriginalFleetFrameServices):ReturnType<typeof import('../../../src/campaign/rules/OriginalCampaignFleetFrame.mjs').advanceOriginalFleetFrame>;
 /** Actual render-time state changes; contrail output still needs a Web GPU adapter. */
 createNativeFleetObserverPresentation(dataRef:string,observerDataRef:string,seed:string|number|bigint):OriginalFleetObserverPresentation;
 advanceNativeFleetObserverContact(state:OriginalFleetObserverPresentation,seconds:number,context:OriginalObserverFrameContext,services?:import('../../../src/campaign/rules/OriginalCampaignFleetFrame.mjs').OriginalFleetFrameServices):ReturnType<typeof import('../../../src/campaign/rules/OriginalFleetPresentation.mjs').advanceOriginalFleetObserverContact>;
 advanceNativeFleetObserverView(state:OriginalFleetObserverPresentation,seconds:number,context:OriginalObserverFrameContext,services?:import('../../../src/campaign/rules/OriginalCampaignFleetFrame.mjs').OriginalFleetFrameServices):boolean;
 renderNativeFleetObserverLayers(state:OriginalFleetObserverPresentation,context:OriginalObserverRenderContext,services?:import('../../../src/campaign/rules/OriginalCampaignFleetFrame.mjs').OriginalFleetFrameServices):OriginalObserverFleetLayers;
 renderNativeFleetView(dataRef:string,alpha:number,services?:import('../../../src/campaign/rules/OriginalCampaignFleetView.mjs').OriginalFleetViewServices):import('../../../src/campaign/rules/OriginalFleetDraw.mjs').OriginalFleetDrawFrame;
 renderNativeFleetGraphics(dataRef:string,alpha:number,services?:import('../../../src/campaign/rules/OriginalCampaignFleetView.mjs').OriginalFleetViewServices):import('../../../src/campaign/rules/OriginalFleetDraw.mjs').OriginalFleetDrawFrame;
 setNativeFleetMemberJitter(dataRef:string,memberRef:string,options:{durationIn:number;durationOut:number;color:import('../../../src/campaign/rules/OriginalFleetViewShifters.mjs').ViewRGBA;copies:number;maxRange:number;direction?:[number,number]|null;length?:number;circular?:boolean;brightness?:number},services?:import('../../../src/campaign/rules/OriginalCampaignFleetMemberView.mjs').OriginalMemberViewServices):void;
 endNativeFleetMemberJitter(dataRef:string,memberRef:string):void;
 renderNativeFleetContrails(dataRef:string,alpha?:number):ReturnType<typeof import('../../../src/campaign/rules/OriginalCampaignFleetView.mjs').renderOriginalFleetViewContrails>;
 advanceNativeFleetEvenIfPaused(dataRef:string,seconds:number,context:Omit<import('../../../src/campaign/rules/OriginalCampaignFleetFrame.mjs').OriginalFleetFrameContext,'playerFleet'>,services?:import('../../../src/campaign/rules/OriginalCampaignFleetFrame.mjs').OriginalFleetFrameServices):void;
 setNativeFleetNoEngaging(dataRef:string,seconds:number):void;
 advanceNativeFleetMotion(dataRef:string,seconds:number,context:import('../../../src/campaign/rules/OriginalCampaignFleetMotion.mjs').OriginalFleetMotionContext,services?:import('../../../src/campaign/rules/OriginalFleetData.mjs').OriginalFleetLifecycleServices):ReturnType<typeof import('../../../src/campaign/rules/OriginalCampaignFleetMotion.mjs').advanceOriginalConstructedFleetMotion>;
 findNativePlayerNavigationTarget(dataRef:string,x:number,y:number,services?:OriginalNavigationServices):import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalWorldEntity|null;
 followNativePlayerNavigationTarget(dataRef:string,target:import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalWorldEntity,services?:OriginalNavigationServices):OriginalFollowTargetResult;
 setNativePlayerMovementDestination(dataRef:string,x:number,y:number):void;
 advanceNativePlayerTargetNavigation(dataRef:string,context:{paused:boolean},services?:OriginalNavigationServices):boolean;
 setNativeFleetMoveDestination(dataRef:string,x:number,y:number,override?:boolean):void;
 requestNativeFleetGoSlow(dataRef:string,stop?:boolean):void;
 fleetWorldState():import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorld|null;
 bindDetectedEntityListeners(listeners:NonNullable<import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorld['detectedEntityListeners']>):NonNullable<import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorld['detectedEntityListeners']>;
 bindFleetWorld(world:import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorld):import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorld;
 bindCargoScreenListeners(listeners:NonNullable<import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorld['cargoScreenListeners']>):NonNullable<import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorld['cargoScreenListeners']>;
 cargoPodsVisibilityForPlayerObserver(pod:OriginalCargoPods,observerDataRef:string):import('../../../src/campaign/rules/OriginalSensors.mjs').OriginalVisibilityLevel;
 createNativeCargoPodsObserverPresentation(pod:OriginalCargoPods,observerDataRef:string,seed:string):OriginalCargoPodsObserverPresentation;
 advanceNativeCargoPodsObserver(state:OriginalCargoPodsObserverPresentation,seconds:number,context:OriginalCargoPodsObserverContext,services?:OriginalCargoPodsPresentationServices):ReturnType<typeof advanceOriginalCargoPodsObserver>;
 renderNativeCargoPodsObserverLayers(state:OriginalCargoPodsObserverPresentation,context:OriginalCargoPodsRenderContext,services?:OriginalCargoPodsPresentationServices):OriginalObserverCargoPodsLayers;
 cargoPodsVisibilityToPlayer(pod:OriginalCargoPods):import('../../../src/campaign/rules/OriginalSensors.mjs').OriginalVisibilityLevel;
 advanceNativeCargoPodsFrame(pod:OriginalCargoPods,seconds:number,context:Omit<OriginalCargoPodsFrameContext,'playerFleet'>,services?:OriginalCargoPodsFrameServices):ReturnType<typeof advanceOriginalCargoPodsFrame>;
 advanceNativeCargoPodsEvenIfPaused(pod:OriginalCargoPods,seconds:number,context:Omit<OriginalCargoPodsFrameContext,'playerFleet'>,services?:OriginalCargoPodsFrameServices):void;
 addNativePlanet(locationRef:string,input:Omit<OriginalCampaignPlanetInput,'id'>&{id:string|null},services?:NativePlanetServices):OriginalCampaignPlanet;
 removeNativePlanet(planet:OriginalCampaignPlanet,services?:NativePlanetServices):void;
 planetFactionId(planet:OriginalCampaignPlanet):string;
 planetVisibilityToPlayer(planet:OriginalCampaignPlanet):import('../../../src/campaign/rules/OriginalSensors.mjs').OriginalVisibilityLevel;
 planetVisibilityForPlayerObserver(planet:OriginalCampaignPlanet,observerDataRef:string):import('../../../src/campaign/rules/OriginalSensors.mjs').OriginalVisibilityLevel;
 advanceNativePlanetFrame(planet:OriginalCampaignPlanet,seconds:number,context:Omit<OriginalCampaignPlanetFrameContext,'playerFleet'>,services?:OriginalCampaignPlanetFrameServices):ReturnType<typeof advanceOriginalCampaignPlanetFrame>;
 advanceNativePlanetEvenIfPaused(planet:OriginalCampaignPlanet,seconds:number,context:Omit<OriginalCampaignPlanetFrameContext,'playerFleet'>,services?:OriginalCampaignPlanetFrameServices):void;
 addNativeCargoPods(locationRef:string,position:[number,number],services?:NativeCargoPodsServices):OriginalCargoPods;
 removeNativeCargoPods(entity:OriginalCargoPods,services?:NativeCargoPodsServices):void;
 reportNativePlayerDidNotTakeCargo(cargo:import('../../../src/campaign/rules/OriginalPlayerEconomy.mjs').OriginalPlayerCargo,services?:NativeCargoPodsServices):void;
 addNativeFleetToLocation(dataRef:string,locationRef:string,services?:import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorldServices):void;
 removeNativeFleetFromLocation(dataRef:string,locationRef:string,services?:import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorldServices):void;
 addNativeFleetEventListener(dataRef:string,listener:import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorldListener):void;
 bindNativeFleetRouteSpace(dataRef:string):import('../../../src/campaign/rules/OriginalRouteSpace.mjs').OriginalRouteSpatialEntity;
 addNativeFleetAbility(dataRef:string,id:string):import('../../../src/campaign/rules/OriginalCampaignAbilities.mjs').OriginalCampaignAbility;
 nativeFleetAbility(dataRef:string,id:string):import('../../../src/campaign/rules/OriginalCampaignAbilities.mjs').OriginalAbilityPlugin|null;
 changeNativeFleetAbility(dataRef:string,id:string,action:'activate'|'deactivate'|'press',context:Pick<import('../../../src/campaign/rules/OriginalCampaignAbilities.mjs').OriginalAbilityContext,'currentLocation'>&{paused?:boolean},services?:import('../../../src/campaign/rules/OriginalCampaignAbilities.mjs').OriginalAbilityServices):ReturnType<typeof import('../../../src/campaign/rules/OriginalCampaignAbilities.mjs').changeOriginalFleetAbility>;
 removeNativeFleetAbility(dataRef:string,id:string,context:Pick<import('../../../src/campaign/rules/OriginalCampaignAbilities.mjs').OriginalAbilityContext,'currentLocation'|'paused'>,services?:import('../../../src/campaign/rules/OriginalCampaignAbilities.mjs').OriginalAbilityServices):ReturnType<typeof import('../../../src/campaign/rules/OriginalCampaignAbilities.mjs').removeOriginalFleetAbility>;
 updateNativeFleetAbilityLayers(dataRef:string,services?:import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorldServices):boolean;
 despawnNativeFleet(dataRef:string,reason?:string,param?:unknown,services?:import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorldServices):{aborted:boolean};
 finishNativeFleetAfterView(dataRef:string,services?:import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorldServices):{aborted:boolean}|null;
 removeExpiredNativeWorldFleets(locationRef:string,services?:import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetWorldServices):import('../../../src/campaign/rules/OriginalCampaignFleet.mjs').OriginalConstructedCampaignFleet[];
 fleetTowCableState():import('../../../src/campaign/rules/OriginalTowCable.mjs').OriginalTowCablePersistentEntry|null;
 bindFleetTowCableState(state:import('../../../src/campaign/rules/OriginalTowCable.mjs').OriginalTowCablePersistentEntry):import('../../../src/campaign/rules/OriginalTowCable.mjs').OriginalTowCablePersistentEntry;
 fleetRosterState():import('../../../src/campaign/rules/OriginalFleetRoster.mjs').OriginalFleetRosterState;
 registerFleetRoster(fleet:import('../../../src/campaign/rules/OriginalFleetData.mjs').OriginalNativeFleet,naming:import('../../../src/campaign/rules/OriginalFleetMembers.mjs').OriginalFleetNaming,shipNameRandom?:import('../../../src/campaign/rules/OriginalJavaRandom.mjs').OriginalJavaRandomState|null):import('../../../src/campaign/rules/OriginalFleetRoster.mjs').OriginalFleetRosterBinding;
 bindFleetRoster(dataRef:string,plugins?:import('../../../src/campaign/rules/OriginalMemberEffects.mjs').OriginalMemberEffectPlugins,lifecycle?:import('../../../src/campaign/rules/OriginalFleetRoster.mjs').OriginalFleetRosterLifecycle):import('../../../src/campaign/rules/OriginalFleetRoster.mjs').OriginalFleetRosterServices;
 fleetCompositionState():import('../../../src/campaign/rules/OriginalFleetComposition.mjs').OriginalFleetCompositionState;
 composeFleetRoster<Member extends object>(factionId:string,marketId:string,params:import('../../../src/campaign/rules/OriginalFleetComposition.mjs').OriginalFleetCompositionParams,random:import('../../../src/campaign/rules/OriginalJavaRandom.mjs').OriginalJavaRandomState,services?:Partial<import('../../../src/campaign/rules/OriginalFleetComposition.mjs').OriginalFleetCompositionServices<Member>>):void;
 shipQuality(marketId?:string|null,factionId?:string|null):number;
 routeSpatialState():import('../../../src/campaign/rules/OriginalRouteSpace.mjs').OriginalRouteSpace|null;
 sensorState():import('../../../src/campaign/rules/OriginalSensors.mjs').OriginalFleetSensorState|null;
 fleetVisibilityToPlayer(fleetRef:string):import('../../../src/campaign/rules/OriginalSensors.mjs').OriginalVisibilityLevel;
 fleetVisibilityForPlayerObserver(targetDataRef:string,observerDataRef:string,sensingDataRef?:string):import('../../../src/campaign/rules/OriginalSensors.mjs').OriginalVisibilityLevel;
 registerNativeFleetSensors(dataRef:string):void;
 bindSensorFleet(fleet:import('../../../src/campaign/rules/OriginalSensors.mjs').OriginalSensorFleet):void;
 routePosition(routeRef:string):DeepReadonly<{routeRef:string;hyperPosition:import('../../../src/campaign/rules/OriginalRouteSpace.mjs').OriginalRouteVector;containingLocationRef:string|null}>;
 setRouteFleetMousedOver(fleetRef:string,value:boolean|null):void;
 advanceRouteFleetPhase(services?:import('../../../src/campaign/rules/OriginalRouteFleets.mjs').OriginalRouteFleetRuntime):ReturnType<typeof import('../../../src/campaign/rules/OriginalRouteFleets.mjs').advanceOriginalRouteFleetPhase>;
 reportRouteFleetDespawned(fleetRef:string,reason:string):string|null;
 advanceRouteManager(seconds:number,services?:import('../../../src/campaign/rules/OriginalRouteFleets.mjs').OriginalRouteManagerServices):DeepReadonly<{scope:'route-manager-time-and-fleet-phases';time:ReturnType<NativeLiveEconomyDraft['advanceRouteTimePhase']>;fleets:ReturnType<NativeLiveEconomyDraft['advanceRouteFleetPhase']>;readyForAuthority:false}>;
 militaryPatrolState():import('../../../src/campaign/rules/OriginalMilitaryPatrols.mjs').OriginalPatrolState|null;
 advanceMilitaryPatrolAfterBase(marketId:string,industryId:string,seconds:number,services?:Partial<Pick<import('../../../src/campaign/rules/OriginalMilitaryPatrols.mjs').OriginalPatrolRuntime,'randomDouble'|'newRouteSeed'|'shipQuality'|'officerQuality'>>&{simMode?:boolean;fastPatrolSpawn?:boolean}):ReturnType<typeof import('../../../src/campaign/rules/OriginalMilitaryPatrols.mjs').advanceOriginalMilitaryPatrolAfterBase>;
 advanceMilitaryMemoryPhase(marketId:string,seconds:number,options?:{paused?:boolean}):DeepReadonly<{scope:'selected-military-memory-phase';expired:string[]}>;
 setMilitaryDisrupted(marketId:string,industryId:string,days:number,useMax?:boolean):boolean;
 /** Engine hooks only, not a priced/authorized player command. */
 startMilitaryUpgrade(marketId:string,industryId:string):void;
 cancelMilitaryUpgrade(marketId:string,industryId:string):void;
 refreshNativeColonyEconomy():DeepReadonly<{passes:number;counts:NativeScheduledEconomyPass['counts']}>;
 applyNativeColonyConstruction(marketId:string,action:import('../../../src/campaign/client/NativeProtocol.js').NativeColonyGesture):{kind:string;marketId:string;inspection?:import('../../../src/campaign/rules/OriginalColonyConstructionCommands.mjs').OriginalColonyConstructionBuildInspection;receipt?:import('../../../src/campaign/rules/OriginalColonyConstructionCommands.mjs').OriginalColonyConstructionReceipt};
 buildNextNativeConstructionQueue(marketId:string,services?:{militaryServices?:Parameters<NativeLiveEconomyDraft['advanceMilitaryPatrolAfterBase']>[3];productionServices?:NativeProductionFrameServices;civicServices?:NativeCivicFrameServices;resourceServices?:NativeResourceFrameServices}):string|null;
 editNativeConstructionQueue(marketId:string,industryId:string,action:'up'|'down'|'front'|'back'|'remove'):void;
 buildNextMilitaryQueue(marketId:string,services?:Parameters<NativeLiveEconomyDraft['advanceMilitaryPatrolAfterBase']>[3]):string|null;
 advanceMilitaryIndustry(marketId:string,industryId:string,seconds:number,services?:NonNullable<Parameters<NativeLiveEconomyDraft['advanceMilitaryPatrolAfterBase']>[3]>&{colonyDebug?:boolean}):ReturnType<typeof import('../../../src/campaign/rules/OriginalMilitaryLifecycle.mjs').advanceOriginalMilitaryIndustry>;
 advanceRouteTimePhase(seconds:number,services:Omit<Parameters<typeof import('../../../src/campaign/rules/OriginalMilitaryPatrols.mjs').advanceOriginalRouteTime>[2],'timestamp'>):ReturnType<typeof import('../../../src/campaign/rules/OriginalMilitaryPatrols.mjs').advanceOriginalRouteTime>;

 static fromCheckpoint(checkpoint:unknown,options?:{readMaxOutposts?:()=>number}):NativeLiveEconomyDraft;
 checkpoint():DeepReadonly<import('./CheckpointCodec.mjs').OfflineCheckpoint>;
 constructor(capture:DeepReadonly<NativeSaveEconomyCapture>);
 playerExportModifiers:Record<string,EconomyMutable|null>;
 inNewGameAdvance:boolean|null;
 market(marketId:string):NativeLiveMarket;
 marketIds():string[];
 getCommodityData(marketId:string,commodityId:string):DeepReadonly<OriginalCommodityCacheEntry>;
 rebuildCommodityData(commodityId:string,econGroup:string|null):DeepReadonly<OriginalCommodityCacheEntry>;
 peekCommodityData(marketId:string,commodityId:string):DeepReadonly<OriginalCommodityCacheEntry>|null;
 getExportIncome(marketId:string,commodityId:string):number;
 getShipping(marketId:string):DeepReadonly<{global:number;inFaction:number}>;
 /** Exact callbacks only; neither method executes the complete native industry lifecycle. */
 modifyPopulationStability(marketId:string,readMaxOutposts?:()=>number):DeepReadonly<OriginalPopulationStabilityResult>;
 /** Real native stockpile phase with current game-month getter; economic stockpile is not retail cargo. */
 updateStockpileAndPrice(marketId:string,triggerCommodityId:string,options:{month?:number;phase:import('../../../src/campaign/rules/OriginalMarketEconomy.mjs').EconomyPricePass['phase']}):DeepReadonly<import('../../../src/campaign/rules/OriginalCommodityClassPricing.mjs').OriginalClassPricingResult>;
 beginScheduledEconomyPass(options:{lastIteration:boolean;paused:false},readMaxOutposts?:()=>number):DeepReadonly<NativeScheduledEconomyPass>;
 stepScheduledEconomyPass():DeepReadonly<NativeScheduledEconomyPass>;
 runScheduledEconomyPass(options:{lastIteration:boolean;paused:false},readMaxOutposts?:()=>number):DeepReadonly<NativeScheduledEconomyPass>;
 scheduledEconomyStatus():DeepReadonly<NativeScheduledEconomyPass>|null;
 economyListenerSnapshot():ReturnType<import('../../../src/campaign/rules/OriginalEconomyListeners.mjs').OriginalEconomyUpdateListeners['snapshot']>|null;
 economyNotificationSnapshot():ReturnType<import('../../../src/campaign/rules/OriginalEconomyNotifications.mjs').OriginalEconomyNotifications['snapshot']>|null;
 nativeCustomProductionState():import('../../../src/campaign/rules/OriginalCustomProduction.mjs').OriginalCustomProductionState;
 bindNativeCustomProductionState(state:import('../../../src/campaign/rules/OriginalCustomProduction.mjs').OriginalCustomProductionState):import('../../../src/campaign/rules/OriginalCustomProduction.mjs').OriginalCustomProductionState;
 generateNativeIndustryProductionCargo(industry:import('../../../src/campaign/rules/OriginalIndustryCommodityPass.mjs').OriginalIndustryCommodityEntry,random:import('../../../src/campaign/rules/OriginalJavaRandom.mjs').OriginalJavaRandomState|null,services?:import('../../../src/campaign/rules/OriginalIndustryProductionCargo.mjs').OriginalIndustryProductionServices):import('../../../src/campaign/rules/OriginalPlayerEconomy.mjs').OriginalPlayerCargo|null;
 readNativeIndustryProductionCargoTitle(industry:import('../../../src/campaign/rules/OriginalIndustryCommodityPass.mjs').OriginalIndustryCommodityEntry):string;
 nativeProductionHullVariants(hullId:string):string[];
 runNativeCustomProduction(services?:NativeCustomProductionDependencies):import('../../../src/campaign/rules/OriginalCustomProduction.mjs').OriginalCustomProductionResult;
 monthlyAccountSnapshot():DeepReadonly<import('../../../src/campaign/rules/OriginalMonthlyReport.mjs').OriginalMonthlyAccounts>;
 reportLocalResourcesEconomyTick(listenerRef:string,iteration:number):ReturnType<import('../../../src/campaign/rules/OriginalEconomyListeners.mjs').OriginalEconomyUpdateListeners['reportEconomyTick']>;
 reportLocalResourcesEconomyMonthEnd(listenerRef:string):ReturnType<import('../../../src/campaign/rules/OriginalEconomyListeners.mjs').OriginalEconomyUpdateListeners['reportEconomyMonthEnd']>;
 playerEconomyState():import('../../../src/campaign/rules/OriginalPlayerEconomy.mjs').OriginalPlayerEconomyState;
 playerEconomySnapshot():DeepReadonly<import('../../../src/campaign/rules/OriginalPlayerEconomy.mjs').OriginalPlayerEconomyCapture>|null;
 refreshNativeTopography(listenerRef:string):ReturnType<typeof import('../../../src/campaign/rules/OriginalHyperspaceTopography.mjs').refreshOriginalHyperspaceTopography>;
 refreshNativeCharacterStats(personRef:string,dependencies?:{refreshOutposts?:boolean;resolvePending?:boolean;nativeFleetServices?:import('../../../src/campaign/rules/OriginalFleetData.mjs').OriginalFleetLifecycleServices;characterEffects?:import('../../../src/campaign/rules/OriginalNativeCharacterStats.mjs').OriginalCharacterServices['effects'];resolveCharacterFleet?(ref:string):import('../../../src/campaign/rules/OriginalFleetData.mjs').OriginalNativeFleet;readCharacterFleetMembers?(fleet:import('../../../src/campaign/rules/OriginalFleetData.mjs').OriginalNativeFleet):import('../../../src/campaign/rules/OriginalFleetData.mjs').OriginalNativeFleetMember[];refreshHyperspaceTopography?(listener:import('../../../src/campaign/rules/OriginalNativeCharacterStats.mjs').OriginalCharacterWorldCapture['listeners'][number],draft:NativeLiveEconomyDraft):void;refreshCharacterPlayerOutposts?(stats:import('../../../src/campaign/rules/OriginalNativeCharacterStats.mjs').OriginalNativeCharacterStats,markets:NativeLiveMarket[],draft:NativeLiveEconomyDraft):void}):import('../../../src/campaign/rules/OriginalNativeCharacterStats.mjs').OriginalCharacterRefreshResult;
 readFleetDeploymentPoints(dependencies?:NativePersonnelDependencies):number[];
 readNativeOutpostLimit():number;
 readNativeMarketAdministratorModifier(marketId:string,key:'supply_bonus'|'demand_reduction'|'fuel_supply_bonus'):number;
 getNativeMarketAdministrator(marketId:string):import('../../../src/campaign/rules/OriginalPlayerEconomy.mjs').OriginalPayrollPerson;
 setNativeMarketAdministrator(marketId:string,personRef:string|null):import('../../../src/campaign/rules/OriginalPlayerEconomy.mjs').OriginalPayrollPerson|null;
 readOfficerPayroll():import('../../../src/campaign/rules/OriginalMonthlyReport.mjs').OriginalFleetPayroll['officers'];
 readAdministrators(dependencies?:NativePersonnelDependencies):import('../../../src/campaign/rules/OriginalMonthlyReport.mjs').OriginalAdministratorPayroll[];
 readFleetPayroll(dependencies?:NativePersonnelDependencies):import('../../../src/campaign/rules/OriginalMonthlyReport.mjs').OriginalFleetPayroll;
 readFleetCargoStat(kind:'crew'|'marines'|'supplies'|'fuel'|'cargo',dependencies?:NativePersonnelDependencies):number;
 hasStorageAccess(marketId:string):boolean;
 nativeStorageCargo(marketId:string):import('../../../src/campaign/rules/OriginalStorage.mjs').OriginalStorageCargo|null;
 initializeNativeCargoMothballedShips(cargo:import('../../../src/campaign/rules/OriginalFleetDataFactory.mjs').OriginalConstructedCargo,factionId:string):import('../../../src/campaign/rules/OriginalFleetDataFactory.mjs').OriginalConstructedFleetData;
 readStorageValues(marketId:string,dependencies?:import('../../../src/campaign/rules/OriginalStorage.mjs').OriginalStorageDependencies):{cargo:number;ships:number};
 reportCoreEconomyTick(dependencies:import('../../../src/campaign/rules/OriginalStorage.mjs').OriginalStorageDependencies & NativePersonnelDependencies & {readIndustryName(marketId:string,industryId:string):string}):ReturnType<typeof import('../../../src/campaign/rules/OriginalMonthlyReport.mjs').originalCoreEconomyTick>;
 reportCoreEconomyMonthEnd(dependencies:NativePersonnelDependencies & Pick<import('../../../src/campaign/rules/OriginalMonthlyReport.mjs').OriginalCoreEconomyRuntime,'doCustomProduction'>):ReturnType<typeof import('../../../src/campaign/rules/OriginalMonthlyReport.mjs').originalCoreEconomyMonthEnd>;
 nativeEconomySchedule():DeepReadonly<import('../../../src/campaign/rules/OriginalMarketEconomySchedule.mjs').OriginalEconomySchedule>;
 createNativeBattle(firstDataRef:string,secondDataRef:string,services?:OriginalCampaignBattleServices):OriginalCampaignBattle;
 pickNativeBattleSide(battle:OriginalCampaignBattle,dataRef:string,services?:OriginalCampaignBattleServices,respectTransponder?:boolean):OriginalBattleSide;
 canJoinNativeBattle(battle:OriginalCampaignBattle,dataRef:string,services?:OriginalCampaignBattleServices):boolean;
 joinNativeBattle(battle:OriginalCampaignBattle,dataRef:string,services?:OriginalCampaignBattleServices,side?:OriginalBattleSide):boolean;
 takeNativeBattleSnapshots(battle:OriginalCampaignBattle):OriginalCampaignBattle;
 advanceNativeBattleFrame(battle:OriginalCampaignBattle,seconds:number,context:OriginalBattleFrameContext,services?:OriginalFleetEncounterServices):void;
 nativeFactionRelationsState():OriginalFactionRelations|null;
 nativeHullmodItemManager():import('../../../src/campaign/rules/OriginalHullmodItems.mjs').OriginalHullmodItemManager;
 isNativeHullmodItemAvailable(id:string,member:import('../../../src/campaign/rules/OriginalHullmodItems.mjs').OriginalHullmodItemMember|null,variant:import('../../../src/campaign/rules/OriginalStorage.mjs').OriginalStorageVariant|null,market:object|null,services?:import('../../../src/campaign/rules/OriginalHullmodItems.mjs').OriginalHullmodItemServices):boolean;
 reportNativeRefitVariantSaved(member:import('../../../src/campaign/rules/OriginalHullmodItems.mjs').OriginalHullmodItemMember,market:object|null,services?:import('../../../src/campaign/rules/OriginalHullmodItems.mjs').OriginalHullmodItemServices & {reportRefitVariantSavedToListener?(listener:object,member:import('../../../src/campaign/rules/OriginalHullmodItems.mjs').OriginalHullmodItemMember,market:object|null):void}):void;
 bindNativeSpecialItem(plugin:import('../../../src/campaign/rules/OriginalSpecialItems.mjs').OriginalSpecialItemState,services?:import('../../../src/campaign/rules/OriginalSpecialItems.mjs').OriginalSpecialItemServices):import('../../../src/campaign/rules/OriginalSpecialItems.mjs').OriginalSpecialItemFacade;
 readNativePlayerAvailableHullmods(services?:import('../../../src/campaign/rules/OriginalPlayerHullmods.mjs').OriginalPlayerHullmodServices):string[];
 addNativePlayerHullmod(id:string):void;
 removeNativePlayerHullmod(id:string):void;
 nativeFactionEquipmentState(factionId:string):OriginalFactionEquipment|null;
 bindNativeFactionEquipment(factionId:string,state:OriginalFactionEquipment):OriginalFactionEquipment;
 readNativeFactionKnownEquipment(factionId:string,kind:OriginalFactionEquipmentKind,services?:OriginalFactionEquipmentServices):string[];
 isNativeFactionEquipmentKnownAt(factionId:string,kind:OriginalTimedFactionEquipmentKind,id:string,timestamp:string|null):boolean;
 isNativeFactionEquipmentPriority(factionId:string,kind:OriginalFactionEquipmentKind,id:string):boolean;
 setNativeFactionEquipmentPriority(factionId:string,kind:OriginalFactionEquipmentKind,id:string,enabled:boolean):void;
 addNativeFactionKnownEquipment(factionId:string,kind:OriginalTimedFactionEquipmentKind,id:string,recordTimestamp:boolean,services?:OriginalFactionEquipmentServices):void;
 removeNativeFactionKnownEquipment(factionId:string,kind:OriginalTimedFactionEquipmentKind,id:string):void;
 nativeFactionFrameState(factionId:string):OriginalFactionFrame|null;
 bindNativeFactionFrame(factionId:string,frame:OriginalFactionFrame):OriginalFactionFrame;
 nativeFactionMemoryWithoutUpdate(factionId:string):import('../../../src/campaign/rules/OriginalCampaignMemory.mjs').OriginalCampaignMemory;
 nativeFactionProductionState(factionId:string):OriginalFactionProduction;
 readNativeProductionUnitCost(factionId:string,type:OriginalProductionItemType,specId:string,services?:import('../../../src/campaign/rules/OriginalFactionProduction.mjs').OriginalProductionPricingServices):number;
 readNativeProductionOrderCost(factionId:string,services?:import('../../../src/campaign/rules/OriginalFactionProduction.mjs').OriginalProductionPricingServices):number;
 readNativeProductionCapacity(factionId:string):number;
 addNativeFactionProductionItem(factionId:string,type:OriginalProductionItemType,specId:string,quantity?:number,limit?:number,services?:OriginalProductionItemServices):boolean;
 removeNativeFactionProductionItem(factionId:string,type:OriginalProductionItemType,specId:string,quantity:number,services?:OriginalProductionItemServices):void;
 nativeFactionGatheringPoint(factionId:string):NativeLiveMarket|null;
 clearNativeFactionProduction(factionId:string,services?:OriginalProductionItemServices):void;
 advanceNativeFactionFrame(factionId:string,seconds:number,context:{paused:boolean},services?:Omit<OriginalFactionFrameServices,'convertFactionSecondsToDays'>):void;
 bindNativeFactionRelations(manager:OriginalFactionRelations):OriginalFactionRelations;
 nativeFactionRelation(one:string|null,two:string|null):OriginalFactionRelation|null;
 getNativeFactionRelationship(one:string,two:string):number;
 setNativeFactionRelationship(one:string,two:string,value:number):void;
 adjustNativePlayerFactionReputation(action:unknown,factionId:string,services?:OriginalReputationServices):OriginalReputationResult;
 createNativeFleetEncounterContext(services?:OriginalFleetEncounterServices):OriginalFleetEncounterContext;
 nativeRetainedEncounterState():NativeRetainedEncounters;
 retainNativeFleetEncounterContext(ownerDataRef:string,state:OriginalEncounterState):string;
 retainedNativeFleetEncounterContext(encounterId:string,services?:OriginalFleetEncounterServices):OriginalFleetEncounterContext;
 releaseNativeFleetEncounterContext(encounterId:string):boolean;
 nativeFleetLootCargoView(encounterId:string):NativeLootCargoView;
 applyNativeFleetLootCargoActions(encounterId:string,actions:OriginalLootCargoAction[],services?:OriginalFleetEncounterServices):NativeLootCargoView;
 nativeFleetInteractionAftermathState(encounterId:string):OriginalFleetInteractionAftermath|null;
 createNativeFleetInteractionAftermath(encounterId:string,otherDataRef:string,progress:OriginalFleetInteractionProgress,config?:OriginalFleetAftermathConfig):OriginalFleetInteractionAftermath;
 completeNativeFleetVictorySalvage(encounterId:string,dialog:OriginalFleetInteractionDialog,services?:OriginalFleetInteractionServices):void;
 openNativeFleetLoot(encounterId:string,dialog:OriginalFleetInteractionDialog,services?:OriginalFleetInteractionServices):void;
 /** Atomically confirms temporary loot, reports remainder/transaction, then runs real aftermath. Missing world receivers reject the draft. */
 dismissNativeFleetLoot(encounterId:string,dialog:OriginalFleetInteractionDialog,services?:OriginalFleetInteractionServices):boolean;
 leaveNativeFleetInteraction(encounterId:string,dialog:OriginalFleetInteractionDialog,continued?:boolean,services?:OriginalFleetInteractionServices):boolean;
 bindNativeFleetEncounterContext(state:OriginalEncounterState,services?:OriginalFleetEncounterServices):OriginalFleetEncounterContext;
 createNativeBattleAutoresolver(battle:OriginalCampaignBattle,services?:OriginalFleetEncounterServices):OriginalBattleAutoresolver;
 resolveNativeBattleAutoresolver(resolver:OriginalBattleAutoresolver,services?:OriginalFleetEncounterServices):OriginalBattleEngagementResult|undefined;
 resolveNativeBattlePlayerPursuit(resolver:OriginalBattleAutoresolver,context:OriginalBattleEncounterContext,selected:import('../../../src/campaign/rules/OriginalFleetData.mjs').OriginalNativeFleetMember[],services?:OriginalFleetEncounterServices):OriginalBattleEngagementResult|undefined;
 generateNativeBattleCombined(battle:OriginalCampaignBattle,services?:OriginalBattleLifecycleServices,withStations?:boolean,removeEmpty?:boolean):OriginalCampaignBattle;
 uncombineNativeBattle(battle:OriginalCampaignBattle,services?:OriginalBattleLifecycleServices):void;
 leaveNativeBattle(battle:OriginalCampaignBattle,dataRef:string,engaged:boolean,services?:OriginalBattleLifecycleServices):void;
 finishNativeBattle(battle:OriginalCampaignBattle,winner:OriginalBattleSide|null,engaged?:boolean,services?:OriginalBattleLifecycleServices):void;
 resolveNativeBattleRound(battle:OriginalCampaignBattle,services?:OriginalFleetEncounterServices):void;
 advanceNativeLocationEncounters(locationRef:string,context:OriginalLocationEncounterContext,services?:OriginalLocationEncounterServices & OriginalCampaignBattleServices):OriginalLocationEncounterResult;
 nativeLocationFrameState(locationRef:string):OriginalLocationFrame|null;
 bindNativeLocationBackground(locationRef:string,background:OriginalNormalSpaceBackground):OriginalNormalSpaceBackground;
 setNativeLocationBackgroundTexture(locationRef:string,texturePath:string|null):void;
 bindNativeLocationFrame(state:OriginalLocationFrame):OriginalLocationFrame;
 advanceNativeLocationEvenIfPaused(locationRef:string,seconds:number,context:OriginalLocationFrameContext,services?:NativeLocationFrameServices):ReturnType<typeof advanceOriginalLocationEvenIfPaused>;
 advanceNativeLocationFrame(locationRef:string,seconds:number,context:OriginalLocationFrameContext,services?:NativeLocationFrameServices):ReturnType<typeof advanceOriginalLocationFrame>;
 bindNativeCharacterMemory(characterRef:string,memory:OriginalCampaignMemory|null):OriginalCampaignMemory|null;
 nativeCharacterMemoryWithoutUpdate():OriginalCampaignMemory;
 advanceNativeCharacterMemory(seconds:number,context:{paused:boolean},services?:OriginalCampaignMemoryServices):void;
 nativeCampaignListenerTimeoutsState():OriginalCampaignListenerTimeouts|null;
 bindNativeCampaignListenerTimeouts(state:OriginalCampaignListenerTimeouts):OriginalCampaignListenerTimeouts;
 addNativeCampaignListenerWithTimeout(listener:OriginalFleetWorldListener,days:number):void;
 removeNativeCampaignListener(listener:OriginalFleetWorldListener):void;
 advanceNativeCampaignListenerTimeouts(days:number):void;
 nativeImportantPeopleState():OriginalImportantPeople|null;
 bindNativeImportantPeople(state:OriginalImportantPeople):OriginalImportantPeople;
 addNativeImportantPerson(personRef:string):void;
 removeNativeImportantPerson(personId:string):void;
 advanceNativeImportantPeople(seconds:number,context:{paused:boolean},services?:Omit<OriginalImportantPeopleServices,'convertImportantPeopleSecondsToDays'>):void;
 nativeCampaignEventManagerState():OriginalCampaignEventManager|null;
 bindNativeCampaignEventManager(state:OriginalCampaignEventManager):OriginalCampaignEventManager;
 createNativeCampaignEventManager():OriginalCampaignEventManager;
 createNativeBaseCampaignEvent():OriginalBaseCampaignEvent;
 initializeNativeBaseCampaignEvent(event:OriginalBaseCampaignEvent,type:string,target:OriginalCampaignEventTarget,services?:NativeCampaignEventServices,addListener?:boolean):void;
 nativeCampaignEventProbability(type:string,target:OriginalCampaignEventTarget,services?:NativeCampaignEventServices):OriginalCampaignEventProbability;
 ongoingNativeCampaignEvent(target:OriginalCampaignEventTarget|null,type:string,services?:NativeCampaignEventServices):OriginalCampaignEventPlugin|null;
 countNativeCampaignEvents(type:string,services?:NativeCampaignEventServices):number;
 primeNativeCampaignEvent(target:OriginalCampaignEventTarget|null,type:string,param?:unknown,services?:NativeCampaignEventServices):OriginalCampaignEventPlugin|null;
 startNativeCampaignEvent(target:OriginalCampaignEventTarget|null,type:string,param?:unknown,services?:NativeCampaignEventServices):OriginalCampaignEventPlugin|null;
 startNativeCampaignEventPlugin(event:OriginalCampaignEventPlugin,services?:NativeCampaignEventServices):void;
 endNativeCampaignEvent(event:OriginalCampaignEventPlugin,services?:NativeCampaignEventServices):void;
 advanceNativeCampaignEventManager(seconds:number,context:{paused:boolean},services?:NativeCampaignEventServices):void;
 nativeIntelManagerState():OriginalIntelManager|null;
 bindNativeIntelManager(state:OriginalIntelManager):OriginalIntelManager;
 findNativeIntelCommRelay(observer:object|null,services?:OriginalIntelSpatialServices):object|null;
 addNativeProductionReportIntel(delivery:import('../../../src/campaign/rules/OriginalCustomProduction.mjs').OriginalProductionDelivery<NativeLiveMarket>,services?:NativeIntelServices):import('../../../src/campaign/rules/OriginalProductionReportIntel.mjs').OriginalProductionReportIntel<NativeLiveMarket>;
 queueNativeIntel(item:OriginalIntelPlugin,delay?:number):void;
 unqueueNativeIntel(item:OriginalIntelPlugin):boolean;
 addNativeIntel(item:OriginalIntelPlugin,silent?:boolean,textPanel?:object|null,services?:NativeIntelServices):void;
 removeNativeIntel(item:OriginalIntelPlugin,services?:NativeIntelServices):void;
 clearNativeIntel():void;
 notifyNativeIntelScreenOpening(services?:NativeIntelServices):void;
 removeNativeExpiredIntel(services?:NativeIntelServices):void;
 advanceNativeIntelManager(seconds:number,context:{paused:boolean},services?:NativeIntelServices):void;
 addNativeBaseIntelScript(item:import('../../../src/campaign/rules/OriginalProductionReportIntel.mjs').OriginalSupportedIntel,transient?:boolean):void;
 endNativeBaseIntel(item:import('../../../src/campaign/rules/OriginalProductionReportIntel.mjs').OriginalSupportedIntel,days?:number,services?:OriginalBaseIntelServices):void;
 advanceNativeBaseIntelScript(item:import('../../../src/campaign/rules/OriginalProductionReportIntel.mjs').OriginalSupportedIntel,seconds:number,services?:OriginalBaseIntelServices):void;
 nativeEntityById(id:string):import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalWorldEntity|null;
 nativeLocationEntityById(locationRef:string,id:string):import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalWorldEntity|null;
 readdNativeEngineChangeListeners():void;
 removeNativeStarSystem(locationRef:string):void;
 updateNativePlayerSpeedBonus(services?:import('../../../src/campaign/rules/OriginalFleetData.mjs').OriginalFleetLifecycleServices):void;
 resourceLifecycleState(marketId:string):import('../../../src/campaign/rules/OriginalResourceLifecycle.mjs').OriginalResourceLifecycleState|null;
 advanceNativeResourceIndustry(marketId:string,industryId:string,seconds:number,services?:NativeResourceFrameServices):ReturnType<typeof import('../../../src/campaign/rules/OriginalResourceLifecycle.mjs').advanceOriginalResourceIndustryFrame>;
 setNativeResourceDisrupted(marketId:string,industryId:string,days:number,useMax?:boolean):boolean;
 setNativeResourceSpecialItem(marketId:string,industryId:string,special:import('../../../src/campaign/rules/OriginalResourceLifecycle.mjs').OriginalResourceLifecycleRow['special'],services?:NativeResourceFrameServices):void;
 civicLifecycleState(marketId:string):import('../../../src/campaign/rules/OriginalCivicLifecycle.mjs').OriginalCivicLifecycleState|null;
 advanceNativeCivicIndustry(marketId:string,industryId:string,seconds:number,services?:NativeCivicFrameServices):ReturnType<typeof import('../../../src/campaign/rules/OriginalCivicLifecycle.mjs').advanceOriginalCivicIndustryFrame>;
 startNativeCivicUpgrade(marketId:string,industryId:string):void;
 cancelNativeCivicUpgrade(marketId:string,industryId:string):void;
 setNativeCivicDisrupted(marketId:string,industryId:string,days:number,useMax?:boolean):boolean;
 setNativeCivicSpecialItem(marketId:string,industryId:string,special:import('../../../src/campaign/rules/OriginalCivicLifecycle.mjs').OriginalCivicLifecycleRow['special']):void;
 productionLifecycleState(marketId:string):OriginalProductionLifecycleState|null;
 advanceNativeProductionIndustry(marketId:string,industryId:string,seconds:number,services?:NativeProductionFrameServices):{scope:'native-production-industry-frame';industryRef:string;finishedRef:string|null};
 startNativeProductionUpgrade(marketId:string,industryId:string):void;
 cancelNativeProductionUpgrade(marketId:string,industryId:string):void;
 setNativeProductionDisrupted(marketId:string,industryId:string,days:number,useMax?:boolean):boolean;
 setNativeProductionSpecialItem(marketId:string,industryId:string,special:OriginalProductionLifecycleRow['special']):void;
 nativeMarketFrameState(marketId:string):OriginalMarketFrameState|null;
 /** Explicit complete Memory is verified against captured military flags and becomes their sole state. */
 bindNativeMarketFrame(marketId:string,state:OriginalMarketFrameState):OriginalMarketFrameState;
 advanceNativePausedMarketConditions(seconds: number,context:{skipMarketAdvance:boolean},services?:NativeMarketFrameServices):void;
 advanceNativeMarketFrame(marketId:string,seconds:number,services?:NativeMarketFrameServices):void;
 nativeUIDataFrameState():OriginalCampaignUIDataFrame|null;
 bindNativeUIDataFrame(state:OriginalCampaignUIDataFrame):OriginalCampaignUIDataFrame;
 suppressNativeMusic(level:number):void;
 advanceNativeUIDataFrame(seconds:number,context:{paused:boolean},services?:Omit<OriginalCampaignUIDataServices,'convertUISecondsToDays'>):void;
 nativeAnimationManagerState():import('../../../src/campaign/rules/OriginalCampaignAnimations.mjs').OriginalAnimationManager|null;
 bindNativeAnimationManager(state:import('../../../src/campaign/rules/OriginalCampaignAnimations.mjs').OriginalAnimationManager):import('../../../src/campaign/rules/OriginalCampaignAnimations.mjs').OriginalAnimationManager;
 addNativeAnimation<T extends object>(animation:T):T;
 removeNativeAnimation(animation:object):void;
 advanceNativeAnimations(seconds:number,services?:import('../../../src/campaign/rules/OriginalCampaignAnimations.mjs').OriginalAnimationServices):void;
 addNativeCampaignPing(entity:object,options:import('../../../src/campaign/rules/OriginalCampaignPings.mjs').OriginalPingOptions,services?:Omit<import('../../../src/campaign/rules/OriginalCampaignPings.mjs').OriginalPingServices,'addPingIndicator'>):ReturnType<typeof import('../../../src/campaign/rules/OriginalCampaignPings.mjs').createOriginalPingScript>|null;
 advanceNativePingScript(script:import('../../../src/campaign/rules/OriginalCampaignPings.mjs').OriginalPingScript,seconds:number,services?:Omit<import('../../../src/campaign/rules/OriginalCampaignPings.mjs').OriginalPingServices,'addPingIndicator'>):{effects:(import('../../../src/campaign/rules/OriginalLocationFrame.mjs').OriginalLocationFrameEffect&{location:import('../../../src/campaign/rules/OriginalFleetWorld.mjs').OriginalFleetLocationRegistry;playerFleet:import('../../../src/campaign/rules/OriginalFleetData.mjs').OriginalNativeFleet|null})[]};
 nativeEngineFrameState():OriginalCampaignEngineState|null;
 bindNativeEngineFrame(state:OriginalCampaignEngineState):OriginalCampaignEngineState;
 advanceNativeEngineFrame(seconds:number,context:OriginalCampaignEngineContext,options?:{viewport?:import('../../../src/campaign/rules/OriginalCampaignViewport.mjs').OriginalCampaignViewport;economy?:NativeEconomyFrameOptions;locationServices?:NativeLocationFrameServices;factionServices?:Omit<OriginalFactionFrameServices,'convertFactionSecondsToDays'>;importantPeopleServices?:Omit<OriginalImportantPeopleServices,'convertImportantPeopleSecondsToDays'>;characterMemoryServices?:OriginalCampaignMemoryServices;intelServices?:NativeIntelServices;eventServices?:NativeCampaignEventServices;marketServices?:NativeMarketFrameServices;animationServices?:import('../../../src/campaign/rules/OriginalCampaignAnimations.mjs').OriginalAnimationServices;pingServices?:Omit<import('../../../src/campaign/rules/OriginalCampaignPings.mjs').OriginalPingServices,'addPingIndicator'>;uiDataServices?:Omit<OriginalCampaignUIDataServices,'convertUISecondsToDays'>;services?:Omit<OriginalCampaignEngineServices,'advanceEconomyBeforeClock'|'advanceClock'|'convertToDays'|'advanceEngineMemory'>}):ReturnType<typeof advanceOriginalCampaignEngine>;
 advanceNativeScheduledFrame(amountSeconds:number,options:NativeEconomyFrameOptions):DeepReadonly<{
  scope:'native-scheduled-economy-clock-and-open-timers-only';notificationMode:'external-adapter'|'native-receivers';schedule:import('../../../src/campaign/rules/OriginalMarketEconomySchedule.mjs').OriginalEconomySchedule;
  events:import('../../../src/campaign/rules/OriginalMarketEconomySchedule.mjs').OriginalEconomyScheduleEvent[];
  taskFrame:ReturnType<import('../../../src/campaign/rules/OriginalEconomyTasks.mjs').OriginalEconomyTaskRunner['advanceTask']>|null;
  economyFrame:ReturnType<NativeLiveEconomyDraft['economyClockFrame']>;clockAndRetail:ReturnType<NativeLiveEconomyDraft['advanceNativeClockAndOpenRetail']>;readyForAuthority:false;
 }>;
 nativeClockSnapshot():DeepReadonly<import('../../../src/campaign/rules/OriginalNativeClock.mjs').OriginalNativeClockState>;
 calendarDate():import('../../../src/campaign/rules/OriginalCalendar.mjs').OriginalCalendarDate;
 economyClockFrame(amountSeconds:number):ReturnType<import('../../../src/campaign/rules/OriginalNativeClock.mjs').OriginalNativeClock['calendarFrame']>;
 advanceNativeClockAndOpenRetail(amountSeconds:number):DeepReadonly<{scope:'native-clock-and-open-resource-timers-only';economyFrame:ReturnType<import('../../../src/campaign/rules/OriginalNativeClock.mjs').OriginalNativeClock['calendarFrame']>;frame:ReturnType<import('../../../src/campaign/rules/OriginalNativeClock.mjs').OriginalNativeClock['advance']>;marketsAdvanced:number;readyForAuthority:false}>;
 advanceOpenMarketTimers(marketId:string,options:{ticks:number;ticksPerSecond:number}):DeepReadonly<{minSWUpdateInterval:number;sinceSWUpdate:number;sinceLastCargoUpdate:number}>;
 refreshOpenMarketResources(marketId:string,options?:{month?:number}):DeepReadonly<{scope:'native-open-market-resource-phase-only';marketId:string;reports:{commodityId:string;before:number;after:number;limit:number;delta:number}[];sinceLastCargoUpdate:0;sinceSWUpdate:number;readyForAuthority:false}>;
 refreshIndustryFinances(marketId:string,industryId:string):DeepReadonly<OriginalIndustryFinanceResult>;
 reapplyMarketEconomicEffects(marketId:string,readMaxOutposts?:()=>number):DeepReadonly<NativeLiveMarketEffects>;
 /** Computes/installs incoming only; explicit elapsed days do not advance the world or settle credits. */
 computeIncoming(marketId:string,options:{days:number;uiUpdateOnly:boolean}):DeepReadonly<import('../../../src/campaign/rules/OriginalImmigration.mjs').OriginalImmigrationResult>;
 /** Installs population/incoming/incentives and synchronous growth economic effects without advancing world time. */
 advancePopulation(marketId:string,options:{days:number;uiUpdateOnly:boolean},readMaxOutposts?:()=>number):DeepReadonly<import('../../../src/campaign/rules/OriginalPopulation.mjs').OriginalPopulationObjectsResult>;
 reapplyCurrentMarketEconomicEffects(marketId:string,readMaxOutposts?:()=>number):DeepReadonly<Omit<NativeLiveMarketEffects,'scope'> & {scope:'shared-current-market-economic-effects-only'}>;
 reapplyEconomicEffects(readMaxOutposts?:()=>number):DeepReadonly<{scope:'shared-offline-economy-economic-effects-only';markets:NativeLiveMarketEffects[];readyForAuthority:false}>;
 snapshot():DeepReadonly<{scope:'native-shared-offline-economy-draft-only';encounters:NativeRetainedEncounters;factionRelations:OriginalFactionRelations|null;locationFrames:OriginalLocationFrame[]|null;engineFrame:OriginalCampaignEngineState|null;sensors:import('../../../src/campaign/rules/OriginalSensors.mjs').OriginalFleetSensorState|null;routeSpace:import('../../../src/campaign/rules/OriginalRouteSpace.mjs').OriginalRouteSpace|null;fleetServices:NativeFleetGenerationServices|null;patrols:import('../../../src/campaign/rules/OriginalMilitaryPatrols.mjs').OriginalPatrolState|null;notificationMode:'external-adapter'|'native-receivers'|null;economyNotifications:ReturnType<NativeLiveEconomyDraft['economyNotificationSnapshot']>;monthlyAccounts:import('../../../src/campaign/rules/OriginalMonthlyReport.mjs').OriginalMonthlyAccounts|null;nativeSchedule:import('../../../src/campaign/rules/OriginalMarketEconomySchedule.mjs').OriginalEconomySchedule|null;source:NativeSaveEconomyCapture['source'];inNewGameAdvance:boolean|null;nativeClock:import('../../../src/campaign/rules/OriginalNativeClock.mjs').OriginalNativeClockState|null;clockProvenance:import('../../../scripts/lib/campaign-native-save.mjs').NativeClockCapture['source']|null;economyListeners:ReturnType<import('../../../src/campaign/rules/OriginalEconomyListeners.mjs').OriginalEconomyUpdateListeners['snapshot']>|null;economyPass:NativeScheduledEconomyPass|null;markets:NativeLiveMarket[];readyForAuthority:false}>;
}

/** Native runtime remains incomplete; only explicit development hosts may persist it. */
export {NativeLiveEconomyDraft as NativeCampaignRuntime};
