import type { OriginalMarketVisit, OriginalMarketVisitRequest, OriginalMarketTradeRequest, OriginalMarketTradeQuote, OriginalMarketBasketRequest, OriginalMarketBasketQuote } from '../../src/campaign/rules/OriginalMarket.mjs';
import type { CampaignView, CargoPreviewRequest, CargoPreviewResponse } from '../../src/campaign/client/Protocol.js';
import type { SimulationStatus } from './SimulationLoop.mjs';
import type { DeepReadonly, ReadonlyWorld, Principal, CommandReceipt, EventBatch, RulesLock } from '../../src/campaign/Types.js';
import type { LogisticsInput, LogisticsQuote } from '../../src/campaign/rules/OriginalLogistics.mjs';
export class CampaignService {
  constructor(options: { filename: string; timeoutMs?: number; enableNativeDevelopment?: boolean });
  ready(): Promise<DeepReadonly<{ epoch: string; rules: RulesLock; nativeDevelopmentEnabled:boolean }>>;
  createNativeDevelopment(input:unknown):Promise<DeepReadonly<import('./native/DevelopmentWorld.mjs').NativeDevelopmentSummary>>;
  nativeDevelopmentStatus(worldId:string):Promise<DeepReadonly<import('./native/DevelopmentWorld.mjs').NativeDevelopmentSummary>>;
  projectNativeDevelopmentPlayer(worldId:string,playerId:string):Promise<DeepReadonly<import('./native/DevelopmentWorld.mjs').NativeDevelopmentPlayer>>;
  projectNativeDevelopmentScene(worldId:string,playerId:string,input:unknown):Promise<DeepReadonly<import('../../src/campaign/client/NativeProtocol.js').NativeSceneFrame>>;
  projectNativeDevelopmentObservations(worldId:string,playerId:string,input:unknown):Promise<DeepReadonly<import('../../src/campaign/client/NativeProtocol.js').NativeFleetObservations>>;
  executeNativeDevelopment(principal:Principal,command:unknown):Promise<DeepReadonly<CommandReceipt>>;
  projectNativeDevelopmentFrameEvents(worldId:string,playerId:string,input:import('./native/FrameEffects.mjs').NativeFrameEventsRequest):Promise<DeepReadonly<import('./native/FrameEffects.mjs').NativePlayerFrameEvents>>;
  nativeDevelopmentEventsSince(worldId:string,revision:number,limit?:number):Promise<DeepReadonly<EventBatch[]>>;
  create(world: unknown): Promise<ReadonlyWorld>;
  read(worldId: string): Promise<ReadonlyWorld>;
  projectPlayer(worldId: string, playerId: string): Promise<DeepReadonly<CampaignView>>;
  execute(principal: Principal, command: unknown): Promise<DeepReadonly<CommandReceipt>>;
  eventsSince(worldId: string, revision: number, limit?: number): Promise<DeepReadonly<EventBatch[]>>;
  quoteLogistics(input: LogisticsInput): Promise<DeepReadonly<LogisticsQuote>>;
  quoteCargo(worldId: string, playerId: string, input: CargoPreviewRequest): Promise<DeepReadonly<CargoPreviewResponse>>;
  browseMarket(worldId: string, playerId: string, input: OriginalMarketVisitRequest & { worldId: string; epoch: string }): Promise<DeepReadonly<OriginalMarketVisit & { epoch: string }>>;
  quoteMarketBasket(worldId: string, playerId: string, input: OriginalMarketBasketRequest & { worldId: string; epoch: string }): Promise<DeepReadonly<OriginalMarketBasketQuote & { worldId: string; epoch: string }>>;
  quoteMarket(worldId: string, playerId: string, input: OriginalMarketTradeRequest): Promise<DeepReadonly<OriginalMarketTradeQuote>>;
  startSimulation(worldId: string): Promise<SimulationStatus>;
  stopSimulation(worldId: string): Promise<SimulationStatus>;
  simulationStatus(worldId: string): Promise<SimulationStatus>;
  close(): Promise<number>;
}
