/** Installed-jar module constructors and actual plugin picks; no CampaignEngine/Fleet constructor or game loop. */
import java.lang.reflect.*;import java.util.*;import org.json.*;
import com.fs.starfarer.campaign.CampaignEngine;import com.fs.starfarer.campaign.ModAndPluginData;import com.fs.starfarer.campaign.ai.*;import com.fs.starfarer.campaign.fleet.CampaignFleet;
import com.fs.starfarer.api.PluginPick;import com.fs.starfarer.api.campaign.*;import com.fs.starfarer.api.campaign.ai.*;import com.fs.starfarer.api.impl.campaign.CoreCampaignPluginImpl;
public class NativeFleetAIInputs {
 static Object field(Object o,String name)throws Exception{Field f=o.getClass().getDeclaredField(name);f.setAccessible(true);return f.get(o);}
 static JSONObject timer(Object o)throws Exception {JSONObject r=new JSONObject();for(String k:new String[]{"minInterval","maxInterval","currInterval","elapsed","intervalElapsed"})r.put(k,field(o,k));return r;}
 static JSONObject values(Object o,String...keys)throws Exception {JSONObject r=new JSONObject();for(String k:keys){Object v=field(o,k);r.put(k,v==null?JSONObject.NULL:v);}return r;}
 static BaseCampaignPlugin pick(String id,NavigationModulePlugin module,CampaignPlugin.PickPriority priority){return new BaseCampaignPlugin(){public String getId(){return id;}public PluginPick<NavigationModulePlugin> pickNavigationAIModule(CampaignFleetAPI f,ModularFleetAIAPI a){return new PluginPick<>(module,priority);}};}
 public static void main(String[] args)throws Exception {
  org.apache.log4j.Logger.getRootLogger().setLevel(org.apache.log4j.Level.OFF);
  Class<?> uc=Class.forName("sun.misc.Unsafe");Field uf=uc.getDeclaredField("theUnsafe");uf.setAccessible(true);Object unsafe=uf.get(null);Method allocate=uc.getMethod("allocateInstance",Class.class);CampaignEngine engine=(CampaignEngine)allocate.invoke(unsafe,CampaignEngine.class);CampaignFleet fleet=(CampaignFleet)allocate.invoke(unsafe,CampaignFleet.class);
  Field singleton=CampaignEngine.class.getDeclaredField("instance");singleton.setAccessible(true);singleton.set(null,engine);ModAndPluginData registry=new ModAndPluginData();Field data=CampaignEngine.class.getDeclaredField("modAndPluginData");data.setAccessible(true);data.set(engine,registry);
  Field rf=Class.forName("java.lang.Math$RandomNumberGeneratorHolder").getDeclaredField("randomNumberGenerator");rf.setAccessible(true);Random random=(Random)rf.get(null);JSONArray cases=new JSONArray();
  for(long seed:new long[]{0L,731L,-9223372036854775808L}){random.setSeed(seed);ModularFleetAI ai=new ModularFleetAI(fleet);Object nav=ai.getNavModule(),assignment=ai.getAssignmentModule(),strategic=ai.getStrategicModule(),tactical=ai.getTacticalModule();JSONObject result=new JSONObject().put("seed",Long.toString(seed)).put("strategicTracker",timer(field(strategic,"avoidTracker"))).put("tacticalTracker",timer(field(tactical,"tracker"))).put("nextLong",Long.toString(random.nextLong()));
   result.put("allFleetIdentity",field(nav,"fleet")==fleet&&field(assignment,"fleet")==fleet&&field(strategic,"fleet")==fleet&&field(tactical,"fleet")==fleet).put("aiIdentity",field(strategic,"ai")==ai&&field(tactical,"ai")==ai);
   result.put("navigation",values(nav,"hasDest")).put("assignment",values(assignment,"fr")).put("assignmentCount",((List<?>)field(assignment,"assignments")).size()).put("tactical",values(tactical,"travelDest","priorityTarget","travelDur","targetDur","target","largestEnemy","pursueDuration","pursuitDays","beforeSearchPattern","plan","followMode","isFleeing","isMaintainingContact","slowDown","didSlowDownBark")).put("actionText",ai.getActionTextOverride()).put("abilityCount",((Map<?,?>)field(ai,"abilityAI")).size()).put("noAICount",((Set<?>)field(ai,"noAIAbilities")).size());cases.put(result);
  }
  NavigationModule a=new NavigationModule(fleet,null),b=new NavigationModule(fleet,null);BaseCampaignPlugin first=pick("same",a,CampaignPlugin.PickPriority.MOD_GENERAL),last=pick("last",b,CampaignPlugin.PickPriority.MOD_GENERAL);registry.addPlugin(first);registry.addPlugin(last);boolean tie=registry.pickNavigationAIModule(fleet,null)==b;registry.addPlugin(pick("same",a,CampaignPlugin.PickPriority.MOD_SPECIFIC));boolean higher=registry.pickNavigationAIModule(fleet,null)==a;BaseCampaignPlugin nullable=pick(null,a,CampaignPlugin.PickPriority.CORE_GENERAL);registry.addPlugin(nullable);registry.addPlugin(nullable);int nullCopies=Collections.frequency(registry.getPlugins(),nullable);registry.removePlugin(null);int nullAfter=Collections.frequency(registry.getPlugins(),nullable);
  CoreCampaignPluginImpl core=new CoreCampaignPluginImpl();System.out.print(new JSONObject().put("cases",cases).put("picks",new JSONObject().put("tieLast",tie).put("higher",higher).put("replacementMovedToEnd",registry.getPlugins().get(1).getId().equals("same")).put("nullCopies",nullCopies).put("nullAfterRemove",nullAfter)).put("core",new JSONObject().put("id",core.getId()).put("transient",core.isTransient()).put("modulePickNull",core.pickNavigationAIModule(fleet,null)==null&&core.pickAssignmentAIModule(fleet,null)==null&&core.pickStrategicAIModule(fleet,null)==null&&core.pickTacticalAIModule(fleet,null)==null)));
 }
}
