/** Real installed DModManager, HullVariantSpec and GenericPluginManager. Settings specs only are injected. */
import com.fs.starfarer.api.fleet.MutableFleetStatsAPI;import com.fs.starfarer.api.util.DynamicStatsAPI;import java.lang.reflect.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.awt.Color;import org.json.*;
import com.fs.starfarer.api.*;import com.fs.starfarer.api.campaign.*;import com.fs.starfarer.api.combat.*;import com.fs.starfarer.api.impl.campaign.DModManager;import com.fs.starfarer.loading.oO0O;import com.fs.starfarer.loading.SpecStore;import com.fs.starfarer.loading.specs.g;import com.fs.starfarer.loading.specs.O00O;import com.fs.starfarer.loading.specs.OOOo;import com.fs.starfarer.loading.specs.HullVariantSpec;import com.fs.starfarer.campaign.GenericPluginManager;
public class NativeDModInputs {
 static JSONArray strings(Iterable<?> items){JSONArray a=new JSONArray();for(Object x:items)a.put(x.toString());return a;}
 static String nullable(JSONObject r,String k)throws Exception{return r.isNull(k)?null:r.getString(k);}
 public static void main(String[] args)throws Exception {
  JSONObject input=new JSONObject(new String(System.in.readAllBytes(),StandardCharsets.UTF_8));Map<String,g> hulls=new LinkedHashMap<>();Map<String,O00O> mods=new LinkedHashMap<>();GenericPluginManager plugins=new GenericPluginManager();
  Method register=null;for(Method m:oO0O.class.getDeclaredMethods())if(Modifier.isStatic(m.getModifiers())&&m.getReturnType()==void.class&&Arrays.equals(m.getParameterTypes(),new Class[]{String.class,g.class})){register=m;register.setAccessible(true);break;}if(register==null)throw new IllegalStateException("Hull registry unavailable");
  JSONArray ms=input.getJSONArray("mods");for(int i=0;i<ms.length();i++){JSONObject r=ms.getJSONObject(i);O00O s=new O00O();s.setId(r.getString("id"));JSONArray tags=r.getJSONArray("tags");for(int j=0;j<tags.length();j++)s.addTag(tags.getString(j));mods.put(s.getId(),s);SpecStore.o00000(O00O.class,s.getId(),s);}
  JSONObject hs=input.getJSONObject("hulls");for(Iterator<?> it=hs.keys();it.hasNext();){String id=(String)it.next();JSONObject r=hs.getJSONObject(id);g h=new g(id);h.setBaseHullId(nullable(r,"baseHullId"));h.setDParentHullId(nullable(r,"dParentHullId"));h.setRestoreToBase(r.getBoolean("isRestoreToBase"));h.setNoCRLossSeconds((float)r.getDouble("noCRLossTime"));h.setFighterBays(r.getInt("fighterBays"));h.setShipDefenseId(nullable(r,"defenseId"));h.setShieldSpec(new OOOo(ShieldAPI.ShieldType.valueOf(r.getString("shieldType")),0,0,0,0,0,Color.WHITE,Color.WHITE));
   for(String key:new String[]{"hints","tags","builtInMods","builtInWings"}){JSONArray a=r.getJSONArray(key);for(int j=0;j<a.length();j++){String v=a.getString(j);switch(key){case "hints":h.getHints().add(ShipHullSpecAPI.ShipTypeHints.valueOf(v));break;case "tags":h.addTag(v);break;case "builtInMods":h.getBuiltInMods().add(v);break;default:h.getBuiltInWings().add(v);}}}
   JSONObject weapons=r.getJSONObject("builtInWeapons");for(Iterator<?> it2=weapons.keys();it2.hasNext();){String slot=(String)it2.next();h.getBuiltInWeapons().put(slot,weapons.getString(slot));}hulls.put(id,h);register.invoke(null,id,h);
  }
  Global.setSettings((SettingsAPI)Proxy.newProxyInstance(SettingsAPI.class.getClassLoader(),new Class[]{SettingsAPI.class},(p,m,a)->{switch(m.getName()){case "getInt":return input.getJSONObject("settings").getInt((String)a[0]);case "getFloat":return (float)input.getJSONObject("settings").getDouble((String)a[0]);case "getBoolean":return input.getJSONObject("settings").getBoolean((String)a[0]);case "getColor":{JSONArray c=input.getJSONObject("settings").getJSONArray((String)a[0]);return new Color(c.getInt(0),c.getInt(1),c.getInt(2),c.length()>3?c.getInt(3):255);}case "getHullSpec":return hulls.get(a[0]);case "getHullModSpec":return mods.get(a[0]);case "getAllHullModSpecs":return new ArrayList<>(SpecStore.o00000(O00O.class));}throw new UnsupportedOperationException(m.getName());}));
  Global.setSector((SectorAPI)Proxy.newProxyInstance(SectorAPI.class.getClassLoader(),new Class[]{SectorAPI.class},(p,m,a)->{if(m.getName().equals("getGenericPlugins"))return plugins;throw new UnsupportedOperationException(m.getName());}));
  JSONArray ordered=new JSONArray();for(Object o:SpecStore.o00000(O00O.class)){O00O s=(O00O)o;ordered.put(new JSONObject().put("id",s.getId()).put("tags",strings(s.getTags())));}
  JSONArray results=new JSONArray(),cases=input.getJSONArray("cases");for(int i=0;i<cases.length();i++){
   JSONObject c=cases.getJSONObject(i);HullVariantSpec v=new HullVariantSpec("oracle",hulls.get(c.getString("hullId")));for(String key:new String[]{"mods","perma","sMods","suppressed"}){JSONArray a=c.getJSONArray(key);for(int j=0;j<a.length();j++){String id=a.getString(j);switch(key){case "mods":v.addMod(id);break;case "perma":v.addPermaMod(id,false);break;case "sMods":v.addPermaMod(id,true);break;default:v.addSuppressedMod(id);}}}
   CampaignFleetAPI recoverer=null;if(c.has("recoveryReduction")){DynamicStatsAPI dynamic=(DynamicStatsAPI)Proxy.newProxyInstance(DynamicStatsAPI.class.getClassLoader(),new Class[]{DynamicStatsAPI.class},(p,m,a)->{if(m.getName().equals("getValue")&&a[0].equals("ship_dmod_reduction_mod"))return (float)c.getDouble("recoveryReduction");throw new UnsupportedOperationException(m.getName());});MutableFleetStatsAPI stats=(MutableFleetStatsAPI)Proxy.newProxyInstance(MutableFleetStatsAPI.class.getClassLoader(),new Class[]{MutableFleetStatsAPI.class},(p,m,a)->{if(m.getName().equals("getDynamic"))return dynamic;throw new UnsupportedOperationException(m.getName());});recoverer=(CampaignFleetAPI)Proxy.newProxyInstance(CampaignFleetAPI.class.getClassLoader(),new Class[]{CampaignFleetAPI.class},(p,m,a)->{if(m.getName().equals("getStats"))return stats;throw new UnsupportedOperationException(m.getName());});}
   DModManager.reduceNextDmodsBy=c.getInt("reduce");DModManager.assumeAllShipsAreAutomated=c.getBoolean("assumeAuto");Random random=new Random(Long.parseLong(c.getString("seed")));Boolean changed=null;switch(c.getString("mode")){case "fixed":DModManager.addDMods(v,c.getBoolean("destroyed"),c.getInt("num"),random);break;case "combat":DModManager.addDMods(v,c.getBoolean("destroyed"),c.getBoolean("own"),recoverer,random);break;case "remove":DModManager.removeDMod(v,c.getString("remove"));break;case "setDHull":changed=DModManager.setDHull(v);break;}
   results.put(new JSONObject().put("hullId",v.getHullSpec().getHullId()).put("source",v.getSource()==null?JSONObject.NULL:v.getSource().name()).put("mods",strings(v.getHullMods())).put("perma",strings(v.getPermaMods())).put("sMods",strings(v.getSMods())).put("suppressed",strings(v.getSuppressedMods())).put("reduce",DModManager.reduceNextDmodsBy).put("count",DModManager.getNumDMods(v)).put("nonBuiltInCount",DModManager.getNumNonBuiltInDMods(v)).put("nextLong",Long.toString(random.nextLong())).put("changed",changed==null?JSONObject.NULL:changed));
  }
  System.out.print(new JSONObject().put("mods",ordered).put("results",results));
 }
}
