import { arkWeaponFxTextures } from './ArkWeaponFX';
import art from './adun-fx-art.json';
import motionArt from './adun-motion-art.json';
/** Generated by the user's local gpt-image-2.5 provider. Not native/generic stand-ins. */
export const ADUN_FX_ROOT='/game-assets/graphics/fx/web_spear_of_adun/';
export const ADUN_FX={ignition:ADUN_FX_ROOT+'ignition.png',core:ADUN_FX_ROOT+'core.png',lance:ADUN_FX_ROOT+'lance.png',muzzle:ADUN_FX_ROOT+'muzzle.png',impact:ADUN_FX_ROOT+'impact.png',beam:ADUN_FX_ROOT+'beam.png',exhaust:ADUN_FX_ROOT+'exhaust.png',shutdown:ADUN_FX_ROOT+'shutdown.png'} as const;
export const adunMotionArt = motionArt;
export type AdunMotionKey = keyof typeof motionArt.clips;
export interface AdunMotionFrame {
  readonly url: string;
  readonly pivotX: number;
  readonly pivotY: number;
}
function clip(key: AdunMotionKey, fps: number, loop: boolean) {
  return { fps, loop, frames: motionArt.clips[key].frames.map(f => ({
    url: ADUN_FX_ROOT + 'motion/' + f.file, pivotX: f.pivotX, pivotY: f.pivotY,
  })) };
}
export const adunMotionClips = {
  exhaust: clip('exhaust', 12, true), core: clip('core', 8, true),
  beam: clip('beam', 16, true), lance: clip('lance', 12, true),
  muzzle: clip('muzzle', 30, false), impact: clip('impact', 20, false),
} as const;
export const adunFXTextures = [
  ...arkWeaponFxTextures,
  ...Object.values(ADUN_FX),
  ...Object.values(adunMotionClips).flatMap(c => c.frames.map(f => f.url)),
];
/** Pure simulation-time sampling. Adjacent painted frames crossfade with unit total energy.
 * One-shots use the authoritative event lifetime; no wall clock, private timer or static fallback.
 */
export function sampleAdunMotion(key: AdunMotionKey, time: number, duration?: number): readonly { frame: AdunMotionFrame; weight: number }[] {
  if (!Number.isFinite(time) || time < 0) return [];
  const c = adunMotionClips[key], n = c.frames.length;
  const life = duration ?? n / c.fps;
  if (!c.loop && (!Number.isFinite(life) || life <= 0 || time >= life)) return [];
  const phase = c.loop ? (time * c.fps) % n : time / life * (n - 1);
  const index = Math.floor(phase), mix = phase - index;
  const current = { frame: c.frames[index], weight: 1 - mix };
  if (mix <= 1e-6) return [current];
  return [current, { frame: c.frames[(index + 1) % n], weight: mix }];
}
export const adunFxArt=art;
/** IDs are the authored artwork contract, not a substring/faction guess. */
export function adunWeaponFxScale(id:string):number {
  switch(id){case 'web_ark_solar_lance':return 1.4;case 'web_ark_phase_battery':return .85;case 'web_ark_ion_battery':return .45;case 'web_ark_guard_prism':return .2;case 'web_adun_solar_lance':return 1;case 'web_adun_phase_disruptor':return .58;case 'web_adun_ion_repeater':return .32;case 'web_adun_interception_prism':return .2;default:return 0;}
}
